{
  "openapi": "3.0.3",
  "info": {
    "version": "1.0.0",
    "title": "Clear Books API",
    "description": "REST API for interfacing with Clear Books products\n\n# Authentication\n\nThis API uses OAuth 2 for authentication and authorisation. A compatible OAuth 2 client library or sufficient knowledge to implement an OAuth 2 client is required.\n\nOnly confidential clients are supported and must use the \"Authorization code\" grant type. PKCE is supported (and recommended) but not mandatory. \n\n<!-- ReDoc-Inject: <SecurityDefinitions /> -->\n\n## Registration\n\nTo obtain API crede[...]",
    "termsOfService": "https://www.clearbooks.co.uk/terms/",
    "x-logo": {
      "url": "https://secure.clearbookscdn.uk/themes/minimaal-clearbooks/image/brand/logo-white.svg",
      "backgroundColor": "#1b5883",
      "altText": "Clear Books"
    },
    "x-jentic-source-url": "https://www.clearbooks.co.uk/support/api/"
  },
  "servers": [
    {
      "url": "https://api.clearbooks.co.uk/v1"
    }
  ],
  "tags": [
    {
      "name": "Businesses",
      "description": "Businesses that the current user has access to"
    },
    {
      "name": "Account Codes",
      "description": "An account code, often called a 'nominal code' defines an account in the chart of accounts of a business' accounting ledger"
    },
    {
      "name": "Bank Accounts",
      "description": "A bank account represents either a real-world bank account in which the business has cash stored, or a logical store of cash defined by the business"
    },
    {
      "name": "Customers",
      "description": "A customer represents an entity to which the business sells products or services"
    },
    {
      "name": "Suppliers",
      "description": "A supplier represents an entity from which the business buys products or services"
    },
    {
      "name": "Sales",
      "description": "Sales documents such as invoices, quotes and sales credit notes are issued to customers and represent a sale or prospective sale"
    },
    {
      "name": "Purchases",
      "description": "Purchase documents such as bills, expenses and purchase credit notes are received from suppliers and represent a purchase or prospective purchase"
    },
    {
      "name": "Payments",
      "description": "Payments received or made to cover a sale or purchase represent a transfer of money between the business and a customer or supplier"
    },
    {
      "name": "Allocations",
      "description": "Allocations represent the association of a payment to an invoice or bill in order to clear or partly clear the balance\n"
    },
    {
      "name": "Stock Items",
      "description": "Stock items represent inventory that can be sold and purchased using sales and purchase documents"
    },
    {
      "name": "Sales Attachments",
      "description": "Files can be attached to sales documents for record keeping"
    },
    {
      "name": "Purchases Attachments",
      "description": "Files can be attached to purchase documents for record keeping"
    },
    {
      "name": "VAT",
      "description": "VAT rates and treatments represent the valid VAT settings that can be used on sales and purchase documents"
    },
    {
      "name": "Bank Feeds",
      "description": "Bank feeds allow financial institutions to send transaction data direct to Clear Books and have it associated with a bank account"
    },
    {
      "name": "Bank Statements",
      "description": "Bank Statements represent transactions ready to be explained"
    },
    {
      "name": "Transactions",
      "description": "A transaction represents a movement of money between a business's accounts"
    },
    {
      "name": "General Ledger",
      "description": "The general ledger lists debits and credits from all transactions"
    },
    {
      "name": "Trial Balance",
      "description": "The trial balance lists the balances of all of the business's accounts"
    },
    {
      "name": "Journals",
      "description": "A journal is a type of transaction created to move money between accounts outside of normal business operations"
    }
  ],
  "paths": {
    "/businesses": {
      "get": {
        "summary": "List all businesses for the current user",
        "operationId": "listBusinesses",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "OAuth2": [
              "businesses:read"
            ]
          }
        ]
      }
    },
    "/businesses/{businessId}": {
      "get": {
        "summary": "Retrieve a single business",
        "operationId": "getBusiness",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "OAuth2": [
              "businesses:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a business",
        "operationId": "updateBusiness",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "OAuth2": [
              "businesses:write"
            ]
          }
        ]
      }
    },
    "/accounting/accountCodes": {
      "get": {
        "summary": "List all account codes",
        "operationId": "listAccountCodes",
        "tags": [
          "Account Codes"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.account_codes:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create an account code",
        "operationId": "createAccountCode",
        "tags": [
          "Account Codes"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.account_codes:write"
            ]
          }
        ]
      }
    },
    "/accounting/accountCodes/{accountCodeId}": {
      "get": {
        "summary": "Retrieve a single account code",
        "operationId": "getAccountCode",
        "tags": [
          "Account Codes"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.account_codes:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update an account code",
        "operationId": "updateAccountCode",
        "tags": [
          "Account Codes"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.account_codes:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete account code",
        "operationId": "deleteAccountCode",
        "tags": [
          "Account Codes"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.account_codes:write"
            ]
          }
        ]
      }
    },
    "/accounting/bankAccounts": {
      "get": {
        "summary": "List all bank accounts",
        "operationId": "listBankAccounts",
        "tags": [
          "Bank Accounts"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_accounts:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a bank account",
        "operationId": "createBankAccount",
        "tags": [
          "Bank Accounts"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_accounts:write"
            ]
          }
        ]
      }
    },
    "/accounting/bankAccounts/{bankAccountId}": {
      "get": {
        "summary": "Retrieve a single bank account",
        "operationId": "getBankAccount",
        "tags": [
          "Bank Accounts"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_accounts:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a bank account",
        "operationId": "updateBankAccount",
        "tags": [
          "Bank Accounts"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_accounts:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete bank account",
        "operationId": "deleteBankAccount",
        "tags": [
          "Bank Accounts"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_accounts:write"
            ]
          }
        ]
      }
    },
    "/accounting/customers": {
      "get": {
        "summary": "List all customers",
        "operationId": "listCustomers",
        "tags": [
          "Customers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.customers:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a customer",
        "operationId": "createCustomer",
        "tags": [
          "Customers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.customers:write"
            ]
          }
        ]
      }
    },
    "/accounting/customers/{customerId}": {
      "get": {
        "summary": "Retrieve a single customer",
        "operationId": "getCustomer",
        "tags": [
          "Customers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.customers:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a customer",
        "operationId": "updateCustomer",
        "tags": [
          "Customers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.customers:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete customer",
        "operationId": "deleteCustomer",
        "tags": [
          "Customers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.customers:write"
            ]
          }
        ]
      }
    },
    "/accounting/suppliers": {
      "get": {
        "summary": "List all suppliers",
        "operationId": "listSuppliers",
        "tags": [
          "Suppliers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.suppliers:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a supplier",
        "operationId": "createSupplier",
        "tags": [
          "Suppliers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.suppliers:write"
            ]
          }
        ]
      }
    },
    "/accounting/suppliers/{supplierId}": {
      "get": {
        "summary": "Retrieve a single supplier",
        "operationId": "getSupplier",
        "tags": [
          "Suppliers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.suppliers:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a supplier",
        "operationId": "updateSupplier",
        "tags": [
          "Suppliers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.suppliers:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete supplier",
        "operationId": "deleteSupplier",
        "tags": [
          "Suppliers"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.suppliers:write"
            ]
          }
        ]
      }
    },
    "/accounting/sales/{salesType}": {
      "get": {
        "summary": "List all sales documents of a given type (e.g invoices, quotes)",
        "operationId": "listSalesByType",
        "tags": [
          "Sales"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a sales document of the given type",
        "operationId": "createSales",
        "tags": [
          "Sales"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:write"
            ]
          }
        ]
      }
    },
    "/accounting/sales/{salesType}/{salesId}": {
      "get": {
        "summary": "Retrieve a single sales document",
        "operationId": "getSalesDocument",
        "description": "Retrieve a sales document. If the provided ID refers to a voided previous revision of a document, a redirect to the current revision will be returned.",
        "tags": [
          "Sales"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a sales document",
        "operationId": "updateSalesDocument",
        "description": "Update a sales document. For a non-draft invoice or credit note, the original document will be voided (soft deleted) and a new copy created with a new ID. For a quote or draft invoice, the document will be updated in-place and retain its original ID. You only need to provide the fields you want to update. No fields on the body of the document are required.",
        "tags": [
          "Sales"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete sales document",
        "operationId": "deleteSalesDocument",
        "description": "Delete a sales document. Non-draft invoices and credit notes will be voided (soft deleted). Quotes and draft invoices will be hard deleted.",
        "tags": [
          "Sales"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:write"
            ]
          }
        ]
      }
    },
    "/accounting/purchases/{purchaseType}": {
      "get": {
        "summary": "List all purchase documents of a given type (e.g bills, expenses)",
        "operationId": "listPurchasesByType",
        "tags": [
          "Purchases"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a purchase document of the given type",
        "operationId": "createPurchase",
        "tags": [
          "Purchases"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:write"
            ]
          }
        ]
      }
    },
    "/accounting/purchases/{purchaseType}/{purchaseId}": {
      "get": {
        "summary": "Retrieve a single purchase document",
        "operationId": "getPurchaseDocument",
        "description": "Retrieve a purchase document. If the provided ID refers to a voided previous revision of a document, a redirect to the current revision will be returned.",
        "tags": [
          "Purchases"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a purchase document",
        "operationId": "updatePurchaseDocument",
        "description": "Update a purchase document. For a non-draft bill or credit note, the original document will be voided (soft deleted) and a new copy created with a new ID. For a draft bill, the document will be updated in-place. You only need to provide the fields you want to update. No fields on the body of the document are required.",
        "tags": [
          "Purchases"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete purchase document",
        "operationId": "deletePurchaseDocument",
        "description": "Delete a purchase document. Non-draft bills and credit notes will be voided (soft deleted). Draft bills will be hard deleted.",
        "tags": [
          "Purchases"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:write"
            ]
          }
        ]
      }
    },
    "/accounting/payments": {
      "get": {
        "summary": "List all payments",
        "operationId": "listPayments",
        "tags": [
          "Payments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.payments:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a payment",
        "operationId": "createPayment",
        "tags": [
          "Payments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.payments:write"
            ]
          }
        ]
      }
    },
    "/accounting/payments/{paymentId}": {
      "get": {
        "summary": "Retrieve a single payment",
        "operationId": "getPayment",
        "tags": [
          "Payments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.payments:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a payment",
        "operationId": "updatePayment",
        "tags": [
          "Payments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.payments:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete payment",
        "operationId": "deletePayment",
        "tags": [
          "Payments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.payments:write"
            ]
          }
        ]
      }
    },
    "/accounting/allocations/{invoiceType}": {
      "get": {
        "summary": "List allocations",
        "operationId": "listAllocations",
        "tags": [
          "Allocations"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.allocations:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create an allocation",
        "description": "> **Payments and credit notes that use a different currency to the base currency of the Clear Books account, can only be allocated to invoices and bills of the same currency.**\n",
        "operationId": "createAllocation",
        "tags": [
          "Allocations"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.allocations:write"
            ]
          }
        ]
      }
    },
    "/accounting/allocations/{invoiceType}/{allocationId}": {
      "get": {
        "summary": "Retrieve an allocation",
        "operationId": "getAllocation",
        "tags": [
          "Allocations"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.allocations:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete an allocation",
        "operationId": "deleteAllocation",
        "tags": [
          "Allocations"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.allocations:write"
            ]
          }
        ]
      }
    },
    "/accounting/stockItems": {
      "get": {
        "summary": "List all stock items",
        "operationId": "listStockItems",
        "tags": [
          "Stock Items"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.stock_items:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a stock item",
        "operationId": "createStockItem",
        "tags": [
          "Stock Items"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.stock_items:write"
            ]
          }
        ]
      }
    },
    "/accounting/stockItems/{stockItemId}": {
      "get": {
        "summary": "Retrieve a single stock item",
        "operationId": "getStockItem",
        "tags": [
          "Stock Items"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.stock_items:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a stock item",
        "operationId": "updateStockItem",
        "tags": [
          "Stock Items"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.stock_items:write"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete stock item",
        "operationId": "deleteStockItem",
        "tags": [
          "Stock Items"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.stock_items:write"
            ]
          }
        ]
      }
    },
    "/accounting/sales/{salesType}/{salesId}/attachments": {
      "get": {
        "summary": "List all attachments",
        "operationId": "listAttachments",
        "tags": [
          "Sales Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:read"
            ]
          }
        ]
      }
    },
    "/accounting/sales/{salesType}/{salesId}/attachments/{fileName}": {
      "post": {
        "summary": "Create an attachment",
        "operationId": "createAttachment",
        "tags": [
          "Sales Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:write"
            ]
          }
        ]
      }
    },
    "/accounting/sales/{salesType}/{salesId}/attachments/{attachmentId}": {
      "get": {
        "summary": "Retrieve a single attachment",
        "operationId": "getAttachment",
        "tags": [
          "Sales Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete attachment",
        "operationId": "deleteAttachment",
        "tags": [
          "Sales Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.sales:write"
            ]
          }
        ]
      }
    },
    "/accounting/purchases/{purchaseType}/{purchaseId}/attachments": {
      "get": {
        "summary": "List all attachments",
        "operationId": "listAttachments",
        "tags": [
          "Purchases Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:read"
            ]
          }
        ]
      }
    },
    "/accounting/purchases/{purchaseType}/{purchaseId}/attachments/{fileName}": {
      "post": {
        "summary": "Create an attachment",
        "operationId": "createAttachment",
        "tags": [
          "Purchases Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:write"
            ]
          }
        ]
      }
    },
    "/accounting/purchases/{purchaseType}/{purchaseId}/attachments/{attachmentId}": {
      "get": {
        "summary": "Retrieve a single attachment",
        "operationId": "getAttachment",
        "tags": [
          "Purchases Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete attachment",
        "operationId": "deleteAttachment",
        "tags": [
          "Purchases Attachments"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.purchases:write"
            ]
          }
        ]
      }
    },
    "/accounting/vatTreatments/{vatType}": {
      "get": {
        "summary": "List VAT treatments",
        "operationId": "listVatTreatments",
        "tags": [
          "VAT"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.vat:read"
            ]
          }
        ]
      }
    },
    "/accounting/vatRates/{vatType}": {
      "get": {
        "summary": "List VAT rates",
        "operationId": "listVatRates",
        "tags": [
          "VAT"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.vat:read"
            ]
          }
        ]
      }
    },
    "/accounting/bankFeeds": {
      "post": {
        "summary": "Create a bank feed",
        "description": "### Linking to an existing bank account\n\nA bank feed can be created for an existing Clear Books bank account in one of two ways:\n\n1. By specifying an `accountId` returned from one of the bank accounts endpoints.\n\n2. By providing and `accountNumber` and `sortCode` that match an account which already exists in Clear Books.\n\n### Creating a new bank account\n\nIf a bank account does not already exist in Clear Books for the bank feed you wish to create, then you must p[...]",
        "operationId": "createBankFeed",
        "tags": [
          "Bank Feeds"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_feeds:write"
            ]
          }
        ]
      }
    },
    "/accounting/bankStatements": {
      "post": {
        "summary": "Create a bank statement",
        "description": "### Statement consolidation\n\nClear Books will consolidate statements posted using this API call into monthly statements ready to be explained.\nOne statement in Clear Books will be maintained for each calendar month based on the transaction date.\n\nThe IDs returned by this call represent the statement that the posted transactions were added to, regardless of whether a new\nstatement was created or the transactions were appended to an existing statement.\n\n### Deduplic[...]",
        "operationId": "createBankFeedStatement",
        "tags": [
          "Bank Statements"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.bank_statements:write"
            ]
          }
        ]
      }
    },
    "/accounting/transactions": {
      "get": {
        "summary": "List transactions",
        "operationId": "listTransactions",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.transactions:read"
            ]
          }
        ]
      }
    },
    "/accounting/generalLedger": {
      "get": {
        "summary": "Get general ledger",
        "operationId": "getGeneralLedger",
        "tags": [
          "General Ledger"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.transactions:read"
            ]
          }
        ]
      }
    },
    "/accounting/trialBalance": {
      "get": {
        "summary": "Get trial balance",
        "operationId": "getTrialBalance",
        "tags": [
          "Trial Balance"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.transactions:read"
            ]
          }
        ]
      }
    },
    "/accounting/journals": {
      "post": {
        "summary": "Create a journal",
        "description": "The sum of amounts of all lines in the journal must add up to 0.",
        "operationId": "createJournal",
        "tags": [
          "Journals"
        ],
        "security": [
          {
            "OAuth2": [
              "accounting.journals:write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://secure.clearbooks.co.uk/account/action/oauth/",
            "tokenUrl": "https://api.clearbooks.co.uk/oauth/token",
            "scopes": {
              "businesses:read": "Read business data",
              "businesses:write": "Update business data",
              "accounting.account_codes:read": "Read account codes",
              "accounting.account_codes:write": "Create, update and delete account codes",
              "accounting.bank_accounts:read": "Read bank accounts",
              "accounting.bank_accounts:write": "Create, update and delete bank accounts",
              "accounting.customers:read": "Read customers",
              "accounting.customers:write": "Create, update and delete customers",
              "accounting.suppliers:read": "Read suppliers",
              "accounting.suppliers:write": "Create, update and delete suppliers",
              "accounting.sales:read": "Read sales documents",
              "accounting.sales:write": "Create, update and delete sales documents",
              "accounting.purchases:read": "Read purchase documents",
              "accounting.purchases:write": "Create, update and delete purchase documents",
              "accounting.payments:read": "Read payments",
              "accounting.payments:write": "Create, update and delete payments",
              "accounting.allocations:read": "Read allocations",
              "accounting.allocations:write": "Create, update and delete allocations",
              "accounting.stock_items:read": "Read stock items",
              "accounting.stock_items:write": "Create, update and delete stock items",
              "accounting.vat:read": "Read VAT information",
              "accounting.bank_feeds:write": "Create bank feeds",
              "accounting.bank_statements:write": "Create bank statements",
              "accounting.transactions:read": "Read transactions",
              "accounting.journals:write": "Create journals"
            }
          }
        }
      }
    }
  }
}