{
  "openapi": "3.0.0",
  "info": {
    "title": "Zoho Invoice API",
    "version": "v3"
  },
  "servers": [
    {
      "url": "https://www.zohoapis.com/invoice/v3"
    }
  ],
  "paths": {
    "/contacts/contactpersons": {
      "post": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "create_contact_person",
        "summary": "Create a contact person",
        "description": "Create a contact person for contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/contactpersons/{contact_person_id}": {
      "put": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "update_contact_person",
        "summary": "Update a contact person",
        "description": "Update details of an existing contact person.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "delete_contact_person",
        "summary": "Delete a contact person",
        "description": "Delete an existing contact person.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.DELETE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/contactpersons": {
      "get": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "list_contact_persons",
        "summary": "List contact persons",
        "description": "List all contacts with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/contactpersons/{contact_person_id}": {
      "get": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "get_contact_person",
        "summary": "Get a contact person",
        "description": "Get the details of a contact person.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/contacts/contactpersons/{contact_person_id}/primary": {
      "post": {
        "tags": [
          "contact-persons"
        ],
        "operationId": "mark_contact_person_as_primary",
        "summary": "Mark as primary contact person",
        "description": "Mark a contact person as primary for contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "create_contact",
        "summary": "Create a Contact",
        "description": "Create a contact with given information.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "list_contacts",
        "summary": "List Contacts",
        "description": "List all contacts with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}": {
      "put": {
        "tags": [
          "contacts"
        ],
        "operationId": "update_contact",
        "summary": "Update a Contact",
        "description": "Update an existing contact. To delete a contact person remove it from the contact_persons list.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "get_contact",
        "summary": "Get a Contact",
        "description": "Get details of a Contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "contacts"
        ],
        "operationId": "delete_contact",
        "summary": "Delete a Contact",
        "description": "Delete an existing Contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.DELETE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/active": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "mark_as_contact_active",
        "summary": "Mark as Active",
        "description": "Mark a contact as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/inactive": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "mark_as_contact_inactive",
        "summary": "Mark as Inactive",
        "description": "Mark a contact as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/portal/enable": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "enable_portal_access",
        "summary": "Enable Portal Access",
        "description": "Enable Portal Access for a Contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/clientreviews": {
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "list_client_reviews",
        "summary": "View All Client Reviews",
        "description": "View the list of all client reviews for a particular contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/clientreviews/{comment_id}": {
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "get_client_review",
        "summary": "Details of a Particular Client Review",
        "description": "View the details of a particular client review.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/clientreviews/{comment_id}/comment": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "create_client_review_comment",
        "summary": "Reply a Client Review",
        "description": "Send a reply to a client's review.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/paymentreminder/enable": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "enable_payment_reminders",
        "summary": "Enable Payment Reminders",
        "description": "Enable automated payment reminders for a contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/paymentreminder/disable": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "disable_payment_reminders",
        "summary": "Disable Payment Reminders",
        "description": "Disable automated payment reminders for a contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/statements/email": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "email_statement",
        "summary": "Email Statement",
        "description": "Email statement to the contact. If JSONString is not inputted, mail will be sent with the default mail content.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "get_statement_mail_content",
        "summary": "Get Statement Mail Content",
        "description": "Get the mail content of a contacts billing statement.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/email": {
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "email_contact",
        "summary": "Email Contact",
        "description": "Send email to contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/comments": {
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "list_contact_comments",
        "summary": "List Comments",
        "description": "List recent activities of a contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/address": {
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "get_contact_addresses",
        "summary": "Get Contact Addresses",
        "description": "Get addresses of a contact including its Shipping Address, Billing Address and other additional addresses.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "contacts"
        ],
        "operationId": "create_additional_address",
        "summary": "Add Additional Address",
        "description": "Add an additional address for a contact using the arguments below.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/address/{address_id}": {
      "put": {
        "tags": [
          "contacts"
        ],
        "operationId": "update_additional_address",
        "summary": "Edit Additional Address",
        "description": "Edit the additional address of a contact using the arguments below.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "contacts"
        ],
        "operationId": "delete_additional_address",
        "summary": "Delete Additional Address",
        "description": "Delete the additional address of a contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.DELETE"
            ]
          }
        ]
      }
    },
    "/contacts/{contact_id}/refunds": {
      "get": {
        "tags": [
          "contacts"
        ],
        "operationId": "list_contact_refunds",
        "summary": "List Refunds",
        "description": "List the refund history of a contact.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.READ"
            ]
          }
        ]
      }
    },
    "/creditnotes": {
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "create_credit_note",
        "summary": "Create a credit note",
        "description": "Details of an existing creditnote.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_credit_notes",
        "summary": "List Credit Notes",
        "description": "List all the Credit Notes.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}": {
      "put": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "update_credit_note",
        "summary": "Update a credit note",
        "description": "Update Details of an existing creditnote.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "get_credit_note",
        "summary": "Get a credit note",
        "description": "Details of an existing creditnote.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "delete_credit_note",
        "summary": "Delete a credit note",
        "description": "Delete an existing credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.DELETE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/email": {
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "email_credit_note",
        "summary": "Email a credit note",
        "description": "Email a credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/void": {
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "mark_credit_note_as_void",
        "summary": "Void a credit note",
        "description": "To mark a credit note as invalid/nullify it content.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/converttoopen": {
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "mark_credit_note_as_open",
        "summary": "Open a voided credit note",
        "description": "Convert a voided credit note to open.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/emailhistory": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "get_credit_note_email_history",
        "summary": "Email history",
        "description": "Get email history of a credit code.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/address/billing": {
      "put": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "update_credit_note_billing_address",
        "summary": "Update billing address",
        "description": "Updates the billing address for an existing credit note alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.UPDATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/address/shipping": {
      "put": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "update_credit_note_shipping_address",
        "summary": "Update Shipping address",
        "description": "Updates the shipping address for an existing credit note alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.UPDATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/templates": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_credit_note_templates",
        "summary": "List credit note templates",
        "description": "Get all credit note pdf templates.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/templates/{template_id}": {
      "put": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "update_credit_note_template",
        "summary": "Update a credit note template",
        "description": "Update the pdf template associated with the credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.UPDATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/invoices": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_invoices_credited",
        "summary": "List invoices credited",
        "description": "List invoices to which the credit note is applied.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "apply_credit_to_invoice",
        "summary": "Credit to an invoice",
        "description": "Apply credit note to existing invoices.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/invoices/{creditnote_invoice_id}": {
      "delete": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "delete_credit_notes_applied_to_invoice",
        "summary": "Delete invoices credited",
        "description": "Delete the credits applied to an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.DELETE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/comments": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_credit_note_comments",
        "summary": "List credit note comments & history",
        "description": "Get history and comments of a credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "create_credit_note_comment",
        "summary": "Add a comment",
        "description": "Add a comment to an existing credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "delete_credit_note_comment",
        "summary": "Delete a Comment",
        "description": "Delete a credit note comment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.DELETE"
            ]
          }
        ]
      }
    },
    "/creditnotes/refunds": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_credit_note_refunds",
        "summary": "List credit note refunds",
        "description": "List all refunds with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/refunds": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "list_credit_note_refunds_of_a_credit_note",
        "summary": "List refunds of a credit note",
        "description": "List all refunds of an existing credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "refund_credit_note",
        "summary": "Refund credit note",
        "description": "Refund credit note amount.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.CREATE"
            ]
          }
        ]
      }
    },
    "/creditnotes/{creditnote_id}/refunds/{creditnote_refund_id}": {
      "get": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "get_credit_note_refund",
        "summary": "Get credit note refund",
        "description": "Get refund of a particular credit note.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "update_credit_note_refund",
        "summary": "Update credit note refund",
        "description": "Update the refunded transaction.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "credit-notes"
        ],
        "operationId": "delete_credit_note_refund",
        "summary": "Delete credit note refund",
        "description": "Delete a credit note refund.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.creditnotes.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/currencies": {
      "post": {
        "tags": [
          "currency"
        ],
        "operationId": "create_currency",
        "summary": "Create a Currency",
        "description": "Create a currency for transaction.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "currency"
        ],
        "operationId": "list_currencies",
        "summary": "List Currencies",
        "description": "Get list of currencies configured.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/settings/currencies/{currency_id}": {
      "put": {
        "tags": [
          "currency"
        ],
        "operationId": "update_currency",
        "summary": "Update a Currency",
        "description": "Update the details of a currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "currency"
        ],
        "operationId": "get_currency",
        "summary": "Get a Currency",
        "description": "Get the details of a currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "currency"
        ],
        "operationId": "delete_currency",
        "summary": "Delete a currency",
        "description": "Delete a currency. Currency that is associated to any transaction cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/currencies/{currency_id}/exchangerates": {
      "get": {
        "tags": [
          "currency"
        ],
        "operationId": "list_exchange_rates",
        "summary": "List exchange rates",
        "description": "List of exchange rates configured for the currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "currency"
        ],
        "operationId": "create_exchange_rate",
        "summary": "Create an exchange rate",
        "description": "Create an exchange rate for the specified currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/settings/currencies/{currency_id}/exchangerates/{exchange_rate_id}": {
      "get": {
        "tags": [
          "currency"
        ],
        "operationId": "get_exchange_rate",
        "summary": "Get an exchange rate.",
        "description": "Get the details of an exchange rate that has been asscoiated to the currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "currency"
        ],
        "operationId": "update_exchange_rate",
        "summary": "Update an exchange rate",
        "description": "Update the details of exchange rate for a currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "currency"
        ],
        "operationId": "delete_exchange_rate",
        "summary": "Delete an exchage rate",
        "description": "Delete an exchange rate for the specified currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/customerpayments": {
      "post": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "create_customer_payment",
        "summary": "Create a payment",
        "description": "Create a new payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "list_customer_payments",
        "summary": "List Customer Payments",
        "description": "List all the payments made by your customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.READ"
            ]
          }
        ]
      }
    },
    "/customerpayment/{customer_payment_id}/customfields": {
      "put": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "update_custom_field_in_customer_payment",
        "summary": "Update custom field in existing customerpayments",
        "description": "Update the value of the custom field in existing customerpayments.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.UPDATE"
            ]
          }
        ]
      }
    },
    "/customerpayments/{payment_id}": {
      "put": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "update_customer_payment",
        "summary": "Update a payment",
        "description": "Update an existing payment information.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "get_customer_payment",
        "summary": "Retrieve a payment",
        "description": "Details of an existing payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "delete_customer_payment",
        "summary": "Delete a payment",
        "description": "Delete an existing payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.DELETE"
            ]
          }
        ]
      }
    },
    "/customerpayments/{customer_payment_id}/refunds": {
      "get": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "list_customer_payment_refunds",
        "summary": "List refunds of a customer payment",
        "description": "List all the refunds pertaining to an existing customer payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "refund_customer_payment",
        "summary": "Refund an excess customer payment",
        "description": "Refund the excess amount paid by the customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.CREATE"
            ]
          }
        ]
      }
    },
    "/customerpayments/{customer_payment_id}/refunds/{refund_id}": {
      "get": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "get_customer_payment_refund",
        "summary": "Details of a refund",
        "description": "Obtain details of a particular refund of a customer payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "update_customer_payment_refund",
        "summary": "Update a refund",
        "description": "Update the refunded transaction.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "customer-payments"
        ],
        "operationId": "delete_customer_payment_refund",
        "summary": "Delete a Refund",
        "description": "Delete refund pertaining to an existing customer payment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.customerpayments.DELETE"
            ]
          }
        ]
      }
    },
    "/estimates": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "create_estimate",
        "summary": "Create an Estimate",
        "description": "Create an estimate for your customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "list_estimates",
        "summary": "List estimates",
        "description": "List all estimates with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_estimate",
        "summary": "Update an Estimate",
        "description": "Update an existing estimate. To delete a line item just remove it from the line_items list.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "get_estimate",
        "summary": "Get an estimate",
        "description": "Get the details of an estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "estimates"
        ],
        "operationId": "delete_estimate",
        "summary": "Delete an Estimate",
        "description": "Delete an existing estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.DELETE"
            ]
          }
        ]
      }
    },
    "/estimate/{estimate_id}/customfields": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_custom_field_in_estimate",
        "summary": "Update custom field in existing estimates",
        "description": "Update the value of the custom field in existing estimates.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/status/sent": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "mark_estimate_as_sent",
        "summary": "Mark an estimate as sent",
        "description": "Mark a draft estimate as sent.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/status/accepted": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "mark_estimate_as_accepted",
        "summary": "Mark an estimate as accepted",
        "description": "Mark a sent estimate as accepted if the customer has accepted it.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/status/declined": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "mark_estimate_as_declined",
        "summary": "Mark an estimate as declined",
        "description": "Mark a sent estimate as declined if the customer has rejected it.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/email": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "email_estimate",
        "summary": "Email an estimate",
        "description": "Email an estimate to the customer. Input json string is not mandatory. If input json string is empty, mail will be send with default mail content.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "get_estimate_email_content",
        "summary": "Get estimate email content",
        "description": "Get the email content of an estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      }
    },
    "/estimates/email": {
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "email_multiple_estimates",
        "summary": "Email multiple estimates",
        "description": "Send estimates to your customers by email. Maximum of 10 estimates can be sent at once.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      }
    },
    "/estimates/pdf": {
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "bulk_export_estimates",
        "summary": "Bulk export estimates",
        "description": "Maximum of 25 estimates can be exported in a single pdf.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      }
    },
    "/estimates/print": {
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "bulk_print_estimates",
        "summary": "Bulk print estimates",
        "description": "Export estimates as pdf and print them. Maximum of 25 estimates can be printed.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/address/billing": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_billing_address",
        "summary": "Update billing address",
        "description": "Updates the billing address for this estimate alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/address/shipping": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_estimate_shipping_address",
        "summary": "Update shipping address",
        "description": "Updates the shipping address for an existing estimate alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      }
    },
    "/estimates/templates": {
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "list_estimate_templates",
        "summary": "List estimate templates",
        "description": "Get all estimate pdf templates.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/templates/{template_id}": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_estimate_template",
        "summary": "Update estimate template",
        "description": "Update the pdf template associated with the estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/comments": {
      "get": {
        "tags": [
          "estimates"
        ],
        "operationId": "list_estimate_comments",
        "summary": "List estimate comments & history",
        "description": "Get the complete history and comments of an estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "estimates"
        ],
        "operationId": "create_estimate_comment",
        "summary": "Add Comments",
        "description": "Add a comment for an estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.CREATE"
            ]
          }
        ]
      }
    },
    "/estimates/{estimate_id}/comments/{comment_id}": {
      "put": {
        "tags": [
          "estimates"
        ],
        "operationId": "update_estimate_comment",
        "summary": "Update comment",
        "description": "Update an existing comment of an estimate.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "estimates"
        ],
        "operationId": "delete_estimate_comment",
        "summary": "Delete a comment",
        "description": "Delete an estimate comment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.estimates.DELETE"
            ]
          }
        ]
      }
    },
    "/expensecategories": {
      "post": {
        "tags": [
          "expense-category"
        ],
        "operationId": "create_expense_category",
        "summary": "Create an expense category",
        "description": "Create an expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expense-category"
        ],
        "operationId": "list_expense_categories",
        "summary": "List expense categories",
        "description": "List expense categories along with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/expensecategories/{category_id}": {
      "put": {
        "tags": [
          "expense-category"
        ],
        "operationId": "update_expense_category",
        "summary": "Update an expense category",
        "description": "Update an expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expense-category"
        ],
        "operationId": "get_expense_category",
        "summary": "Get an expense category",
        "description": "Get the details of an expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "expense-category"
        ],
        "operationId": "delete_expense_category",
        "summary": "Delete an expense category",
        "description": "Delete an existing expense category. Category which is associated with expense cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/expensecategories/{categoryid}/active": {
      "post": {
        "tags": [
          "expense-category"
        ],
        "operationId": "mark_expense_category_as_active",
        "summary": "Mark an expense category as active",
        "description": "Update an expense category status as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/expensecategories/{categoryid}/inactive": {
      "post": {
        "tags": [
          "expense-category"
        ],
        "operationId": "mark_expense_category_as_inactive",
        "summary": "Mark an expense category as inactive",
        "description": "Update an expense category status as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/expenses": {
      "post": {
        "tags": [
          "expenses"
        ],
        "operationId": "create_expense",
        "summary": "Create an Expense",
        "description": "Create billable or non-billable expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expenses"
        ],
        "operationId": "list_expenses",
        "summary": "List Expenses",
        "description": "List all the Expenses with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      }
    },
    "/expenses/{expense_id}": {
      "put": {
        "tags": [
          "expenses"
        ],
        "operationId": "update_expense",
        "summary": "Update an Expense",
        "description": "Update an existing Expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expenses"
        ],
        "operationId": "get_expense",
        "summary": "Get an Expense",
        "description": "Get the details of the Expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "expenses"
        ],
        "operationId": "delete_expense",
        "summary": "Delete an Expense",
        "description": "Delete an existing expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.DELETE"
            ]
          }
        ]
      }
    },
    "/expenses/{expense_id}/comments": {
      "get": {
        "tags": [
          "expenses"
        ],
        "operationId": "list_expense_comments",
        "summary": "List expense History & Comments",
        "description": "Get history and comments of an expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      }
    },
    "/employees": {
      "get": {
        "tags": [
          "expenses"
        ],
        "operationId": "list_employees",
        "summary": "List employees",
        "description": "List employees with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "expenses"
        ],
        "operationId": "create_employee",
        "summary": "Create an employee",
        "description": "Create an employee for an expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.CREATE"
            ]
          }
        ]
      }
    },
    "/employee/{employee_id}": {
      "delete": {
        "tags": [
          "expenses"
        ],
        "operationId": "delete_employee",
        "summary": "Delete an employee",
        "description": "Delete an existing employee.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.DELETE"
            ]
          }
        ]
      }
    },
    "/crm/account/{crm_account_id}/import": {
      "post": {
        "tags": [
          "integration"
        ],
        "operationId": "import_customer_using_crm_account_id",
        "summary": "Import a customer using the CRM account ID",
        "description": "Zoho Invoice must be integrated with Zoho CRM using Accounts and Contacts sync or using Accounts only sync to import a customer from CRM with its CRM account ID. <br> Note: You can get a contact by CRM account ID by using this <a href=/invoice/api/v3/contacts/#list-contacts/zcrm_account_id>API Endpoint</a>",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/crm/contact/{crm_contact_id}/import": {
      "post": {
        "tags": [
          "integration"
        ],
        "operationId": "import_customer_using_crm_contact_id",
        "summary": "Import a customer using CRM contact ID",
        "description": "Zoho Invoice must be integrated with Zoho CRM using Contacts only sync to import a customer from CRM with its CRM contact ID. <br> Note: You can get a contact by CRM contact ID by using this <a href=/invoice/api/v3/contacts/#list-contacts/zcrm_contact_id>API Endpoint</a>",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.contacts.CREATE"
            ]
          }
        ]
      }
    },
    "/crm/item/{crm_product_id}/import": {
      "post": {
        "tags": [
          "integration"
        ],
        "operationId": "import_item_using_crm_product_id",
        "summary": "Import an item using the CRM product ID",
        "description": "Zoho Invoice must be integrated with Zoho CRM using Products only sync to import an item from CRM with its CRM product ID.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "create_invoice",
        "summary": "Create an invoice",
        "description": "Create an invoice for your customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "list_invoices",
        "summary": "List invoices",
        "description": "List all invoices with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice",
        "summary": "Update an invoice",
        "description": "Update an existing invoice. To delete a line item just remove it from the line_items list.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "get_invoice",
        "summary": "Get an invoice",
        "description": "Get the details of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_invoice",
        "summary": "Delete an invoice",
        "description": "Delete an existing invoice. Invoices which have payment or credits note applied cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/invoice/{invoice_id}/customfields": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_custom_fields_invoice",
        "summary": "Update custom field in existing invoices",
        "description": "Update the value of the custom field in existing invoices.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/status/sent": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "mark_invoice_as_sent",
        "summary": "Mark an invoice as sent",
        "description": "Mark a draft invoice as sent.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/status/void": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "mark_invoice_as_void",
        "summary": "Void an invoice",
        "description": "Mark an invoice status as void. Upon voiding, the payments and credits associated with the invoices will be unassociated and will be under customer credits.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/status/draft": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "mark_invoice_as_draft",
        "summary": "Mark as draft",
        "description": "Mark a voided invoice as draft.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/email": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "email_invoice",
        "summary": "Email an invoice",
        "description": "Email an invoice to the customer. Input json string is not mandatory. If input json string is empty, mail will be send with default mail content.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "get_invoice_email_content",
        "summary": "Get invoice email content",
        "description": "Get the email content of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/email": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "email_invoices",
        "summary": "Email invoices",
        "description": "Send invoices to your customers by email. Maximum of 10 invoices can be sent at once.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/paymentreminder": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "invoice_payment_reminder",
        "summary": "Remind Customer",
        "description": "Remind your customer about an unpaid invoice by email. Reminder will be sent, only for the invoices which are in open or overdue status.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "get_payment_reminder_mail_content",
        "summary": "Get payment reminder mail content",
        "description": "Get the mail content of the payment reminder.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/paymentreminder": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "bulk_invoice_reminder",
        "summary": "Bulk invoice reminder",
        "description": "Remind your customer about an unpaid invoices by email. Reminder mail will be send, only for the invoices is in open or overdue status. Maximum 10 invoices can be reminded at once.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/pdf": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "bulk_export_invoices",
        "summary": "Bulk export Invoices",
        "description": "Maximum of 25 invoices can be exported in a single pdf.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/print": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "bulk_print_invoices",
        "summary": "Bulk print invoices",
        "description": "Export invoices as pdf and print them. Maximum of 25 invoices can be printed.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/paymentreminder/disable": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "disable_invoice_payment_reminder",
        "summary": "Disable payment reminder",
        "description": "Disable automated payment reminders for an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/paymentreminder/enable": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "enable_invoice_payment_reminder",
        "summary": "Enable payment reminder",
        "description": "Enable automated payment reminders for an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/writeoff": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "write_off_invoice",
        "summary": "Write off invoice",
        "description": "Write off the invoice balance amount of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/writeoff/cancel": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "cancel_write_off_invoice",
        "summary": "Cancel write off",
        "description": "Cancel the write off amount of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/address/billing": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice_billing_address",
        "summary": "Update billing address",
        "description": "Updates the billing address for this invoice alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/address/shipping": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice_shipping_address",
        "summary": "Update shipping address",
        "description": "Updates the shipping address for this invoice alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/invoices/templates": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "list_invoice_templates",
        "summary": "List invoice templates",
        "description": "Get all invoice pdf templates.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/templates/{template_id}": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice_template",
        "summary": "Update invoice template",
        "description": "Update the pdf template associated with the invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/payments": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "list_invoice_payments",
        "summary": "List invoice payments",
        "description": "Get the list of payments made for an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/creditsapplied": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "list_invoice_credits_applied",
        "summary": "List credits applied",
        "description": "Get the list of credits applied for an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/credits": {
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "apply_credits_to_invoice",
        "summary": "Apply credits",
        "description": "Apply the customer credits either from credit notes or excess customer payments to an invoice. Multiple credits can be applied at once.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/payments/{invoice_payment_id}": {
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_invoice_payment",
        "summary": "Delete a payment",
        "description": "Delete a payment made to an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/creditsapplied/{creditnotes_invoice_id}": {
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_applied_credit_to_invoice",
        "summary": "Delete  applied credit",
        "description": "Delete a particular credit applied to an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/attachment": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "get_invoice_attachment",
        "summary": "Get an invoice attachment",
        "description": "Returns the file attached to the invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "add_attachment_to_invoice",
        "summary": "Add attachment to an invoice",
        "description": "Attach a file to an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice_attachment",
        "summary": "Update attachment preference",
        "description": "Set whether you want to send the attached file while emailing the invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_invoice_attachment",
        "summary": "Delete an attachment",
        "description": "Delete the file attached to the invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/invoices/expenses/{expense_id}/receipt": {
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_invoice_expense_receipt",
        "summary": "Delete the expense receipt",
        "description": "Delete the expense receipts attached to an invoice which is raised from an expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/comments": {
      "get": {
        "tags": [
          "invoices"
        ],
        "operationId": "list_invoice_comments",
        "summary": "List invoice comments & history",
        "description": "Get the complete history and comments of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "invoices"
        ],
        "operationId": "add_invoice_comment",
        "summary": "Add comment",
        "description": "Add a comment for an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/invoices/{invoice_id}/comments/{comment_id}": {
      "put": {
        "tags": [
          "invoices"
        ],
        "operationId": "update_invoice_comment",
        "summary": "Update comment",
        "description": "Update an existing comment of an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "invoices"
        ],
        "operationId": "delete_invoice_comment",
        "summary": "Delete a comment",
        "description": "Delete an invoice comment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/items": {
      "post": {
        "tags": [
          "items"
        ],
        "operationId": "create_item",
        "summary": "Create an Item",
        "description": "Create a new item.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "items"
        ],
        "operationId": "list_items",
        "summary": "List items",
        "description": "Get the list of all active items with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/itemdetails": {
      "get": {
        "tags": [
          "items"
        ],
        "operationId": "list_item_details",
        "summary": "Bulk fetch item details",
        "description": "Fetch item details for the mentioned item IDs",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.items.READ"
            ]
          }
        ]
      }
    },
    "/items/{item_id}": {
      "put": {
        "tags": [
          "items"
        ],
        "operationId": "update_item",
        "summary": "Update an item",
        "description": "Update the details of an existing item.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "items"
        ],
        "operationId": "get_item",
        "summary": "Retrieve an item",
        "description": "Fetch details of an existing item.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "items"
        ],
        "operationId": "delete_item",
        "summary": "Delete an item",
        "description": "Delete an existing item. Items that are part of a transaction cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/item/{item_id}/customfields": {
      "put": {
        "tags": [
          "items"
        ],
        "operationId": "update_custom_field_in_items",
        "summary": "Update custom field in existing items",
        "description": "Update the value of the custom field in existing items.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/items/{item_id}/active": {
      "post": {
        "tags": [
          "items"
        ],
        "operationId": "mark_item_as_active",
        "summary": "Mark as active",
        "description": "Mark an inactive item as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/items/{item_id}/inactive": {
      "post": {
        "tags": [
          "items"
        ],
        "operationId": "mark_item_as_inactive",
        "summary": "Mark as inactive",
        "description": "Mark an active item as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/organizations": {
      "post": {
        "tags": [
          "organizations"
        ],
        "operationId": "create_organization",
        "summary": "Create an organization",
        "description": "Create an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "organizations"
        ],
        "operationId": "list_organizations",
        "summary": "List organizations",
        "description": "Get the list of organizations.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/organizations/{organization_id}": {
      "put": {
        "tags": [
          "organizations"
        ],
        "operationId": "update_organization",
        "summary": "Update an organization",
        "description": "Update the details of an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "organizations"
        ],
        "operationId": "get_organization",
        "summary": "Get an organization",
        "description": "Get the details of an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/pricebooks": {
      "post": {
        "tags": [
          "price-lists"
        ],
        "operationId": "create_price_list",
        "summary": "Create a Price List",
        "description": "Create a new Price List.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "price-lists"
        ],
        "operationId": "list_price_lists",
        "summary": "List of all the Price Lists",
        "description": "Get the list of all the Price Lists with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/pricebooks/{pricebook_id}": {
      "put": {
        "tags": [
          "price-lists"
        ],
        "operationId": "update_price_list",
        "summary": "Update a Price List",
        "description": "Update an existing Price List.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "price-lists"
        ],
        "operationId": "get_price_list",
        "summary": "Retrieve a Price list",
        "description": "Fetch the details of an existing Price List.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "price-lists"
        ],
        "operationId": "delete_price_list",
        "summary": "Delete a Price List",
        "description": "Delete a Price List.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/projects": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "create_project",
        "summary": "Create a project",
        "description": "Create a new project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "list_projects",
        "summary": "List projects",
        "description": "List all projects with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}": {
      "put": {
        "tags": [
          "projects"
        ],
        "operationId": "update_project",
        "summary": "Update a project",
        "description": "Update details of a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "get_project",
        "summary": "Get a project",
        "description": "Get the details of a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "projects"
        ],
        "operationId": "delete_project",
        "summary": "Delete project",
        "description": "Deleting a existing project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/active": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "activate_project",
        "summary": "Activate a project",
        "description": "Mark project as active",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/inactive": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "inactivate_project",
        "summary": "Deactivate a project",
        "description": "Marking a project as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/clone": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "clone_project",
        "summary": "Clone a project",
        "description": "Cloning the settings of an existing project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/users": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "assign_project_users",
        "summary": "Assign users",
        "description": "Assign a users to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "list_project_users",
        "summary": "List Users",
        "description": "Get list of all users associated to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/users/invite": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "invite_project_user",
        "summary": "Invite user",
        "description": "Invite a user to the project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/users/{user_id}": {
      "put": {
        "tags": [
          "projects"
        ],
        "operationId": "update_project_user",
        "summary": "Update user",
        "description": "Update details of a user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "get_project_user",
        "summary": "Get a User",
        "description": "Get details of a user in project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "projects"
        ],
        "operationId": "delete_project_user",
        "summary": "Delete user",
        "description": "Remove user from a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/comments": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "create_project_comment",
        "summary": "Post comment",
        "description": "Post comment to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "list_project_comments",
        "summary": "List comments",
        "description": "Get comments for a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "projects"
        ],
        "operationId": "delete_project_comment",
        "summary": "Delete comment",
        "description": "Deleting a comment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/invoices": {
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "list_project_invoices",
        "summary": "List invoices",
        "description": "Lists invoices created for this project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/tasks": {
      "post": {
        "tags": [
          "tasks"
        ],
        "operationId": "create_project_task",
        "summary": "Add a project task",
        "description": "Adding a new task to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "tasks"
        ],
        "operationId": "list_project_tasks",
        "summary": "List project tasks",
        "description": "Get list of all the tasks added to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/tasks/{task_id}": {
      "put": {
        "tags": [
          "tasks"
        ],
        "operationId": "update_project_task",
        "summary": "Update a project task",
        "description": "Update the details of an existing project task.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "tasks"
        ],
        "operationId": "get_project_task",
        "summary": "Get a project task",
        "description": "Get the details of a project task.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "tasks"
        ],
        "operationId": "delete_project_task",
        "summary": "Delete a project Task",
        "description": "Delete a task added to a project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/recurringexpenses": {
      "post": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "create_recurring_expense",
        "summary": "Create a recurring expense",
        "description": "Create a new recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "list_recurring_expenses",
        "summary": "List recurring expenses",
        "description": "List all the Expenses with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      }
    },
    "/recurringexpenses/{recurring_expense_id}": {
      "post": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "update_recurring_expense",
        "summary": "Update a recurring expense",
        "description": "Update an existing recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "get_recurring_expense",
        "summary": "Get a recurring expense",
        "description": "Get the details of the recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "delete_recurring_expense",
        "summary": "Delete a recurring expense",
        "description": "Deleting an existing recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.DELETE"
            ]
          }
        ]
      }
    },
    "/recurringexpenses/{recurring_expense_id}/status/stop": {
      "post": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "stop_recurring_expense",
        "summary": "Stop a recurring expense",
        "description": "Stop an active recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.CREATE"
            ]
          }
        ]
      }
    },
    "/recurringexpenses/{recurring_expense_id}/status/resume": {
      "post": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "resume_recurring_expense",
        "summary": "Resume a recurring Expense",
        "description": "Resume a stopped recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.CREATE"
            ]
          }
        ]
      }
    },
    "/recurringexpenses/{recurring_expense_id}/expenses": {
      "get": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "list_child_expenses_created",
        "summary": "List child expenses created",
        "description": "List child expenses created from recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      }
    },
    "/recurringexpenses/{recurring_expense_id}/comments": {
      "get": {
        "tags": [
          "recurring-expenses"
        ],
        "operationId": "list_recurring_expense_comments",
        "summary": "List recurring expense history",
        "description": "Get history and comments of a recurring expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.expenses.READ"
            ]
          }
        ]
      }
    },
    "/recurringinvoices": {
      "post": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "create_recurring_invoice",
        "summary": "Create a Recurring Invoice",
        "description": "Creating a new recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "list_recurring_invoices",
        "summary": "List Recurring Invoice",
        "description": "List the details of all recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/recurringinvoices/{recurring_invoice_id}": {
      "put": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "update_recurring_invoice",
        "summary": "Update Recurring Invoice",
        "description": "Update the recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "get_recurring_invoice",
        "summary": "Get a Recurring Invoice",
        "description": "Get the details of a recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "delete_recurring_invoice",
        "summary": "Delete a Recurring Invoice",
        "description": "Delete an existing recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/recurringinvoices/{recurring_invoice_id}/status/stop": {
      "post": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "stop_recurring_invoice",
        "summary": "Stop a Recurring Invoice",
        "description": "Stop an active recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/recurringinvoices/{recurring_invoice_id}/status/resume": {
      "post": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "resume_recurring_invoice",
        "summary": "Resume a Recurring Invoice",
        "description": "Resume a stopped recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/recurringinvoices/{recurring_invoice_id}/templates/{template_id}": {
      "put": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "update_recurring_invoice_template",
        "summary": "Update Recurring Invoice template",
        "description": "Update the pdf template associated with the recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/recurringinvoices/{recurring_invoice_id}/comments": {
      "get": {
        "tags": [
          "recurring-invoices"
        ],
        "operationId": "list_recurring_invoice_comments",
        "summary": "List Recurring Invoice History",
        "description": "Get the complete history and comments of a recurring invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/retainerinvoices": {
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "create_retainer_invoice",
        "summary": "Create a retainer invoice",
        "description": "Create a retainer invoice for your customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "list_retainer_invoices",
        "summary": "List Retainer invoices",
        "description": "List all retainer invoices with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}": {
      "put": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "update_retainer_invoice",
        "summary": "Update a retainer invoice",
        "description": "Update an existing invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "get_retainer_invoice",
        "summary": "Get a retainer invoice",
        "description": "Get the details of a retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "delete_retainer_invoice",
        "summary": "Delete a retainer invoice",
        "description": "Delete an existing retainer invoice. Invoices which have payment or credits note applied cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/status/sent": {
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "mark_retainer_invoice_as_sent",
        "summary": "Mark a retainer invoice as sent",
        "description": "Mark a draft retainer invoice as sent.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/templates/{template_id}": {
      "put": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "update_retainer_invoice_template",
        "summary": "Update retainer invoice template",
        "description": "Update the pdf template associated with the retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/status/void": {
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "mark_retainer_invoice_as_void",
        "summary": "Void a retainer invoice",
        "description": "Mark an invoice status as void. Upon voiding, the payments and credits associated with the retainer invoices will be unassociated and will be under customer credits.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{reatinerinvoice_id}/status/draft": {
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "mark_retainer_invoice_as_draft",
        "summary": "Mark as draft",
        "description": "Mark a voided retainer invoice as draft.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/email": {
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "email_retainer_invoice",
        "summary": "Email a retainer invoice",
        "description": "Email a retainer invoice to the customer. Input json string is not mandatory. If input json string is empty, mail will be send with default mail content.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "get_retainer_invoice_email_content",
        "summary": "Get retainer invoice email content",
        "description": "Get the email content of a retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/address/billing": {
      "put": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "update_retainer_invoice_billing_address",
        "summary": "Update billing address",
        "description": "Updates the billing address for this retainer invoice alone.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/templates": {
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "list_retainer_invoice_templates",
        "summary": "List retainer invoice templates",
        "description": "Get all retainer invoice pdf templates.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/attachment": {
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "get_retainer_invoice_attachment",
        "summary": "Get a retainer invoice attachment",
        "description": "Returns the file attached to the retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "add_retainer_invoice_attachment",
        "summary": "Add attachment to a retainer invoice",
        "description": "Attach a file to an invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/documents/{document_id}": {
      "delete": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "delete_retainer_invoice_attachment",
        "summary": "Delete an attachment",
        "description": "Delete the file attached to the retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/comments": {
      "get": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "list_retainer_invoice_comments",
        "summary": "List retainer invoice comments & history",
        "description": "Get the complete history and comments of a retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "add_retainer_invoice_comment",
        "summary": "Add comment",
        "description": "Add a comment for a retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.CREATE"
            ]
          }
        ]
      }
    },
    "/retainerinvoices/{retainerinvoice_id}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "delete_retainer_invoice_comment",
        "summary": "Delete a comment",
        "description": "Delete a retainer invoice comment.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.DELETE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "retainer-invoices"
        ],
        "operationId": "update_retainer_invoice_comment",
        "summary": "Update comment",
        "description": "Update an existing comment of a retainer invoice.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.invoices.UPDATE"
            ]
          }
        ]
      }
    },
    "/settings/taxes": {
      "post": {
        "tags": [
          "taxes"
        ],
        "operationId": "create_tax",
        "summary": "Create a tax",
        "description": "Create a tax which can be associated with an item.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "list_taxes",
        "summary": "List taxes",
        "description": "List of simple and compound taxes with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/settings/taxes/{tax_id}": {
      "put": {
        "tags": [
          "taxes"
        ],
        "operationId": "update_tax",
        "summary": "Update a tax",
        "description": "Update the details of a simple or compound tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "get_tax",
        "summary": "Get a tax",
        "description": "Get the details of a simple or compound tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "taxes"
        ],
        "operationId": "delete_tax",
        "summary": "Delete a tax",
        "description": "Delete a simple or compound tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/taxgroups/{tax_group_id}": {
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "get_tax_group",
        "summary": "Get a tax group",
        "description": "Get the details of a tax group.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "taxes"
        ],
        "operationId": "update_tax_group",
        "summary": "Update a tax group",
        "description": "Update the details of the tax group.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "taxes"
        ],
        "operationId": "delete_tax_group",
        "summary": "Delete a tax group",
        "description": "Delete a tax group. Tax group that is associated to transactions cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/taxgroups": {
      "post": {
        "tags": [
          "taxes"
        ],
        "operationId": "create_tax_group",
        "summary": "Create a tax group",
        "description": "Create a tax group associating multiple taxes.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/settings/taxexemptions": {
      "post": {
        "tags": [
          "taxes"
        ],
        "operationId": "create_tax_exemption",
        "summary": "Create Tax Exemption.",
        "description": "Create a Tax Exemption.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "list_tax_exemptions",
        "summary": "List Tax Exemptions",
        "description": "List all Tax Exemptions.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/settings/taxexemptions/{tax_exemption_id}": {
      "put": {
        "tags": [
          "taxes"
        ],
        "operationId": "update_tax_exemption",
        "summary": "Update Tax Exemption.",
        "description": "Update an existing Tax Exemption.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "taxes"
        ],
        "operationId": "delete_tax_exemption",
        "summary": "Delete Tax Exemption",
        "description": "Delete a Tax Exemption.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/taxauthorities": {
      "post": {
        "tags": [
          "taxes"
        ],
        "operationId": "create_tax_authority",
        "summary": "Create Tax Authority.",
        "description": "Create a Tax Authority.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "list_tax_authorities",
        "summary": "List Tax Authorities",
        "description": "List all Tax Authorities.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/settings/taxauthorities/{tax_authority_id}": {
      "put": {
        "tags": [
          "taxes"
        ],
        "operationId": "update_tax_authority",
        "summary": "Update Tax Authority.",
        "description": "Update an existing Tax Authority.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "taxes"
        ],
        "operationId": "delete_tax_authority",
        "summary": "Delete Tax Authority",
        "description": "Delete a Tax Authority.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/timeentries": {
      "post": {
        "tags": [
          "time-entries"
        ],
        "operationId": "create_time_entry",
        "summary": "Log time entries",
        "description": "Logging time entries.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "time-entries"
        ],
        "operationId": "list_time_entries",
        "summary": "List time entries.",
        "description": "List all time entries with pagination.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "time-entries"
        ],
        "operationId": "delete_time_entries",
        "summary": "Delete time entries",
        "description": "Deleting time entries.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/timeentries/{time_entry_id}": {
      "put": {
        "tags": [
          "time-entries"
        ],
        "operationId": "update_time_entry",
        "summary": "Update time entry",
        "description": "Update logged time entry.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "time-entries"
        ],
        "operationId": "get_time_entry",
        "summary": "Get a time entry",
        "description": "Get details of a time entry.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "time-entries"
        ],
        "operationId": "delete_time_entry",
        "summary": "Delete time entry",
        "description": "Deleting a logged time entry.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/timeentries/{time_entry_id}/timer/start": {
      "post": {
        "tags": [
          "time-entries"
        ],
        "operationId": "start_timer",
        "summary": "Start timer",
        "description": "Start tracking time spent.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/timeentries/timer/stop": {
      "post": {
        "tags": [
          "time-entries"
        ],
        "operationId": "stop_timer",
        "summary": "Stop timer",
        "description": "Stop tracking time, say taking a break or leaving.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/timeentries/runningtimer/me": {
      "get": {
        "tags": [
          "time-entries"
        ],
        "operationId": "get_timer",
        "summary": "Get timer",
        "description": "Get current running timer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.projects.READ"
            ]
          }
        ]
      }
    },
    "/users": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "create_user",
        "summary": "Create a user",
        "description": "Create a user for your organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "list_users",
        "summary": "List Users",
        "description": "Get the list of all users in the organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/users/{user_id}": {
      "put": {
        "tags": [
          "users"
        ],
        "operationId": "update_user",
        "summary": "Update a user",
        "description": "Update the details of a user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "get_user",
        "summary": "Get a user",
        "description": "Get the details of a user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "users"
        ],
        "operationId": "delete_user",
        "summary": "Delete a user",
        "description": "Delete a user associated to the organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/users/me": {
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "get_current_user",
        "summary": "Get current user",
        "description": "Get the details of the current user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.READ"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/invite": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "invite_user",
        "summary": "Invite a user",
        "description": "Send invitation email to a person, you wish to add as a user to your organisation. For example- an accountant.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/active": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "mark_user_as_active",
        "summary": "Mark user as active",
        "description": "Mark an inactive user as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/inactive": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "mark_user_as_inactive",
        "summary": "Mark user as inactive",
        "description": "Mark an active user as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoInvoice.settings.CREATE"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Zoho_Auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "scopes": {
              "ZohoInvoice.settings.CREATE": "Create Settings",
              "ZohoInvoice.settings.UPDATE": "Update Settings",
              "ZohoInvoice.settings.READ": "Read Settings",
              "ZohoInvoice.settings.DELETE": "Delete Settings"
            }
          }
        }
      }
    }
  }
}