{
  "openapi": "3.0.3",
  "info": {
    "title": "AXA Partners Travel API",
    "version": "1.0.0",
    "x-jentic-source-url": "https://move-portal.axa-assistance.com/static/sandbox-packages/travel.openapi.json",
    "description": "AXA Partners Travel API provides programmatic access to sales resources."
  },
  "servers": [
    {
      "url": "https://sandbox.api.axapartners.com",
      "description": "Sandbox server"
    }
  ],
  "paths": {
    "/sales/v2/individual/travel/orders": {
      "post": {
        "summary": "Create and store an order.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.orders.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/orders/{order_id}": {
      "get": {
        "summary": "Retrieve order details.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.orders.read_only"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update the order.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.orders.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/orders/{order_id}/communication_requests": {
      "post": {
        "summary": "Sends a request for a communication with the customer.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.orders.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies": {
      "get": {
        "summary": "Retrieve travel customer policy summaries.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.read_only"
            ]
          }
        ]
      },
      "post": {
        "summary": "Creates policy subscription.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}": {
      "get": {
        "summary": "Gets policy details.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.read_only"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update policy",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      },
      "put": {
        "summary": "Updates policy.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}/attachments": {
      "get": {
        "summary": "Gets the list of policy attachments associated with the policy.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.read_only"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}/cancel": {
      "post": {
        "summary": "Cancel a policy according to its id.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}/finalize": {
      "post": {
        "summary": "Finalizes policy subscription, completing missing information.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}/payment_updates": {
      "post": {
        "summary": "Post new payment information related to the policy.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/policies/{policy_id}/rectify_failed_payment": {
      "post": {
        "summary": "Rectify the failed payments.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.policies.write"
            ]
          }
        ]
      }
    },
    "/sales/v2/individual/travel/quotes_requests": {
      "post": {
        "summary": "Gets quotes for travel insurances.",
        "description": "Cf. summary",
        "x-business-category": "TRAVEL",
        "security": [
          {
            "sandbox_auth0_cc": [
              "urn:axa.partners.sales.individual.travel.quotesrequests.write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "sandbox_auth0_cc": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://sandbox.auth.api.axapartners.com/oauth/token",
            "scopes": {
              "urn:axa.partners.sales.individual.travel.orders.write": "Right to act on order information.",
              "urn:axa.partners.sales.individual.travel.orders.read_only": "Right to read order information.",
              "urn:axa.partners.sales.individual.travel.policies.write": "Right to act on subscription information.",
              "urn:axa.partners.sales.individual.travel.policies.read_only": "Right to read subscription information.",
              "urn:axa.partners.sales.individual.travel.quotesrequests.write": "Right to create quotes requests."
            }
          }
        }
      }
    }
  },
  "x-version": "e658c67edafd784e031da77c299a55ec4f789b48 [sandbox]",
  "x-generated-at": "2026-03-31T14:46:14.022Z"
}