{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "name": "Web API Support",
      "url": "https://dev.fitbit.com/build/reference/web-api/help/"
    },
    "description": "Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authori[...]",
    "termsOfService": "https://dev.fitbit.com/legal/platform-terms-of-service/",
    "title": "Fitbit Web API Explorer",
    "version": "1",
    "x-jentic-source-url": "https://dev.fitbit.com/build/reference/web-api/explore/fitbit-web-api-swagger.json"
  },
  "servers": [
    {
      "url": "https://api.fitbit.com/"
    }
  ],
  "paths": {
    "/1.1/oauth2/introspect": {
      "post": {
        "security": [
          {
            "oauth2": []
          }
        ],
        "tags": [
          "Authorization"
        ],
        "description": "Retrieves the active state of an OAuth 2.0 token. It follows https://tools.ietf.org/html/rfc7662.",
        "operationId": "introspect",
        "summary": "Retrieve the active state of an OAuth 2.0 token"
      }
    },
    "/1.1/user/-/friends.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "social"
            ]
          }
        ],
        "tags": [
          "Friends"
        ],
        "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFriends",
        "summary": "Get Friends"
      }
    },
    "/1.1/user/-/leaderboard/friends.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "social"
            ]
          }
        ],
        "tags": [
          "Friends"
        ],
        "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFriendsLeaderboard",
        "summary": "Get Friends Leaderboard"
      }
    },
    "/1.2/user/-/sleep.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "Creates a log entry for a sleep event and returns a response in the format requested.",
        "operationId": "addSleep",
        "summary": "Log Sleep"
      }
    },
    "/1.2/user/-/sleep/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "The Get Sleep Logs by Date Range endpoint returns a list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given date range (inclusive of start and end dates).",
        "operationId": "getSleepByDateRange",
        "summary": "Get Sleep Logs by Date Range"
      }
    },
    "/1.2/user/-/sleep/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "The Get Sleep Logs by Date endpoint returns a summary and list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given day.",
        "operationId": "getSleepByDate",
        "summary": "Get Sleep Log"
      }
    },
    "/1.2/user/-/sleep/goal.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "Returns the user's sleep goal.",
        "operationId": "getSleepGoal",
        "summary": "Get Sleep Goal"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "Create or update the user's sleep goal and get a response in the JSON format.",
        "operationId": "updateSleepGoal",
        "summary": "Update Sleep Goal"
      }
    },
    "/1.2/user/-/sleep/list.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "The Get Sleep Logs List endpoint returns a list of a user's sleep logs (including naps) before or after a given day with offset, limit, and sort order.",
        "operationId": "getSleepList",
        "summary": "Get Sleep Logs List"
      }
    },
    "/1.2/user/-/sleep/{log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Sleep"
        ],
        "description": "Deletes a user's sleep log entry with the given ID.",
        "operationId": "deleteSleep",
        "summary": "Delete Sleep Log"
      }
    },
    "/1/activities.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives a tree of all valid Fitbit public activities from the activities catelog as well as private custom activities the user created in the format requested.",
        "operationId": "getActivitiesTypes",
        "summary": "Browse Activity Types"
      }
    },
    "/1/activities/{activity-id}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Returns the detail of a specific activity in the Fitbit activities database in the format requested. If activity has levels, it also returns a list of activity level details.",
        "operationId": "getActivitiesTypeDetail",
        "summary": "Get Activity Type"
      }
    },
    "/1/foods/locales.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns the food locales that the user may choose to search, log, and create food in.",
        "operationId": "getFoodsLocales",
        "summary": "Get Food Locales"
      }
    },
    "/1/foods/search.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of public foods from the Fitbit food database and private food the user created in the format requested.",
        "operationId": "getFoodsList",
        "summary": "Search Foods"
      }
    },
    "/1/foods/units.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of all valid Fitbit food units in the format requested.",
        "operationId": "getFoodsUnits",
        "summary": "Get Food Units"
      }
    },
    "/1/foods/{food-id}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns the details of a specific food in the Fitbit food databases or a private food that an authorized user has entered in the format requested.",
        "operationId": "getFoodsInfo",
        "summary": "Get Food"
      }
    },
    "/1/user/-/activities.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesLog",
        "summary": "Get Lifetime Stats"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "The Log Activity endpoint creates log entry for an activity or user's private custom activity using units in the unit system which corresponds to the Accept-Language header provided (or using optional custom distanceUnit) and get a response in the format requested.",
        "operationId": "addActivitiesLog",
        "summary": "Log Activity"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Intraday Time Series"
        ],
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
        "operationId": "getAZMByDateIntraday",
        "summary": "Get AZM Intraday by Date"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Intraday Time Series"
        ],
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
        "operationId": "getAZMByDateTimeSeriesIntraday",
        "summary": "Get AZM Intraday by Date"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Time Series"
        ],
        "description": "Returns the daily summary values over a period of time by specifying a date and time period.",
        "operationId": "getAZMTimeSeriesByDate",
        "summary": "Get AZM Time Series by Date"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Time Series"
        ],
        "description": "Returns the daily summary values over an interval by specifying a date range.",
        "operationId": "getAZMTimeSeriesByInterval",
        "summary": "Get AZM Time Series by Interval"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Intraday Time Series"
        ],
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
        "operationId": "getAZMByIntervalTimeSeriesIntraday",
        "summary": "Get AZM Intraday by Interval"
      }
    },
    "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity"
            ]
          }
        ],
        "tags": [
          "Active Zone Minutes Intraday Time Series"
        ],
        "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
        "operationId": "getAZMByIntervalIntraday",
        "summary": "Get AZM Intraday by Interval"
      }
    },
    "/1/user/-/activities/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retrieves a summary and list of a user's activities and activity log entries for a given day.",
        "operationId": "getActivitiesByDate",
        "summary": "Get Activity Summary by Date "
      }
    },
    "/1/user/-/activities/favorite.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Returns a list of a user's favorite activities.",
        "operationId": "getFavoriteActivities",
        "summary": "Get Favorite Activities"
      }
    },
    "/1/user/-/activities/favorite/{activity-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Removes the activity with the given ID from a user's list of favorite activities.",
        "operationId": "deleteFavoriteActivities",
        "summary": "Delete Favorite Activity"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Adds the activity with the given ID to user's list of favorite activities.",
        "operationId": "addFavoriteActivities",
        "summary": "Add Favorite Activity"
      }
    },
    "/1/user/-/activities/frequent.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives a list of a user's frequent activities in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFrequentActivities",
        "summary": "Get Frequent Activities"
      }
    },
    "/1/user/-/activities/goals/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives a user's current daily or weekly activity goals using measurement units as defined in the unit system, which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesGoals",
        "summary": "Get Activity Goals"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Updates a user's daily or weekly activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "addUpdateActivitiesGoals",
        "summary": "Update Activity Goals"
      }
    },
    "/1/user/-/activities/heart/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Time Series"
        ],
        "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "getHeartByDateRange",
        "summary": "Get Heart Rate Time Series"
      }
    },
    "/1/user/-/activities/heart/date/{date}/1d/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Intraday Time Series"
        ],
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateIntraday",
        "summary": "Get Heart Rate Intraday Time Series"
      }
    },
    "/1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Intraday Time Series"
        ],
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateTimestampIntraday",
        "summary": "Get Heart Rate Intraday Time Series"
      }
    },
    "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Intraday Time Series"
        ],
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateRangeIntraday",
        "summary": "Get Heart Rate Intraday Time Series"
      }
    },
    "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Intraday Time Series"
        ],
        "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized u[...]",
        "operationId": "getHeartByDateRangeTimestampIntraday",
        "summary": "Get Heart Rate Intraday Time Series"
      }
    },
    "/1/user/-/activities/heart/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Heart Rate Time Series"
        ],
        "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "getHeartByDatePeriod",
        "summary": "Get Heart Rate Time Series"
      }
    },
    "/1/user/-/activities/list.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives a list of user's activity log entries before or after a given day with offset and limit using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesLogList",
        "summary": "Get Activity Log List"
      }
    },
    "/1/user/-/activities/recent.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives a list of a user's recent activities types logged with some details of the last activity log of that type using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getRecentActivities",
        "summary": "Get Recent Activity Types"
      }
    },
    "/1/user/-/activities/tracker/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Time Series"
        ],
        "description": "Returns time series data in the specified range for a given resource.",
        "operationId": "getActivitiesTrackerResourceByDateRange",
        "summary": "Get Activity Tracker Resource by Date Range Time Series"
      }
    },
    "/1/user/-/activities/tracker/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Time Series"
        ],
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesTrackerResourceByDatePeriod",
        "summary": "Get Activity Time Series"
      }
    },
    "/1/user/-/activities/{activity-log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Deletes a user's activity log entry with the given ID.",
        "operationId": "deleteActivitiesLog",
        "summary": "Delete Activity Log"
      }
    },
    "/1/user/-/activities/{log-id}.tcx": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity"
        ],
        "description": "Retreives the details of a user's location and heart rate data during a logged exercise activity.",
        "operationId": "getActivitiesTCX",
        "summary": "Get Activity TCX"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Time Series"
        ],
        "description": "Returns activities time series data in the specified range for a given resource.",
        "operationId": "getActivitiesResourceByDateRange",
        "summary": "Get Activity Resource by Date Range"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Intraday Time Series"
        ],
        "description": "Returns the Activity Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateRangeIntraday",
        "summary": "Get Activity Intraday Time Series"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Intraday Time Series"
        ],
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateIntraday",
        "summary": "Get Intraday Time Series"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Intraday Time Series"
        ],
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateTimeSeriesIntraday",
        "summary": "Get Intraday Time Series"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Intraday Time Series"
        ],
        "description": "Returns the Intraday Time Series for a given resource in the format requested.",
        "operationId": "getActivitiesResourceByDateRangeTimeSeriesIntraday",
        "summary": "Get Activity Intraday Time Series"
      }
    },
    "/1/user/-/activities/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Activity Time Series"
        ],
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getActivitiesResourceByDatePeriod",
        "summary": "Get Activity Time Series"
      }
    },
    "/1/user/-/badges.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "User"
        ],
        "description": "Retrieves the user's badges in the format requested. Response includes all badges for the user as seen on the Fitbit website badge locker (both activity and weight related.) The endpoint returns weight and distance badges based on the user's unit profile preference as on the website.",
        "operationId": "getBadges",
        "summary": "Get Badges"
      }
    },
    "/1/user/-/body/log/fat.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Creates a log entry for body fat and returns a response in the format requested.",
        "operationId": "addBodyFatLog",
        "summary": "Log Body Fat"
      }
    },
    "/1/user/-/body/log/fat/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDateRange",
        "summary": "Get Body Fat Logs"
      }
    },
    "/1/user/-/body/log/fat/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDate",
        "summary": "Get Body Fat Logs"
      }
    },
    "/1/user/-/body/log/fat/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getBodyFatByDatePeriod",
        "summary": "Get Body Fat Logs"
      }
    },
    "/1/user/-/body/log/fat/goal.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Updates user's fat percentage goal.",
        "operationId": "UpdateBodyFatGoal",
        "summary": "Update Body Fat Goal"
      }
    },
    "/1/user/-/body/log/fat/{body-fat-log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Deletes a user's body fat log entry with the given ID.",
        "operationId": "deleteBodyFatLog",
        "summary": "Delete Body Fat Log"
      }
    },
    "/1/user/-/body/log/weight.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Creates log entry for a body weight using units in the unit systems that corresponds to the Accept-Language header provided and gets a response in the format requested.",
        "operationId": "addWeightLog",
        "summary": "Log Weight"
      }
    },
    "/1/user/-/body/log/weight/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
        "operationId": "getWeightByDateRange",
        "summary": "Get Body Fat Logs"
      }
    },
    "/1/user/-/body/log/weight/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body weight log entries for a given day using units in the unit systems which corresponds to the Accept-Language header provided.",
        "operationId": "getWeightByDate",
        "summary": "Get Weight Logs"
      }
    },
    "/1/user/-/body/log/weight/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a list of all user's body weight log entries for a given day in the format requested.",
        "operationId": "getWeightByDatePeriod",
        "summary": "Get Body Fat Logs"
      }
    },
    "/1/user/-/body/log/weight/goal.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "profile",
              "heartrate",
              "location"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Updates user's fat percentage goal.",
        "operationId": "updateWeightGoal",
        "summary": "Update Weight Goal"
      }
    },
    "/1/user/-/body/log/weight/{body-weight-log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Deletes a user's body weight log entrywith the given ID.",
        "operationId": "deleteWeightLog",
        "summary": "Delete Weight Log"
      }
    },
    "/1/user/-/body/log/{goal-type}/goal.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body"
        ],
        "description": "Retreives a user's current body fat percentage or weight goal using units in the unit systems that corresponds to the Accept-Language header providedin the format requested.",
        "operationId": "getBodyGoals",
        "summary": "Get Body Goals"
      }
    },
    "/1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body Time Series"
        ],
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getBodyResourceByDateRange",
        "summary": "Get Body Time Series"
      }
    },
    "/1/user/-/body/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Body Time Series"
        ],
        "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getBodyResourceByDatePeriod",
        "summary": "Get Body Time Series"
      }
    },
    "/1/user/-/br/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "respiratory_rate"
            ]
          }
        ],
        "tags": [
          "Breathing Rate"
        ],
        "description": "This endpoint returns average breathing rate data for a single date. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
        "operationId": "getBreathingRateSummaryByDate",
        "summary": "Get Breathing Rate Summary by Date"
      }
    },
    "/1/user/-/br/date/{date}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "respiratory_rate"
            ]
          }
        ],
        "tags": [
          "Breathing Rate Intraday"
        ],
        "description": "This endpoint returns intraday breathing rate data for a single date. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
        "operationId": "getBreathingRateIntradayByDate",
        "summary": "Get Breathing Rate Intraday by Date"
      }
    },
    "/1/user/-/br/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "respiratory_rate"
            ]
          }
        ],
        "tags": [
          "Breathing Rate"
        ],
        "description": "This endpoint returns average breathing rate data for a date range. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
        "operationId": "getBreathingRateSummaryByInterval",
        "summary": "Get Breathing Rate Summary by Interval"
      }
    },
    "/1/user/-/br/date/{startDate}/{endDate}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "respiratory_rate"
            ]
          }
        ],
        "tags": [
          "Breathing Rate Intraday"
        ],
        "description": "This endpoint returns intraday breathing rate data for a date range. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
        "operationId": "getBreathingRateIntradayByInterval",
        "summary": "Get Breathing Rate Intraday by Interval"
      }
    },
    "/1/user/-/cardioscore/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "cardio_fitness"
            ]
          }
        ],
        "tags": [
          "Cardio Fitness Score (VO2 Max)"
        ],
        "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a single date. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
        "operationId": "getVo2MaxSummaryByDate",
        "summary": "Get VO2 Max Summary by Date"
      }
    },
    "/1/user/-/cardioscore/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "cardio_fitness"
            ]
          }
        ],
        "tags": [
          "Cardio Fitness Score (VO2 Max)"
        ],
        "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a date range. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
        "operationId": "getVo2MaxSummaryByInterval",
        "summary": "Get VO2 Max Summary by Interval"
      }
    },
    "/1/user/-/devices.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Devices"
        ],
        "description": "Returns a list of the Fitbit devices connected to a user's account.",
        "operationId": "getDevices",
        "summary": "Get Devices"
      }
    },
    "/1/user/-/devices/tracker/{tracker-id}/alarms.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Devices"
        ],
        "description": "Returns alarms for a device",
        "operationId": "getAlarms",
        "summary": "Get Alarms"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Devices"
        ],
        "description": "Adds the alarm settings to a given ID for a given device.",
        "operationId": "addAlarms",
        "summary": "Add Alarm"
      }
    },
    "/1/user/-/devices/tracker/{tracker-id}/alarms/{alarm-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Devices"
        ],
        "description": "Deletes the user's device alarm entry with the given ID for a given device.",
        "operationId": "deleteAlarms",
        "summary": "Delete Alarm"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Devices"
        ],
        "description": "Updates the alarm entry with a given ID for a given device. It also gets a response in the format requested.",
        "operationId": "updateAlarms",
        "summary": "Update Alarm"
      }
    },
    "/1/user/-/ecg/list.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "electrocardiogram"
            ]
          }
        ],
        "tags": [
          "Electrocardiogram"
        ],
        "description": "This endpoint is used for querying the user's on-device ECG readings.",
        "operationId": "getEcgLogList",
        "summary": "Get ECG Log List"
      }
    },
    "/1/user/-/foods.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Creates a new private food for a user and returns a response in the format requested. The created food is found via the Search Foods call.",
        "operationId": "addFoods",
        "summary": "Create Food"
      }
    },
    "/1/user/-/foods/log.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Creates food log entries for users with or without foodId value.",
        "operationId": "addFoodsLog",
        "summary": "Log Food"
      }
    },
    "/1/user/-/foods/log/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Retreives a summary and list of a user's food log entries for a given day in the format requested.",
        "operationId": "getFoodsByDate",
        "summary": "Get Food Logs"
      }
    },
    "/1/user/-/foods/log/favorite.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of a user's favorite foods in the format requested. A favorite food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getFavoriteFoods",
        "summary": "Get Favorite Foods"
      }
    },
    "/1/user/-/foods/log/favorite/{food-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Deletes a food with the given ID to the user's list of favorite foods.",
        "operationId": "deleteFavoriteFood",
        "summary": "Delete Favorite Food"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "addFavoriteFood",
        "summary": "Add Favorite Food"
      }
    },
    "/1/user/-/foods/log/frequent.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getFrequentFoods",
        "summary": "Get Frequent Foods"
      }
    },
    "/1/user/-/foods/log/goal.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a user's current daily calorie consumption goal and/or foodPlan value in the format requested.",
        "operationId": "getFoodsGoal",
        "summary": "Get Food Goals"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
        "operationId": "addUpdateFoodsGoal",
        "summary": "Update Food Goal"
      }
    },
    "/1/user/-/foods/log/recent.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
        "operationId": "getRecentFoods",
        "summary": "Get Recent Foods"
      }
    },
    "/1/user/-/foods/log/water.json": {
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Creates a log entry for water using units in the unit systems that corresponds to the Accept-Language header provided.",
        "operationId": "addWaterLog",
        "summary": "Log Water"
      }
    },
    "/1/user/-/foods/log/water/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Retreives a summary and list of a user's water log entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getWaterByDate",
        "summary": "Get Water Logs"
      }
    },
    "/1/user/-/foods/log/water/goal.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Retreives a summary and list of a user's water goal entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
        "operationId": "getWaterGoal",
        "summary": "Get Water Goal"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
        "operationId": "addUpdateWaterGoal",
        "summary": "Update Water Goal"
      }
    },
    "/1/user/-/foods/log/water/{water-log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Deletes a user's water log entry with the given ID.",
        "operationId": "deleteWaterLog",
        "summary": "Delete Water Log"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Updates a user's water log entry with the given ID.",
        "operationId": "updateWaterLog",
        "summary": "Update Water Log"
      }
    },
    "/1/user/-/foods/log/{food-log-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Deletes a user's food log entry with the given ID.",
        "operationId": "deleteFoodsLog",
        "summary": "Delete Food Log"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "The Edit Food Log endpoint changes the quantity or calories consumed for a user's food log entry with the given Food Log ID.",
        "operationId": "editFoodsLog",
        "summary": "Edit Food Log"
      }
    },
    "/1/user/-/foods/log/{resource-path}/date/{base-date}/{end-date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition Time Series"
        ],
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFoodsByDateRange",
        "summary": "Get Food or Water Time Series"
      }
    },
    "/1/user/-/foods/log/{resource-path}/date/{date}/{period}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition Time Series"
        ],
        "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
        "operationId": "getFoodsResourceByDatePeriod",
        "summary": "Get Food or Water Time Series"
      }
    },
    "/1/user/-/foods/{food-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Deletes custom food for a user and returns a response in the format requested.",
        "operationId": "deleteFoods",
        "summary": "Delete Custom Food"
      }
    },
    "/1/user/-/hrv/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "heartrate"
            ]
          }
        ],
        "tags": [
          "Heart Rate Variability"
        ],
        "description": "This endpoint returns the Heart Rate Variability (HRV) data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvSummaryDate",
        "summary": "Get HRV Summary by Date"
      }
    },
    "/1/user/-/hrv/date/{date}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "heartrate"
            ]
          }
        ],
        "tags": [
          "Heart Rate Variability Intraday"
        ],
        "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvIntradayByDate",
        "summary": "Get HRV Intraday by Date"
      }
    },
    "/1/user/-/hrv/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "heartrate"
            ]
          }
        ],
        "tags": [
          "Heart Rate Variability"
        ],
        "description": "This endpoint returns the Heart Rate Variability (HRV) data for a date range. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvSummaryInterval",
        "summary": "Get HRV Summary by Interval"
      }
    },
    "/1/user/-/hrv/date/{startDate}/{endDate}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "heartrate"
            ]
          }
        ],
        "tags": [
          "Heart Rate Variability Intraday"
        ],
        "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
        "operationId": "getHrvIntradayByInterval",
        "summary": "Get HRV Intraday by Interval"
      }
    },
    "/1/user/-/irn/alerts/list.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "irregular_rhythm_notifications"
            ]
          }
        ],
        "tags": [
          "Irregular Rhythm Notifications"
        ],
        "description": "This endpoint returns a paginated list of Irregular Rhythm Notifications (IRN) alerts, as well as all of the alert tachograms. This endpoint will only return alerts that the user has read in the Fitbit app already, as that is meant as the primary entrypoint for viewing notifications.",
        "operationId": "getIrnAlertsList",
        "summary": "Get IRN Alerts List"
      }
    },
    "/1/user/-/irn/profile.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "irregular_rhythm_notifications"
            ]
          }
        ],
        "tags": [
          "Irregular Rhythm Notifications"
        ],
        "description": "This endpoint returns the user state for Irregular Rhythm Notifications (IRN). The user state contains most information about the user’s current engagement with the feature, including onboarding progress and algorithm processing state.",
        "operationId": "getIrnProfile",
        "summary": "Get IRN Profile"
      }
    },
    "/1/user/-/meals.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Returns a list of meals created by user in the user's food log in the format requested. User creates and manages meals on the Food Log tab on the website.",
        "operationId": "getMeals",
        "summary": "Get Meals"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Creates a meal with the given food contained in the post body.",
        "operationId": "addMeal",
        "summary": "Create Meal"
      }
    },
    "/1/user/-/meals/{meal-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Deletes a user's meal with the given meal id.",
        "operationId": "deleteMeal",
        "summary": "Delete Meal"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "nutrition"
            ]
          }
        ],
        "tags": [
          "Nutrition"
        ],
        "description": "Replaces an existing meal with the contents of the request. The response contains the updated meal.",
        "operationId": "updateMeal",
        "summary": "Update Meal"
      }
    },
    "/1/user/-/profile.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "location",
              "profile",
              "weight"
            ]
          }
        ],
        "tags": [
          "User"
        ],
        "description": "Returns a user's profile. The authenticated owner receives all values. However, the authenticated user's access to other users' data is subject to those users' privacy settings. Numerical values are returned in the unit system specified in the Accept-Language header.",
        "operationId": "getProfile",
        "summary": "Get Profile"
      }
    },
    "/1/user/-/spo2/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "oxygen_saturation"
            ]
          }
        ],
        "tags": [
          "SpO2"
        ],
        "description": "This endpoint returns the SpO2 summary data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2SummaryByDate",
        "summary": "Get SpO2 Summary by Date"
      }
    },
    "/1/user/-/spo2/date/{date}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "oxygen_saturation"
            ]
          }
        ],
        "tags": [
          "SpO2 Intraday"
        ],
        "description": "This endpoint returns the SpO2 intraday data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2IntradayByDate",
        "summary": "Get SpO2 Intraday by Date"
      }
    },
    "/1/user/-/spo2/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "oxygen_saturation"
            ]
          }
        ],
        "tags": [
          "SpO2"
        ],
        "description": "This endpoint returns the SpO2 summary data for a date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2SummaryByInterval",
        "summary": "Get SpO2 Summary by Interval"
      }
    },
    "/1/user/-/spo2/date/{startDate}/{endDate}/all.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "oxygen_saturation"
            ]
          }
        ],
        "tags": [
          "SpO2 Intraday"
        ],
        "description": "This endpoint returns the SpO2 intraday data for a specified date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getSpO2IntradayByInterval",
        "summary": "Get SpO2 Intraday by Interval"
      }
    },
    "/1/user/-/temp/core/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "temperature"
            ]
          }
        ],
        "tags": [
          "Temperature"
        ],
        "description": "Returns the Temperature (Core) data for a single date. Temperature (Core) data applies specifically to data logged manually by the user throughout the day.",
        "operationId": "getTempCoreSummaryByDate",
        "summary": "Get Temperature (Core) Summary by Date"
      }
    },
    "/1/user/-/temp/core/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "temperature"
            ]
          }
        ],
        "tags": [
          "Temperature"
        ],
        "description": "Returns Temperature (Core) data for a date range. Temperature (Core) data applies specifically to data logged manually by the user throughout the day and the maximum date range cannot exceed 30 days.",
        "operationId": "getTempCoreSummaryByInterval",
        "summary": "Get Temperature (Core) Summary by Interval"
      }
    },
    "/1/user/-/temp/skin/date/{date}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "temperature"
            ]
          }
        ],
        "tags": [
          "Temperature"
        ],
        "description": "Returns the Temperature (Skin) data for a single date. Temperature (Skin) data applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
        "operationId": "getTempSkinSummaryDate",
        "summary": "Get Temperature (Skin) Summary by Date"
      }
    },
    "/1/user/-/temp/skin/date/{startDate}/{endDate}.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "temperature"
            ]
          }
        ],
        "tags": [
          "Temperature"
        ],
        "description": "Returns Temperature (Skin) data for a date range. It only returns a value for dates on which the Fitbit device was able to record Temperature (skin) data and the maximum date range cannot exceed 30 days.",
        "operationId": "getTempSkinSummaryByInterval",
        "summary": "Get Temperature (Skin) Summary by Interval"
      }
    },
    "/1/user/-/{collection-path}/apiSubscriptions.json": {
      "get": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Subscriptions"
        ],
        "description": "Retreives a list of a user's subscriptions for your application in the format requested. You can either fetch subscriptions for a specific collection or the entire list of subscriptions for the user. For best practice, make sure that your application maintains this list on your side and use this endpoint only to periodically ensure data consistency.",
        "operationId": "getSubscriptionsList",
        "summary": "Get a List of Subscriptions"
      }
    },
    "/1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Subscriptions"
        ],
        "description": "Deletes a subscription for a user..",
        "operationId": "deleteSubscriptions",
        "summary": "Delete a Subscription"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "activity",
              "heartrate",
              "location",
              "nutrition",
              "profile",
              "settings",
              "sleep",
              "social",
              "weight"
            ]
          }
        ],
        "tags": [
          "Subscriptions"
        ],
        "description": "Adds a subscription in your application so that users can get notifications and return a response in the format requested. The subscription-id value provides a way to associate an update with a particular user stream in your application.",
        "operationId": "addSubscriptions",
        "summary": "Add a Subscription"
      }
    },
    "/oauth2/revoke": {
      "post": {
        "security": [
          {
            "oauth2": []
          }
        ],
        "tags": [
          "Authorization"
        ],
        "description": "Revokes consent of the access token or refresh token",
        "operationId": "revoke",
        "summary": "Revokes consent of the access token or refresh token"
      }
    },
    "/oauth2/token": {
      "post": {
        "tags": [
          "Authorization"
        ],
        "description": "Retrieves an OAuth 2 access token.",
        "operationId": "oauthToken",
        "summary": "Get OAuth 2 access token"
      }
    },
    "post": {
      "security": [
        {
          "oauth2": [
            "activity",
            "heartrate",
            "location",
            "nutrition",
            "profile",
            "settings",
            "sleep",
            "social",
            "temperature",
            "weight"
          ]
        }
      ],
      "tags": [
        "User"
      ],
      "description": "Updates a user's profile using a form.",
      "operationId": "updateProfile",
      "summary": "Update Profile"
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "flows": {
          "implicit": {
            "authorizationUrl": "https://www.fitbit.com/oauth2/authorize",
            "scopes": {
              "activity": "Activity data and exercise log related features, such as steps, distance, calories burned, and active minutes",
              "cardio_fitness": "Maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise",
              "electrocardiogram": "A users on-device ECG readings",
              "heartrate": "Continuous heart rate & HRV data and related analysis",
              "irregular_rhythm_notifications": "Includes the users engagement and list of irregular rhythm notification alerts.",
              "location": "GPS and other location data",
              "nutrition": "Calorie consumption and nutrition related features, such as food/water logging, goals, and plans",
              "oxygen_saturation": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level",
              "profile": "Basic user information",
              "respiratory_rate": "Respiratory Rate is a measurement of your breaths at night.",
              "settings": "User account and device settings, such as alarms",
              "sleep": "Sleep logs and related sleep analysis",
              "social": "Friend-related features, such as friend list and leaderboard",
              "temperature": "Core and skin temperature data",
              "weight": "Weight and related information, such as body mass index, body fat percentage, and goals"
            }
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "description": "The Active Zone Minutes (AZM) Intraday Time Series endpoints retrieve the user's heart-pumping activity for a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Active Zone Minutes.",
      "name": "Active Zone Minutes Intraday Time Series"
    },
    {
      "description": "The Active Zone Minutes (AZM) Time Series endpoints are used for querying the user's heart-pumping activity throughout the day. ",
      "name": "Active Zone Minutes Time Series"
    },
    {
      "description": "The Activity endpoints are used to query and/or modify a Fitbit user's daily activity data. ",
      "name": "Activity"
    },
    {
      "description": "The Activity Intraday Time Series endpoints retrieve the data for a given resource on a specific date or 24 hour period.  Intraday support can extend the detail-level response to include 1min, 5min and 15min for the activity.",
      "name": "Activity Intraday Time Series"
    },
    {
      "description": "The Activity Time Series endpoints are used to query a Fitbit user's activity data over a period of time, either by specifying a date and time period, or a date range.",
      "name": "Activity Time Series"
    },
    {
      "description": "The Authorization endpoints allow an application to onboard Fitbit users who want to share their data with the specified application. The application can initiate the consent flow for new users, obtain the access token and refresh tokens, validate the tokens, and revoke consent to the user.",
      "name": "Authorization"
    },
    {
      "description": "The Body endpoints are used for querying and modifying the user's body fat and weight data.",
      "name": "Body"
    },
    {
      "description": "The Body Time Series endpoints are used for querying body fat and weight data over a period of time either by specifying a date and time period, or a date range.",
      "name": "Body Time Series"
    },
    {
      "description": "Breathing Rate or Respiratory Rate is a measurement of your average breaths per minute at night.",
      "name": "Breathing Rate"
    },
    {
      "description": "The Breathing Rate Intraday endpoint returns the  average breathing rate throughout the day and categories your breathing rate by sleep stage.",
      "name": "Breathing Rate Intraday"
    },
    {
      "description": "The Cardio Fitness Score (also known as VO2 Max) endpoints are used for querying the maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise.",
      "name": "Cardio Fitness Score (VO2 Max)"
    },
    {
      "description": "The Devices endpoints displays information about the devices paired to a user's account.",
      "name": "Devices"
    },
    {
      "description": "The Electrocardiogram (also known as ECG) endpoint is used for querying the user's on-device ECG readings.",
      "name": "Electrocardiogram"
    },
    {
      "description": "The Friends endpoints display information about the specified user's friends and the friend's leaderboard.",
      "name": "Friends"
    },
    {
      "description": "The Heart Rate Intraday Time Series retrieves the heart rate data on a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1sec, 1min, 5min or 15min for Heart Rate.",
      "name": "Heart Rate Intraday Time Series"
    },
    {
      "description": "The Heart Rate Time Series endpoints are used for querying the user's heart rate data.",
      "name": "Heart Rate Time Series"
    },
    {
      "description": "The Heart Rate Variability (HRV) endpoints are used for querying the user’s heart rate variability data.",
      "name": "Heart Rate Variability"
    },
    {
      "description": "The Heart Rate Variability Intraday endpoint returns the HRV rate at various times and returns Root Mean Square of Successive Differences (rmssd), Low Frequency (LF), High Frequency (HF), and Coverage data for a given measurement.",
      "name": "Heart Rate Variability Intraday"
    },
    {
      "description": "The Irregular Rhythm Notifications (also known as IRN) endpoints are used for querying the user's engagement with the IRN feature and the alerts received. The IRN API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes.",
      "name": "Irregular Rhythm Notifications"
    },
    {
      "description": "The Nutrition endpoints are used for querying and modifying the food and water data.",
      "name": "Nutrition"
    },
    {
      "description": "The Nutrition Time Series endpoints are used for querying food- and water-related data over a period of time either by specifying a date and time period, or a date range.",
      "name": "Nutrition Time Series"
    },
    {
      "description": "The Sleep endpoints are used for querying and modifying the user’s general sleep data.",
      "name": "Sleep"
    },
    {
      "description": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level. ",
      "name": "SpO2"
    },
    {
      "description": "The SpO2 Intraday endpoints return the SpO2 values calculated on a 5-minute exponentially-moving average.",
      "name": "SpO2 Intraday"
    },
    {
      "description": "The Subscription endpoints allow an application to request notifications to user's specific data collection.",
      "name": "Subscriptions"
    },
    {
      "description": "The Temperature endpoints are used for querying either the core temperature data logged manually by the user, or the skin temperature recorded by the device while the user is asleep.",
      "name": "Temperature"
    },
    {
      "description": "The User endpoints display information about the user's profile information, the regional locale & language settings, and their badges collected",
      "name": "User"
    }
  ]
}