{
  "openapi": "3.0.3",
  "info": {
    "title": "Staatic API documentation",
    "description": "This is the Staatic API. You can find out more about Staatic at [https://staatic.com](https://staatic.com).",
    "termsOfService": "https://staatic.com/terms",
    "contact": {
      "name": "Staatic Support",
      "url": "https://staatic.com/support",
      "email": "contact@staatic.com"
    },
    "license": {
      "name": "proprietary",
      "url": "https://staatic.com/license"
    },
    "version": "1.0.2",
    "x-logo": {
      "url": "/logo.svg",
      "href": "https://staatic.com/",
      "altText": "Staatic"
    },
    "x-jentic-source-url": "https://api.staatic.com/docs"
  },
  "servers": [
    {
      "url": "https://api.staatic.com/",
      "description": "Main (production) server"
    }
  ],
  "paths": {
    "/v1/deployments": {
      "get": {
        "tags": [
          "deployment"
        ],
        "summary": "Gets a collection of deployments",
        "operationId": "getDeployments",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "deployment"
        ],
        "summary": "Creates a new deployment",
        "operationId": "createDeployment",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/deployments/{id}": {
      "get": {
        "tags": [
          "deployment"
        ],
        "summary": "Gets a deployment by ID",
        "operationId": "getDeploymentById",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "deployment"
        ],
        "summary": "Updates an existing deployment",
        "operationId": "updateDeployment",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/sites/{id}/files": {
      "get": {
        "tags": [
          "file"
        ],
        "summary": "Gets a collection of deployment files for the specified site",
        "operationId": "getSiteFiles",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/deployments/{id}/files/{path}": {
      "put": {
        "tags": [
          "file"
        ],
        "summary": "Uploads a deployment file",
        "operationId": "uploadDeploymentFile",
        "security": [
          {
            "oauth_user": [
              "manage-deployments"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/forms": {
      "get": {
        "tags": [
          "form"
        ],
        "summary": "Gets a collection of forms",
        "operationId": "getForms",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "form"
        ],
        "summary": "Creates a new form",
        "operationId": "createForm",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/forms/{id}": {
      "get": {
        "tags": [
          "form"
        ],
        "summary": "Gets a form by ID",
        "operationId": "getFormById",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "form"
        ],
        "summary": "Deletes an existing form",
        "operationId": "deleteForm",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "form"
        ],
        "summary": "Updates an existing form",
        "operationId": "updateForm",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-notifications": {
      "get": {
        "tags": [
          "form-notification"
        ],
        "summary": "Gets a collection of form notifications",
        "operationId": "getFormNotifications",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "form-notification"
        ],
        "summary": "Creates a new form notification",
        "operationId": "createFormNotification",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-notifications/{id}": {
      "get": {
        "tags": [
          "form-notification"
        ],
        "summary": "Gets a form notification by ID",
        "operationId": "getFormNotificationById",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "form-notification"
        ],
        "summary": "Deletes an existing form notification",
        "operationId": "deleteFormNotification",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "form-notification"
        ],
        "summary": "Updates an existing form notification",
        "operationId": "updateFormNotification",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-submissions": {
      "get": {
        "tags": [
          "form-submission"
        ],
        "summary": "Gets a collection of form submissions",
        "operationId": "getFormSubmissions",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "form-submission"
        ],
        "summary": "Creates a new form submission",
        "operationId": "createFormSubmission",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-submissions/{id}": {
      "get": {
        "tags": [
          "form-submission"
        ],
        "summary": "Gets a form submission by ID",
        "operationId": "getFormSubmissionById",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "form-submission"
        ],
        "summary": "Deletes an existing form submission",
        "operationId": "deleteFormSubmission",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "form-submission"
        ],
        "summary": "Updates an existing form submission",
        "operationId": "updateFormSubmission",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-templates": {
      "get": {
        "tags": [
          "form-template"
        ],
        "summary": "Gets a collection of form templates",
        "operationId": "getFormTemplates",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "form-template"
        ],
        "summary": "Creates a new form template",
        "operationId": "createFormTemplate",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/form-templates/{id}": {
      "get": {
        "tags": [
          "form-template"
        ],
        "summary": "Gets a form template by ID",
        "operationId": "getFormTemplateById",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "form-template"
        ],
        "summary": "Deletes an existing form template",
        "operationId": "deleteFormTemplate",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "form-template"
        ],
        "summary": "Updates an existing form template",
        "operationId": "updateFormTemplate",
        "security": [
          {
            "oauth_user": [
              "manage-forms"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/plugins": {
      "get": {
        "tags": [
          "plugin"
        ],
        "summary": "Gets a collection of plugins",
        "operationId": "getPlugins",
        "security": [
          {
            "oauth_user": []
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search/{index}": {
      "post": {
        "tags": [
          "search"
        ],
        "summary": "Performs a search query on the specified search index",
        "operationId": "search",
        "security": [
          {
            "public_api_key": []
          }
        ]
      }
    },
    "/v1/search-indices": {
      "get": {
        "tags": [
          "search-index"
        ],
        "summary": "Gets a collection of search indices",
        "operationId": "getSearchIndices",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "search-index"
        ],
        "summary": "Creates a new search index",
        "operationId": "createSearchIndex",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search-indices/{index}": {
      "get": {
        "tags": [
          "search-index"
        ],
        "summary": "Gets a search index by name",
        "operationId": "getSearchIndexByName",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "search-index"
        ],
        "summary": "Deletes an existing search index",
        "operationId": "deleteSearchIndex",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "search-index"
        ],
        "summary": "Updates an existing search index",
        "operationId": "updateSearchIndex",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search-indices/{index}/clear": {
      "post": {
        "tags": [
          "search-index"
        ],
        "summary": "Clears a search index by name",
        "operationId": "clearSearchIndexByName",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search-indices/{index}/{id}": {
      "delete": {
        "tags": [
          "search-record"
        ],
        "summary": "Deletes an existing search record",
        "operationId": "deleteSearchRecord",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search-indices/{index}/import": {
      "post": {
        "tags": [
          "search-record"
        ],
        "summary": "Imports search records into the specified search index",
        "operationId": "importSearchRecords",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/search-indices/{index}/delete": {
      "post": {
        "tags": [
          "search-record"
        ],
        "summary": "Deletes search records from the specified search index",
        "operationId": "deleteSearchRecords",
        "security": [
          {
            "oauth_user": [
              "manage-search"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/sites": {
      "get": {
        "tags": [
          "site"
        ],
        "summary": "Gets a collection of sites",
        "operationId": "getSites",
        "security": [
          {
            "oauth_user": [
              "manage-sites"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "post": {
        "tags": [
          "site"
        ],
        "summary": "Creates a new site",
        "operationId": "createSite",
        "security": [
          {
            "oauth_user": [
              "manage-sites"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/sites/{id}": {
      "get": {
        "tags": [
          "site"
        ],
        "summary": "Gets a site by ID",
        "operationId": "getSiteById",
        "security": [
          {
            "oauth_user": [
              "manage-sites"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "delete": {
        "tags": [
          "site"
        ],
        "summary": "Deletes an existing site",
        "operationId": "deleteSite",
        "security": [
          {
            "oauth_user": [
              "manage-sites"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      },
      "patch": {
        "tags": [
          "site"
        ],
        "summary": "Updates an existing site",
        "operationId": "updateSite",
        "security": [
          {
            "oauth_user": [
              "manage-sites"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    },
    "/v1/subscriptions": {
      "get": {
        "tags": [
          "subscription"
        ],
        "summary": "Gets a collection of subscriptions",
        "operationId": "getSubscriptions",
        "security": [
          {
            "oauth_user": [
              "manage-subscriptions"
            ]
          },
          {
            "oauth_site": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth_site": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/oauth2/token",
            "scopes": {}
          }
        }
      },
      "oauth_user": {
        "type": "oauth2",
        "flows": {
          "password": {
            "tokenUrl": "/oauth2/token",
            "refreshUrl": "/oauth2/token",
            "scopes": {
              "manage-deployments": "Manage deployments",
              "manage-forms": "Manage forms",
              "manage-sites": "Manage sites",
              "manage-search": "Manage search"
            }
          }
        }
      },
      "public_api_key": {
        "type": "apiKey",
        "name": "X-Staatic-API-Key",
        "in": "header"
      }
    }
  },
  "tags": [
    {
      "name": "deployment",
      "description": "Deployment operations",
      "x-displayName": "Deployments"
    },
    {
      "name": "file",
      "description": "File operations",
      "x-displayName": "Files"
    },
    {
      "name": "form",
      "description": "Form operations",
      "x-displayName": "Forms"
    },
    {
      "name": "form-notification",
      "description": "Form notification operations",
      "x-displayName": "Form Notifications"
    },
    {
      "name": "form-submission",
      "description": "Form submission operations",
      "x-displayName": "Form Submissions"
    },
    {
      "name": "form-template",
      "description": "Form template operations",
      "x-displayName": "Form Templates"
    },
    {
      "name": "plugin",
      "description": "Plugin operations",
      "x-displayName": "Plugins"
    },
    {
      "name": "search",
      "description": "Search operations",
      "x-displayName": "Search"
    },
    {
      "name": "search-index",
      "description": "Search index operations",
      "x-displayName": "Search Indices"
    },
    {
      "name": "search-record",
      "description": "Search record operations",
      "x-displayName": "Search Records"
    },
    {
      "name": "site",
      "description": "Site operations",
      "x-displayName": "Sites"
    },
    {
      "name": "subscription",
      "description": "Subscription operations",
      "x-displayName": "Subscriptions"
    }
  ],
  "x-tagGroups": [
    {
      "name": "Account",
      "tags": [
        "subscription",
        "site",
        "plugin"
      ]
    },
    {
      "name": "Deployments",
      "tags": [
        "deployment",
        "file"
      ]
    },
    {
      "name": "Forms",
      "tags": [
        "form",
        "form-notification",
        "form-template",
        "form-submission"
      ]
    },
    {
      "name": "Search",
      "tags": [
        "search",
        "search-index",
        "search-record"
      ]
    }
  ]
}