{
  "openapi": "3.0.3",
  "info": {
    "title": "AppConnect V3",
    "description": "The Constant Contact, Inc. V3 public API, for building integrations with Constant Contact, the leading small-business email marketing platform.",
    "contact": {
      "name": "webservices@constantcontact.com"
    },
    "license": {
      "name": "Private",
      "url": "https://www.constantcontact.com/legal/terms-of-use"
    },
    "version": "3.0.141",
    "x-jentic-source-url": "https://developer.constantcontact.com"
  },
  "servers": [
    {
      "url": "https://api.cc.email/v3"
    }
  ],
  "tags": [
    {
      "name": "Account Services",
      "description": "Use the account endpoints and methods to get account information."
    },
    {
      "name": "Bulk Activities",
      "description": "Bulk activities endpoints are used to manage large numbers of contacts, lists, and tags."
    },
    {
      "name": "Contacts",
      "description": "Endpoints and methods to get, create, delete, and update one or more contacts."
    },
    {
      "name": "Contact Lists",
      "description": "Endpoints and methods to get, create, delete, and update one or more contact lists."
    },
    {
      "name": "Contact Tags",
      "description": "Endpoints and methods to get, create, delete, and update one or more contact tags."
    },
    {
      "name": "Contacts Reporting",
      "description": "Contact reporting endpoints are used to gather activity reports for campaigns sent to a contact."
    },
    {
      "name": "Contacts Custom Fields",
      "description": "Endpoints and methods to get, create, delete, and update on one or more custom fields."
    },
    {
      "name": "Email Campaigns",
      "description": "Use email campaign endpoints and methods to get, create, and update email campaigns."
    },
    {
      "name": "Email Campaigns AB Tests",
      "description": "Use email campaigns A/B Test endpoints and methods to get, create, delete and update A/B tests."
    },
    {
      "name": "Email Reporting",
      "description": "Use the email reporting endpoints and methods to get reporting data for email campaigns you sent to contacts."
    },
    {
      "name": "Email Scheduling",
      "description": "Use email scheduling endpoints and methods to schedule an email campaign activity, unschedule an email campaign activity, and GET schedule information."
    },
    {
      "name": "Events",
      "description": "Endpoints and methods used to create and manage events."
    },
    {
      "name": "Segments",
      "description": "Use segments to target a subset of your contacts that are most likely to engage with a particular campaign."
    },
    {
      "name": "Landing Pages Reporting",
      "description": "Use landing pages reporting endpoints and methods to get reporting data about how a contact interacted with a campaign activity."
    },
    {
      "name": "SMS Reporting",
      "description": "Use SMS reporting endpoints and methods to get reporting data about SMS campaigns."
    },
    {
      "name": "Technology Partners",
      "description": "Use partner endpoints to manage client Constant Contact accounts under your partner account."
    },
    {
      "name": "Technology Partners Webhooks",
      "description": "Use partner webhooks to subscribe to billing event notifications from Constant Contact."
    }
  ],
  "paths": {
    "/account/user/privileges": {
      "get": {
        "tags": [
          "Account Services"
        ],
        "summary": "GET User Privileges",
        "description": "Use this method to return the user privileges associated with your access token as an array of objects. This method returns all user privileges, including privileges the V3 API does not currently use. Constant Contact requires specific user privileges to make requests using the V3 API. For more information, see the [User Privileges and Roles Overview](/api_guide/user_privileges.html).",
        "operationId": "getUserPrivileges",
        "security": [
          {
            "oauth2_implicit": []
          },
          {
            "oauth2_access_code": []
          }
        ]
      }
    },
    "/account/summary": {
      "get": {
        "tags": [
          "Account Services"
        ],
        "summary": "GET a Summary of Account Details",
        "description": "Get account related details for a Constant Contact user account. Use the `extra_fields` query parameter to include the `company_logo` and/or `physical_address` details in the response body. For more details, see [Get Account Summary Details](/api_guide/account_details_get.html).",
        "operationId": "getAccountById",
        "security": [
          {
            "oauth2_implicit": [
              "account_read"
            ]
          },
          {
            "oauth2_access_code": [
              "account_read"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:read"
        ],
        "x-sdk-methodName": "getAccountDetails"
      },
      "put": {
        "tags": [
          "Account Services"
        ],
        "summary": "PUT (update) Account Details",
        "description": "Use this method to update account details for a Constant Contact account, such as the email address or phone number. This PUT method provides a partial update where only valid properties that you include in the request body are updated and excluded properties are not overwritten. For more details, see [Put (update) Account Summary Details](/api_guide/account_details_put.html).",
        "operationId": "putCustomerById",
        "security": [
          {
            "oauth2_implicit": [
              "account_update"
            ]
          },
          {
            "oauth2_access_code": [
              "account_update"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:update"
        ],
        "x-sdk-methodName": "updateAccount"
      }
    },
    "/account/summary/physical_address": {
      "get": {
        "tags": [
          "Account Services"
        ],
        "summary": "GET the Physical Address for the Account",
        "description": "Use this method to get the address where the account's organization physically resides. The physical address is required to send emails and displays on the footer of every email that is sent from the account.",
        "operationId": "getPhysicalAddress",
        "security": [
          {
            "oauth2_implicit": [
              "account_read"
            ]
          },
          {
            "oauth2_access_code": [
              "account_read"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:read"
        ],
        "x-sdk-methodName": "getAccountPhysicalAddress"
      },
      "put": {
        "tags": [
          "Account Services"
        ],
        "summary": "PUT (update) the Physical Address for an Account",
        "description": "Use this method to update the organization's physical address for the Constant Contact user account. The physical address is required to send emails and displays on the footer of every email that is sent from the account. To get the current physical address, make a GET call to `/account/summary/physical_address`. The country (<code>country_code</code>) where the account organization resides determines whether you use the <code>state_code</code> to specify United States (<[...]",
        "operationId": "putPhysicalAddress",
        "security": [
          {
            "oauth2_implicit": [
              "account_update"
            ]
          },
          {
            "oauth2_access_code": [
              "account_update"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:update"
        ],
        "x-sdk-methodName": "updateAccountPhysicalAddress"
      },
      "post": {
        "tags": [
          "Account Services"
        ],
        "summary": "POST the Physical Address for the Account",
        "description": "Use this method to add the address where the account's organization physically resides. The physical address is required to send emails and displays on the footer of every email that is sent from the account. The country (<code>country_code</code>) where the account organization resides determines whether you use the <code>state_code</code> to specify United States (<code>US</code>) and Canada (<code>CA</code>) addresses, or use the <code>state_name</code> to specify all [...]",
        "operationId": "addPhysicalAddress",
        "security": [
          {
            "oauth2_implicit": [
              "account_update"
            ]
          },
          {
            "oauth2_access_code": [
              "account_update"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:update"
        ],
        "x-ctctmcp-allow": true
      }
    },
    "/account/emails": {
      "get": {
        "tags": [
          "Account Services"
        ],
        "summary": "GET a Collection of Account Email Addresses",
        "description": "Use this method to return a collection of email addresses for the account associated with your access token. When you <a href=\"https://v3.developer.constantcontact.com/api_reference/index.html#!/Email_Campaigns/createEmailCampaignUsingPOST\" target=\"_blank\">Create an Email Campaign<a/>, you must use an account email address with a `CONFIRMED` status in the email campaign `from_email` and `reply_to_email` headers.\n      \n\nUse the query parameters to filter results. Y[...]",
        "operationId": "retrieveEmailAddresses",
        "security": [
          {
            "oauth2_implicit": [
              "account_read"
            ]
          },
          {
            "oauth2_access_code": [
              "account_read"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:read"
        ],
        "x-sdk-methodName": "getAllAccountEmailAddresses"
      },
      "post": {
        "tags": [
          "Account Services"
        ],
        "summary": "POST Add an Account Email Address",
        "description": "Use this method to add a new email address to a Constant Contact account. If the email address you are adding already exists in the account the API will return a 409 conflict error. \n\nWhen you add a new email address to an account, Constant Contact automatically sends an email to that address with a link to confirm it. After a user clicks that link, the account email status changes from `UNCONFIRMED` to `CONFIRMED`. You can use confirmed account email addresses in the e[...]",
        "operationId": "addAccountEmailAddress",
        "security": [
          {
            "oauth2_implicit": [
              "account_update"
            ]
          },
          {
            "oauth2_access_code": [
              "account_update"
            ]
          }
        ],
        "x-authorization-privileges": [
          "account:update"
        ]
      }
    },
    "/activities": {
      "get": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "GET Activity Status Collection",
        "description": "This endpoint returns a collection of activities. Use the state query parameter to include only activities with a specific status (processing, completed, cancelled, failed, or time_out). Use the limit query parameter to define the number of activities returned per page. Learn [more](/api_guide/activity_status.html).",
        "operationId": "getActivityStatusCollection",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "getAllActivities"
      }
    },
    "/activities/{activity_id}": {
      "get": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "GET an Activity Status",
        "description": "This endpoint returns an activity status report.",
        "operationId": "getActivity",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "getActivityById"
      }
    },
    "/activities/contact_exports": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Export Contacts to a File",
        "description": "Use this method to create an activity that exports contacts and contact details to a CSV file.  You can choose to export all contacts in your account (default) or you can use parameters to filter on which contacts to export. After Constant Contact finishes processing the activity, use the `results` link in the response body to retrieve the CSV file.",
        "operationId": "postContactsExport",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createExportActivity"
      }
    },
    "/contact_exports/{file_export_id}": {
      "get": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Retrieve Exported Contacts File",
        "description": "Use this endpoint to retrieve (GET) a CSV file containing exported contacts by providing the `activity_id` of a completed CSV export activity. \n",
        "operationId": "getContactsExport",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "getCSVExportFile"
      }
    },
    "/activities/contact_delete": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Delete Contacts in Bulk",
        "description": "Use this endpoint to bulk delete contacts in an account. Contacts to delete are specified by contact_id (up to 500), or by list_id (up to 50 lists); all contacts that are members of the list_ids are deleted. Deleted contacts won\u2019t receive email from you, and they don\u2019t count as active contacts. Unlike unsubscribed contacts, deleted contacts can be added back to an account. [Learn how to revive deleted contacts](/api_guide/contacts_delete.html#revive).",
        "operationId": "postContactDelete",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createDeleteActivity"
      }
    },
    "/activities/contacts_file_import": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Import Contacts using a CSV File",
        "description": "This multipart method creates an asynchronous background job that adds or updates contacts by importing a CSV file containing contact information. Do not use a Content-Type header value with this method.\n\nImporting a new contact email address automatically sets the contact's `permission_to_send` property as `implicit` and the `opt_in_source` property as `Account`. Importing an existing contact only updates the contact properties you include in the request.\nImporting co[...]",
        "operationId": "contactsCSVImport",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createCSVImportActivity"
      }
    },
    "/activities/contacts_json_import": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Import Contacts using a JSON Payload",
        "description": "Use this method to create an asynchronous background job that adds new contacts or updates existing contacts by importing a JSON payload. This method requires a request body that contains the contact data you are importing and the contact lists to which you want to add the imported contacts. A contact's data must include an `email` address and/or `sms_number`. The `sms_number` must be a US phone number to associate with the contact's SMS-enabled phone. Valid formats are <[...]",
        "operationId": "bulkImportContactsJSON",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-ctctmcp-allow": true,
        "x-sdk-methodName": "createImportJSONActivity"
      }
    },
    "/activities/remove_list_memberships": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Remove Contacts from Lists",
        "description": "Use this method to create an activity that removes contacts from one or more contact lists. Use the properties in the `source` object to remove specific contacts from your lists. Use the `list_ids` array to specify the target lists from which contacts are removed. Optionally, if the source is  `all_active_contacts` (billable) or `list_ids`, use the `exclude` object to exclude specific contacts from being removed from the destination lists.",
        "operationId": "postListRemoveContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createListRemoveActivity"
      }
    },
    "/activities/add_list_memberships": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Add Contacts to Lists",
        "description": "Use this method to create an activity that adds contacts to one or more lists. Each contact can be a member of up to 50 lists. Use the properties in the `source` object to specify the contacts you want to add to lists. Use the `list_ids` array to specify which lists you want to add your source contacts to.",
        "operationId": "postListAddContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createListAddActivity"
      }
    },
    "/activities/list_delete": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Delete Contact Lists",
        "description": "Use this endpoint to delete up to 100 contact lists in an account. ",
        "operationId": "postListDelete",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createListDeleteActivity"
      }
    },
    "/activities/contacts_taggings_remove": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Remove Tags from Contacts",
        "description": "Use this method to create an asynchronous activity that removes one or more tags from all contacts meeting your contact filtering criteria. Filtering criteria must include the `source` type used to identify contacts from which the specified tags (`tag_id`) are removed.\nSource types are mutually exclusive. If the specified source is either `all_active_contacts` or `list_ids`, you can optionally choose to `exclude` specified contacts by `contact_id`. Use the activity link [...]",
        "operationId": "postTagRemoveContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createTagRemoveActivity"
      }
    },
    "/activities/contacts_taggings_add": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Add Tags to Contacts",
        "description": "Use this method to create an asynchronous activity that adds one or more tags to all contacts meeting your contact filtering criteria. Use the `source` type to identify contacts from which the specified tags (`tag_id`) are added.\nSource criteria are mutually exclusive. If the source is `all_active_contacts` or `list_ids`, you can optionally choose to `exclude` contacts by `contact_id`. Use the activity link in the results to check the status of your request.\nFor more us[...]",
        "operationId": "postTagAddContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createTagAddContactActivity"
      }
    },
    "/activities/contacts_tags_delete": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Delete Tags",
        "description": "Use this method to create an asynchronous activity that deletes up to 500 tags. Deleted tags are automatically removed from tagged contacts. Use the `tag_ids` array of string values in the request body to specify which tags to delete.",
        "operationId": "postTagDelete",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createTagDeleteActivity"
      }
    },
    "/activities/custom_fields_delete": {
      "post": {
        "tags": [
          "Bulk Activities"
        ],
        "summary": "Delete Custom Fields",
        "description": "Use this endpoint to delete up to 100 custom fields for an account. ",
        "operationId": "postCustomFieldDelete",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "GET a collection of events.",
        "description": "Retrieve a collection of events with event details.",
        "operationId": "findEvents",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ]
      }
    },
    "/events/default": {
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "POST (create) a new event.",
        "description": "Creates a new event with default settings, registration form, and landing page. The event will be created in DRAFT status.",
        "operationId": "addDefaultEvent",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "createEvent"
      }
    },
    "/events/{event_id}": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "GET details for a single event.",
        "description": "Specify the `event_id` path parameter to retrieve the event's details.",
        "operationId": "getEvent_2",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ]
      },
      "patch": {
        "tags": [
          "Events"
        ],
        "summary": "PATCH (update) an event.",
        "description": "Partially updates an event with the provided fields. Only the specified fields will be updated. This endpoint only works for events in DRAFT or ACTIVE status. Events in COMPLETE, CANCELED, or DELETED status cannot be updated.",
        "operationId": "patchEvent",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "updateEvent"
      }
    },
    "/events/{event_id}/copy": {
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "POST (copy) an existing event.",
        "description": "Creates a deep copy of an existing event with all its settings, registration forms, and landing pages. The copied event is created in DRAFT status. Events in DRAFT, ACTIVE, COMPLETE, or CANCELED status can be copied. DELETED events cannot be copied.",
        "operationId": "copyEvent",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "copyEvent"
      }
    },
    "/events/{event_id}/tracks/{track_id}/registrations/{registration_id}": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get registration details for an event.",
        "description": "Use the `event_id`, `registration_id`, and `track_id` path parameters to get registration details.",
        "operationId": "getRegistrationInfo",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ]
      }
    },
    "/events/{event_id}/tracks/{track_id}/registrations": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Get a list of registrations for an event.",
        "description": "Use the `event_id` and `track_id` path parameters to get a list of registrations for an event. Use optional query parameters to limit the number of results returned per page, the sort order, or to filter results by specific criteria; such as registration `status`.",
        "operationId": "findRegistrationsUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ]
      }
    },
    "/segments": {
      "get": {
        "tags": [
          "Segments"
        ],
        "summary": "GET all Segments",
        "description": "Use this method to get a list of all segments associated with the account. You can sort segment results and limit the number of segments that display per page. Deleted segments are excluded from the results. For more use case information, see [Get All Segments](/api_guide/segment_get_all.html) in the API guide.",
        "operationId": "getAccountSegments",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:read"
        ],
        "x-sdk-methodName": "getAllSegments"
      },
      "post": {
        "tags": [
          "Segments"
        ],
        "summary": "POST (create) a Segment",
        "description": "Use this method to create a new segment. You create segments to target a subset of your contacts that meet your specific criteria for a marketing campaign. The segment `name` must be unique. The `segment_criteria` requires single-string escaped JSON. Constant Contact uses the contact data that you specify in the `segment_criteria` to evaluate and identify the contacts you want to target. Contact data can be grouped from different data sources, including:\n\n  -  **`tracki[...]",
        "operationId": "createSegment",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ]
      }
    },
    "/segments/{segment_id}": {
      "get": {
        "tags": [
          "Segments"
        ],
        "summary": "GET a Segment's Details",
        "description": "Use this method to get details about a segment, including the segment criteria. If you know the `segment_id` You can also use this method to get details about a deleted segment. For more use case information, see [Get a Segment's Details](/api_guide/segment_get.html) in the API guide.",
        "operationId": "getSegmentDetail",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:read"
        ],
        "x-sdk-methodName": "getSegmentById"
      },
      "put": {
        "tags": [
          "Segments"
        ],
        "summary": "PUT (update) a Segment",
        "description": "Use this method to update an existing segment's name (`name`) and/or contact selection criteria (`segment_criteria`). You must specify both the `name` and the `segment_criteria` in the request body, even if you don't plan to update both. The segment's name must be unique and the JSON must be valid (requires single-string escaped JSON). To avoid returning a 400 error response, when specifying the `segment_criteria` do not request more than 500 email campaigns or a date ran[...]",
        "operationId": "updateSegment",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ]
      },
      "delete": {
        "tags": [
          "Segments"
        ],
        "summary": "DELETE a Segment",
        "description": "Use this method to delete a segment from your account. Before deleting a segment, verify that the segment is not associated with a scheduled campaign.\n\nDeleted segments do not display in the results when using the `GET /segments` endpoint. If you know the `segment_id`, you can use the `GET /segments/{segment_id}` endpoint to view the deleted segment's details. A segment's details are preserved for external reference purposes, such as displaying the segment name in a cam[...]",
        "operationId": "deleteSegment",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ]
      }
    },
    "/segments/{segment_id}/name": {
      "patch": {
        "tags": [
          "Segments"
        ],
        "summary": "PATCH (rename) a Segment",
        "description": "Use this method to update an existing segment `name` with a new unique name in the request body. For more use case information, see [Rename a Segment](/api_guide/segment_rename.html) in the API guide.",
        "operationId": "updateSegmentName",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ]
      }
    },
    "/contacts/{contact_id}": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "GET a Contact",
        "description": "This endpoint GETs a specific contact resource (contact_id). Use the `include` query parameter to add any of the available contact sub-resources to the response payload.",
        "operationId": "getContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ],
        "x-sdk-methodName": "getContactById"
      },
      "put": {
        "tags": [
          "Contacts"
        ],
        "summary": "PUT (update) a Contact",
        "description": "The PUT method updates an existing contact. You must include the `update_source` property in the PUT request payload. To restore  a deleted contact you must specify the `update_source` as `Account`. When updating any resource using PUT, all properties are updated, overwriting all previous values. Any properties left blank or not included in the request are overwritten with null value - however this does not apply to contact subresources. \n\nAdd or change any of the subre[...]",
        "operationId": "putContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "updateContact"
      },
      "delete": {
        "tags": [
          "Contacts"
        ],
        "summary": "DELETE a Contact",
        "description": "Deletes the contact identified by the contact_id path parameter. Deleted contacts won't receive email from you, and they don't count as active contacts. Unlike unsubscribed contacts, deleted contacts can be revived, or added back to an account. Learn how to [revive deleted contacts](/api_guide/contacts_delete.html#revive).",
        "operationId": "deleteContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contacts": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "GET Contacts Collection",
        "description": "Use this method to return a collection of contacts. Use the query parameters to search for contacts that match specific contact properties and sub-resource properties as criteria. For example, you can search using the contact's `email` address, `lists` memberships, and by the date range that a contact was created or updated. Use the `limit` query parameter to limit the number of results returned per page. Use the `include` query parameter to include contact sub-resources [...]",
        "operationId": "getContacts",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ],
        "x-sdk-methodName": "getAllContacts"
      },
      "post": {
        "tags": [
          "Contacts"
        ],
        "summary": "POST (create) a Contact",
        "description": "\nCreates a new contact resource. You must include the `create_source` property and at least one of the following properties: `first_name`, `last_name`, a unique `email_address` (specified using the `EmailAddress` object), or the `sms_channel` property (specified using the `ContactSmsChannel` object).\n\n<div class=\"Msg\"><p class=\"note-text\">If `email_address` is specified: **Only use this method when a contact gives you their explicit permission to send them an email[...]",
        "operationId": "createContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contacts/sign_up_form": {
      "post": {
        "tags": [
          "Contacts"
        ],
        "summary": "Create or Update a Contact",
        "description": "Use this method to create a new contact or update an existing contact. In the request body, this method requires including the `list_memberships` array as well as either the contact's `email_address` string or `sms_channel` object which includes the contact's SMS number. The information you specify determines if a new contact is either created (the email address or SMS number does not already exist in the account), or if an existing contact is updated (the email address o[...]",
        "operationId": "createOrUpdateContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contacts/contact_id_xrefs": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "GET a collection of V2 and V3 API contact IDs",
        "description": "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this endpoint to migrate your locally stored V2 contact ids to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>\n\nThis GET call retrieves a collection of cross-referenced contact sequence IDs (`id` used in the V2 API) and UUIDs (`contact_id` used in th[...]",
        "operationId": "getContactIdXrefs",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ]
      }
    },
    "/contact_custom_fields/{custom_field_id}": {
      "get": {
        "tags": [
          "Contacts Custom Fields"
        ],
        "summary": "GET a custom_field",
        "description": "Get details for a specified custom field.",
        "operationId": "getCustomField",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ]
      },
      "put": {
        "tags": [
          "Contacts Custom Fields"
        ],
        "summary": "Update a custom field.",
        "description": "Update an existing custom field.",
        "operationId": "putCustomField",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "updateCustomField"
      },
      "delete": {
        "tags": [
          "Contacts Custom Fields"
        ],
        "summary": "DELETE a custom_field",
        "description": "Delete a custom field from the user's account.",
        "operationId": "deleteCustomField",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contact_custom_fields": {
      "get": {
        "tags": [
          "Contacts Custom Fields"
        ],
        "summary": "GET custom_fields Collection",
        "description": "Get all custom fields defined in the user's account.\n<div class=\"Msg\"><p class=\"note-text\">This method does not currently support filtering results using the custom field update date.</p></div>",
        "operationId": "getCustomFields",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ],
        "x-sdk-methodName": "getAllCustomFields"
      },
      "post": {
        "tags": [
          "Contacts Custom Fields"
        ],
        "summary": "POST (create) a custom_field",
        "description": "Custom fields are extra data fields you create to store additional information about your contacts, such as preferences, membership levels, and interests. Use custom fields to organize contacts, send personalized email campaigns, and to identify a targeted audience for a specific campaign. Custom fields types include text, number, date, drop-down lists, radio buttons, and checkboxes. A user can configure up to 100 `custom_fields` in their account.",
        "operationId": "postCustomFields",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ],
        "x-sdk-methodName": "createCustomFields"
      }
    },
    "/contact_lists/{list_id}": {
      "get": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "GET a List",
        "description": "Use this method to get details about a specific contact list (`list_id`).",
        "operationId": "getList",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:read"
        ]
      },
      "put": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "PUT (update) a List",
        "description": "Updates an existing contact list resource, specified by `list_id`",
        "operationId": "putList",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ],
        "x-sdk-methodName": "updateList"
      },
      "delete": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "DELETE a List",
        "description": "Deletes the specified contact list and its membership. DELETE List requests are processed asynchronously, and you can track the status of the request by making a GET call to the URI shown in the `_links` property in the response.",
        "operationId": "deleteListActivity",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ],
        "x-sdk-methodName": "deleteList"
      }
    },
    "/contact_lists": {
      "get": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "GET Lists Collection",
        "description": "Use this method to return details about all contact lists for the account.\n<div class=\"Msg\"><p class=\"note-text\">This method does not currently support filtering results using the contact list update date.</p></div>",
        "operationId": "getLists",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:read"
        ],
        "x-sdk-methodName": "getAllLists"
      },
      "post": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "POST (create) a List",
        "description": "Create a new contact list resource",
        "operationId": "createList",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:write"
        ],
        "x-ctctmcp-allow": true
      }
    },
    "/contact_lists/list_id_xrefs": {
      "get": {
        "tags": [
          "Contact Lists"
        ],
        "summary": "GET a collection of V2 and V3 API List IDs",
        "description": "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this endpoint to migrate your locally stored V2 contact list data to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>\n\nThis GET call retrieves a collection of cross-referenced list sequence IDs (`id` used in the V2 API) and UUIDs (`list_id` used in th[...]",
        "operationId": "getListIdXrefs",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:lists:read"
        ]
      }
    },
    "/contacts/sms_engagement_history/{contact_id}": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "GET SMS Engagement History for a Contact",
        "description": "Use this method to return SMS engagement details for a contact, such as SMS consent and advertising frequency details.",
        "operationId": "getSmsEngagementHistory",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ]
      }
    },
    "/contacts/counts": {
      "get": {
        "tags": [
          "Contacts"
        ],
        "summary": "GET Contact Consent Counts",
        "description": "Use to get the total contacts count for the account and the total contact-consent counts for each consent state. Optionally, to include the total number of contacts that subscribed within the last 30 days in the results, use `new_subscribers` in the `include` query parameter. To optimize open rates, reduce spam reports, and help grow your business,  you must value your contact's consent to receive or to not receive your emails.",
        "operationId": "countContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ],
        "x-sdk-methodName": "getContactCounts"
      }
    },
    "/contacts/resubscribe/{contact_id}": {
      "put": {
        "tags": [
          "Contacts"
        ],
        "summary": "PUT Resubscribe a Contact",
        "description": "Use this endpoint to send a confirmation resubscribe email to a contact in order to get their confirmation to resubscribe. This endpoint also adds the resubscribed contact to the contact lists you specify in the request body. You can only send a resubscribe email to the unsubscribed contact once. The contact is not resubscribed until after you receive their confirmation. ",
        "operationId": "resubscribeContact",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contact_tags/{tag_id}": {
      "get": {
        "tags": [
          "Contact Tags"
        ],
        "summary": "GET Tag Details",
        "description": "Use this method to get tag details for a specified `tag_id`. Use the `include_count` query parameter to include or exclude the total number of contacts to which this tag is assigned. To learn more, see  [Get a Tag's Details](/api_guide/tags_get_single.html).",
        "operationId": "getTag",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ],
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ]
      },
      "put": {
        "tags": [
          "Contact Tags"
        ],
        "summary": "PUT (Update) a Tag",
        "description": "Use this method to rename an existing tag to a new unique tag name (`name`). The maximum length is 255 characters. The `tag_source` value cannot be updated using this method. You can set the `tag_source` value using the `POST contact_tags method`. [Learn more](/api_guide/tags_update.html)",
        "operationId": "putTag",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      },
      "delete": {
        "tags": [
          "Contact Tags"
        ],
        "summary": "DELETE a Tag",
        "description": "Use this method to create an activity used to un-assign a tag from all assigned contacts and delete the tag. This is an asynchronous activity. To view activity details for the delete request, use the href link returned in the response. [Learn more](/api_guide/tags_delete.html).",
        "operationId": "deleteTag",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ],
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/contact_tags": {
      "get": {
        "tags": [
          "Contact Tags"
        ],
        "summary": "GET Details for All Tags",
        "description": "Use this endpoint to get details for all tags in your account. Use the <code>include_count</code> query parameter to include the total number of contacts assigned each tag. Use the <code>limit</code> query parameter to limit the number of tag results returned per page. To get the next page of results, copy the <code>cursor={the cursor ID}</code> from the resulting href link and add it (<code>&</code>) to the URL. For example:\n\n<p><code>/v3/contact_tags?limit=1&cursor=</[...]",
        "operationId": "getTags",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ],
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:read"
        ],
        "x-sdk-methodName": "getAllTags"
      },
      "post": {
        "tags": [
          "Contact Tags"
        ],
        "summary": "POST (Create) a Tag",
        "description": "Use this method to create a new tag. The tag `name` is required and must be unique and can include most common keyboard symbols. Optionally, when creating a new tag you can specify the source (`tag_source`) used to identify the contacts to tag in the request body. [Learn more](/api_guide/tags_create.html).",
        "operationId": "postTag",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "contacts:write"
        ]
      }
    },
    "/emails": {
      "get": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "GET a Collection of Email Campaigns",
        "description": "Use this method to list and get details about your email campaigns. By default, this method returns all email campaigns for the user account including deleted email campaigns. To get email campaigns within a date-range, use the `after_date` and `before_date` query parameters.\n\nThis endpoint does not return campaign activity details for each email campaign in the collection. To get email campaign activity details for a single email campaign, use the GET `/emails/{campaig[...]",
        "operationId": "retrieveEmailCampaignsUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getAllEmailCampaigns"
      },
      "post": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "POST (Create) a New Email Campaign",
        "description": "Use this method to create a new email campaign. This method also creates new `primary_email` and `permalink` email campaign activities and associates them with the new email campaign.\n\nThe request body must contain the `name` property and the `email_campaign_activities` array. The `name` must be unique. The `email_campaign_activities` array contains the main content of your email campaign and must include `format_type`, `from_name`, `from_email`, `reply_to_email`, `subj[...]",
        "operationId": "createEmailCampaignUsingPOST",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "createEmailCampaign",
        "x-ctctmcp-allow": true
      }
    },
    "/emails/{campaign_id}": {
      "get": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "GET Details About a Single Email Campaign",
        "description": "Use this method to get details about a single email campaign and campaign related activities. Details include the email campaign name, current status, create date, last update date, and a list of campaign activities; including the `campaign_activity_id` and `role`.",
        "operationId": "retrieveEmailCampaignUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignById"
      },
      "delete": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "DELETE an Email Campaign",
        "description": "Use this method to delete an email campaign and the email campaign activities associated with the email campaign. You cannot delete an email campaign when it has a `Scheduled` status.\n\nConstant Contact users can restore deleted email campaigns using the UI.\n",
        "operationId": "removeEmailCampaignUsingDELETE",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:delete"
        ],
        "x-sdk-methodName": "deleteEmailCampaign"
      },
      "patch": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "PATCH (Update) an Email Campaign Name",
        "description": "Use this method to rename an email campaign. The name is not visible to contacts. The name must be unique and cannot exceed 80 characters. You cannot rename email campaigns that have a `Removed` status.",
        "operationId": "renameEmailCampaignUsingPATCH",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "patchEmailCampaignName"
      }
    },
    "/emails/campaign_id_xrefs": {
      "get": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "GET a Collection of V2 and V3 API Email Campaign Identifiers",
        "description": "<div class=\"Msg Msg--warning\"><p class=\"note-text\">Use this endpoint to migrate your locally stored V2 email campaign data to the new V3 format. Developers are expected to use this endpoint sparingly. This endpoint is NOT intended for regular or repeated use. Constant Contact will eventually deprecate and remove this endpoint.</p></div>\n\nUse this method to migrate your local V2 API email data to the V3 API format. For each value that you provide in the `v2_email_cam[...]",
        "operationId": "retrieveXrefMappingsUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignXrefs"
      }
    },
    "/emails/activities/{campaign_activity_id}": {
      "get": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "GET a Single Email Campaign Activity",
        "description": "Use this method to return a specific email campaign activity. Each email campaign activity contains the email content, metadata, and styling information of an email. Email campaign activities can also contain either contact lists or segments. Constant Contact uses this information to determine who to send the email campaign activity to when you schedule it. You cannot get email campaign activities that have a `REMOVED` status.\n",
        "operationId": "retrieveEmailCampaignActivityUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignActivity"
      },
      "put": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "PUT (Update) An Email Campaign Activity",
        "description": "Use this method to update an email campaign activity by including the complete email campaign activity with your changes in the request body. The request body requires the `from_name`, `from_email`, `reply_to_email`, and `subject` properties.\n\nYou can only update email campaign activities that have the `primary_email` role and that are in `DRAFT` or `Done` status.\nWhen you use a PUT method to update a resource, the V3 API overwrites any properties that are missing in t[...]",
        "operationId": "updateEmailCampaignActivityUsingPUT",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "updateEmailCampaignActivity",
        "x-ctctmcp-allow": true
      }
    },
    "/emails/activities/{campaign_activity_id}/schedules": {
      "get": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "GET an Email Campaign Activity Schedule",
        "description": "Use this method to return the current schedule for an email campaign activity. This schedule contains the date that Constant Contact will send the email campaign activity to contacts. If the email campaign activity is not in `SCHEDULED` status, this method returns an empty array and a 200 response code.",
        "operationId": "retrieveEmailSchedulesUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignActivitySchedule"
      },
      "post": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "POST (Create) an Email Campaign Activity Schedule",
        "description": "Use this method to send an email campaign activity to contacts either immediately or on a specific date. To send the email campaign activity immediately, specify `0` for the `scheduled_date` request property (results return an empty array). To send the email campaign activity on a specific date, specify the date using the `scheduled_date` request property (results return the scheduled date in an array).  \n\nBefore you schedule an email campaign activity, you must update [...]",
        "operationId": "scheduleEmailCampaignActivityUsingPOST",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:send"
        ],
        "x-ctctmcp-allow": true,
        "x-sdk-methodName": "scheduleEmailCampaignActivity"
      },
      "delete": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "DELETE an Email Campaign Activity Schedule",
        "description": "Use this method to unschedule an email campaign activity by deleting the schedule. You can only unschedule email campaign activities that are in `SCHEDULED` status. Unscheduling reverts the email campaign activity to the status prior to `SCHEDULED`.",
        "operationId": "unscheduleEmailCampaignActivityUsingDELETE",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:send"
        ],
        "x-sdk-methodName": "unscheduleEmailCampaignActivity"
      }
    },
    "/emails/activities/{campaign_activity_id}/tests": {
      "post": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "POST Test Send an Email Campaign Activity",
        "description": "Use this method to send a test email to specific email addresses. Test emails allow you to verify how the email campaign activity will look before you send it to contacts. This method uses the `email_addresses` array in the request body to determine the recipients of the test email. The test email does not process any dynamic content in the email campaign activity. Dynamic content includes contact and custom field variables.\n\nYou can send up to 50 test emails each day. [...]",
        "operationId": "testSendCampaignActivityUsingPOST",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:send"
        ],
        "x-sdk-methodName": "testSendEmailCampaignActivity"
      }
    },
    "/emails/activities/{campaign_activity_id}/previews": {
      "get": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "GET the HTML Preview of an Email Campaign Activity",
        "description": "Use this method to get the HTML preview of an email campaign activity. The HTML preview allows you to verify how the email campaign activity will look before you send it to contacts.\n\nCustom code emails (`format_type` 5) use the Constant Contact account owner's contact information to process contact, custom field, and account variables in the preview.\n\nThis method returns the HTML preview encoded as a JSON string. You will need to decode the string before you can use [...]",
        "operationId": "retrieveEmailCampaignActivityPreviewUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignActivityPreview"
      }
    },
    "/emails/activities/{campaign_activity_id}/send_history": {
      "get": {
        "tags": [
          "Email Scheduling"
        ],
        "summary": "GET the Send History of an Email Campaign Activity",
        "description": "Use this method to return the send history of an email campaign activity. This method returns the send history as an array containing an object for each time you sent a specific email campaign activity to contacts. \n\nEach send history object contains the email campaign activity send date, the number of contacts it was sent to, and the contact lists or segments used to send it. Each send history object also includes if the send attempt completed or encountered an error, [...]",
        "operationId": "retrieveEmailSendHistoryUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getEmailCampaignActivitySendHistory"
      }
    },
    "/emails/activities/{campaign_activity_id}/non_opener_resends": {
      "get": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "GET Details for a Resend to Non-openers Campaign Activity",
        "description": "Get details about a resend to non-openers campaign activity. If resend activity does not exist for the specified `campaign_activity_id`, an empty list is returned in the results. You can only create one resend activity per email campaign.",
        "operationId": "retrieveResendToNonOpenersUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getResendEmailCampaign"
      },
      "post": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "POST a Resend to Non-openers Campaign Activity",
        "description": "Use this POST method to resend a primary campaign activity to contacts that did not open a campaign activity that has a current `status` of `Draft`, `Scheduled`, or `Done`. You can only create one resend activity per email campaign.\n \n After an email campaign activity is sent to contacts, Constant Contact waits the specified number of `delay_days` or `delay_minutes` (properties are mutually exclusive) before resending to non-openers. If you set both `delay_days` or `del[...]",
        "operationId": "createResendToNonOpenersUsingPOST",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:send"
        ],
        "x-sdk-methodName": "createResendEmailCampaign"
      }
    },
    "/emails/activities/{campaign_activity_id}/non_opener_resends/{resend_request_id}": {
      "delete": {
        "tags": [
          "Email Campaigns"
        ],
        "summary": "DELETE a Resend to Non Openers Activity",
        "description": "Use this `DELETE` method to delete (unschedule) a resend to non openers activity.",
        "operationId": "deleteResendToNonOpenersUsingDELETE",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:send"
        ],
        "x-sdk-methodName": "deleteResendEmailCampaign"
      }
    },
    "/emails/activities/{campaign_activity_id}/abtest": {
      "get": {
        "tags": [
          "Email Campaigns AB Tests"
        ],
        "summary": "GET A/B Test Details for an Email Campaign Activity",
        "description": "Use this method to get A/B test details for a primary email campaign activity, such as the alternate email subject line, the contact test percentage size, and the number of hours to wait to determine the winning subject line to use. Currently, A/B tests support subject line only.",
        "operationId": "retrieveEmailCampaignABTestUsingGET",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:read"
        ],
        "x-sdk-methodName": "getABTestEmailCampaign"
      },
      "post": {
        "tags": [
          "Email Campaigns AB Tests"
        ],
        "summary": "POST (Create) an A/B Test for an Email Campaign Activity",
        "description": "Use this method to create a new A/B test for a primary email campaign activity. You must specify an alternative subject line, the percentage of contact to use for the A/B test, and the number of hours to wait after the A/B test is sent before determining the winning subject line. To create an A/B test, the campaign must have a `current_status` of `DRAFT`. When you create an A/B test, the `type` changes from Newsletter (code= `10`) to A/B Test (code= `57`).",
        "operationId": "createEmailCampaignABTestUsingPOST",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "createABTestEmailCampaign"
      },
      "delete": {
        "tags": [
          "Email Campaigns AB Tests"
        ],
        "summary": "DELETE an A/B Test for an Email Campaign Activity",
        "description": "Deletes an A/B Test on an primary email campaign activity. You can only delete A/B tests that have a `current_status` of `Draft`. Deleting an A/B tests reverts the email campaign activity `type` from A/B Test (code= `57`) back to NewsLetter (code= `10`). Constant Contact uses the original subject line, rather than the alternate A/B test subject line, when an A/B test is deleted.",
        "operationId": "deleteEmailCampaignABTestUsingDELETE",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "campaign:write"
        ],
        "x-sdk-methodName": "deleteABTestEmailCampaign"
      }
    },
    "/reports/contact_reports/{contact_id}/activity_details": {
      "get": {
        "tags": [
          "Contacts Reporting"
        ],
        "summary": "GET Contact Activity Details",
        "description": "<p>Gets the tracking activity data for a single contact, sorted in descending activity date order.</p> <p>You must chose either the `tracking_activities_list` query parameter and or the `tracking_activity_type` query parameter to specify one or more tracking activity types In the request. The `tracking_activities_list`  and `tracking_activities_type` query parameters are mutually exclusive.</p>\n      <table><tr><td colspan='2'>Valid tracking activity types</td></tr>\n   [...]",
        "operationId": "getContactTracking",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getContactTrackingReport"
      }
    },
    "/reports/contact_reports/{contact_id}/open_and_click_rates": {
      "get": {
        "tags": [
          "Contacts Reporting"
        ],
        "summary": "GET Average Open and Click Rates",
        "description": "<p>Gets the average open and click rate for a given account and contact.<p>Looks at all tracking activities for bulk emails from a given contact over the given date range. Range cannot exceed 5 years.</p><p>Returns the rates and the number of campaign activities that were included in the calculation.</p><p>If no activities fall into the given date range, all rates will return 0 and the number of included activities will be 0.</p>",
        "operationId": "getContactOpenClickRate",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getContactOpenClickRateReport"
      }
    },
    "/reports/contact_reports/{contact_id}/activity_summary": {
      "get": {
        "tags": [
          "Contacts Reporting"
        ],
        "summary": "GET Contact Action Summary",
        "description": "Get a list of the recent emails (aka, campaign activities) sent to a specific contact and a summary of the actions the contact took on that email for the most recent 200 campaigns.",
        "operationId": "getContactTrackingCount",
        "security": [
          {
            "oauth2_implicit": [
              "contact_data"
            ]
          },
          {
            "oauth2_access_code": [
              "contact_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getContactTrackingCountReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/links": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Links Report",
        "description": "Use this method to return link details, including the number of unique contacts that clicked each link in an email campaign activity, and the type of action associated with clicking each link. To include link details for links that were not clicked, set the `no_clicks` query parameter to `true`.\n\nYou can return reporting data for `primary_email` and `resend` role email campaign activities. For more use case information, see [Get an Email Links Report](/api_guide/email_l[...]",
        "operationId": "getCampaignActivityLinkStats",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getCampaignActivityLinkReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/sends": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Sends Report",
        "description": "Use this method to get each contact that was sent a specific email campaign activity. This sends report includes general contact data such as the date and time that the email campaign activity was sent to a contact's email address, the contact's first and last name, and unique ID. This report lists the most recent activity first. For more use case information, see [Get an Sends report for an Email Campaign Activity](/api_guide/email_summary_sends_report.html) in the API g[...]",
        "operationId": "getSends",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getEmailSendsReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/opens": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Opens Report",
        "description": "Use this method to get each time a contact opened a specific email campaign activity. This report includes general contact information such as the contact's email address and unique ID, the date and time they opened the email campaign activity, and the type of device they used to open it. This report lists the most recent activity first. For more use case information, see [Get an Opens report for an Email Campaign Activity](/api_guide/email_summary_opens_report.html) in t[...]",
        "operationId": "getOpens",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getEmailOpensReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/unique_opens": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Unique Opens Report",
        "description": "Use this method to get a unique opens report that provides details about the last time that each contact opened the specified email campaign activity. This report includes general contact information such as the contact's email address and unique ID, the date and time they opened the email campaign activity, and the type of device they used to open it. This report lists the most recent activity first. For more use case information, see [Get an Unique Opens Report for an E[...]",
        "operationId": "getUniqueOpens",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getUniqueOpensReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/didnotopens": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Did Not Opens Report",
        "description": "Use this method to get a report listing each contact that was sent, but did not open the specified email campaign activity. This report lists contact information such as the contact's email address and unique ID, and the date and time that the email campaign activity was sent. This report lists the most recent activity first. For more use case information, see [Get a Did Not Opens Report for an Email Campaign Activity](/api_guide/email_summary_non_opens_report.html) in th[...]",
        "operationId": "getDidNotOpens",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getDidNotOpensReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/clicks": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Clicks Report",
        "description": "Use this method to get each time a contact clicked a link, the click date and time, and the device type they used. Use the `url_id` query parameter to get a clicks report for a specific link URL. Clicks report data is sorted with most recent activity listed first.",
        "operationId": "getClicks",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getClicksReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/forwards": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Forwards Report",
        "description": "Use this method to get a report listing each time a contact forwarded the email campaign activity using the forwarding link in the email footer. The report includes general contact information, such as the contact's email address and unique ID, and the date and time that the email campaign activity was forwarded. Forwards report data is sorted with the most recent activity listed first. For more use case information, see [Get an Email Forwards Report](/api_guide/email_sum[...]",
        "operationId": "getForwards",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getForwardsReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/optouts": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Opt-outs Report",
        "description": "Use this method to get a report listing each contact that clicked the unsubscribe link in the email campaign activity to opt-out from receiving emails sent from your Constant Contact account. This report includes contact information, such as the contact's email address, unique ID, and the opt-out date and time. Opt-out report data is sorted with the most recent activity listed first. For more use case information, see [Get an Email Opt-outs Report](/api_guide/email_summar[...]",
        "operationId": "getOptouts",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getOptoutsReport"
      }
    },
    "/reports/email_reports/{campaign_activity_id}/tracking/bounces": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Bounces Report",
        "description": "Use this method to get a report listing contact bounce data for the specified email campaign activity. This report lists the most recent bounce data first and includes contact information, such as the contact's email address, unique ID, and the email bounce date and time.\nUse the <code>bounce_code</code> query parameter to limit the type of bounce data to return.\n\nFor more use case information, see [Get a Bounces Report for an Email Campaign Activity](/api_guide/email_[...]",
        "operationId": "getBounces",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getBouncesReport"
      }
    },
    "/reports/summary_reports/email_campaign_summaries": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Campaigns Summary Report",
        "description": "Use this method to get aggregate email campaign statistics for up to five hundred email campaigns. The response results include the total number of times that each contact uniquely interacted with each tracked campaign activity.\n\nResults are sorted in descending order by the date that the email was last sent (<code>last_sent_date</code>). Use the <code>limit</code> query parameter to limit the number of email campaign summary reports listed on each page.\n\n\n\n For mor[...]",
        "operationId": "getAllBulkEmailCampaignSummaries",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getEmailCampaignReport"
      }
    },
    "/reports/stats/email_campaigns/{campaign_ids}": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Campaign Stats Report",
        "description": "Use this method to get email campaign performance tracking statistics for one or more campaigns, including the total number of times contacts interacted with your campaigns and how.\n\nFor each `campaign_id`, this method returns lists that include total counts (`stats`) for each type of tracked email and relevant campaign-related percentages (`percents`). It also returns the date and time at which the campaign stats were last refreshed.\nIf any specified `campaign_id` is [...]",
        "operationId": "getEmailSummary",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getEmailStatsReport"
      }
    },
    "/reports/stats/email_campaign_activities/{campaign_activity_ids}": {
      "get": {
        "tags": [
          "Email Reporting"
        ],
        "summary": "GET an Email Campaign Activity Stats Report",
        "description": "Use this method to get performance tracking statistics for up to ten email campaign activities. Statistics include the total number of times contacts interacted with your campaigns and how.\n\nFor each `campaign_activity_id`, this method returns the `campaign_id`, the total counts (`stats`) for each type of tracked email activity, and the date and time that Constant Contact last refreshed (`last_refresh_time`) the `stats`.\n\nWhen requesting statistics for multiple email [...]",
        "operationId": "getEmailCampaignActivitySummary",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ],
        "x-sdk-methodName": "getEmailCampaignActivityReport"
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_clicks": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Unique Contacts Clicks Landing Page Report",
        "description": "Use this method get details about each contact that clicked a link on a landing page campaign activity. Unique contact clicks are identified by both the `contact_id` and `url_id`. The same contact may appear more than once in the results, if they clicked more than one link on the landing page. The resulting contact data is listed with most recent activity first.",
        "operationId": "getUniqueContactClicks",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_opens": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Unique Contacts Opens Landing Page Report",
        "description": "Use this method get details about each contact that opens a link on a landing page. Contacts are uniquely identified by `contact_id`.  The resulting contact data is listed with most recent activity first.",
        "operationId": "getUniqueContactOpens",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_contact_opens": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Contacts Opens Landing Page Report",
        "description": "Use this method get contact details for each time a contact opens a link on a landing page.  The resulting contact data is listed with most recent activity first.",
        "operationId": "getContactOpens",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_updates": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Unique Contacts Updates Landing Page Report",
        "description": "Use this method to get contact details for each contact that updated their contact data from a landing page. Contacts are uniquely identified by `contact_id`.  The resulting contact data is listed with most recent activity first.",
        "operationId": "getUniqueContactUpdates",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_adds": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Unique Contacts Adds Landing Page Report",
        "description": "Use this method to get details about each contact added to the account from a specified landing page. Contacts are identified by `contact_id`. The resulting contact data is listed with most recent activity first.",
        "operationId": "getContactAdds",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/landing_pages/campaign_details/{campaign_activity_id}/p_unique_contact_sms_optins": {
      "get": {
        "tags": [
          "Landing Pages Reporting"
        ],
        "summary": "GET a Unique Contacts SMS Opt-In Landing Page Report",
        "description": "Use this method get details about unique contacts that click a link on a landing page to opt in to receiving SMS text messages. Contacts are uniquely identified by `contact_id``.  The resulting contact data is listed with most recent activity first.",
        "operationId": "getUniqueContactSMSOptIns",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/reports/summary_reports/sms_campaign_summaries": {
      "get": {
        "tags": [
          "SMS Reporting"
        ],
        "summary": "GET an SMS Campaigns Summary Report",
        "description": "Use this method to get SMS campaign summary details, including the total number of times that each contact uniquely interacted with each tracked campaign activity and aggregate tracking statistics. Results are sorted in descending order by the date the SMS was last sent (`last_sent_date`).\nThe `start_at` date is required. Use both the `start_at` and `end_at` date query parameters to return only SMS campaign summary details that occurred within a specified date range.\nUs[...]",
        "operationId": "getAllBulkSmsCampaignSummaries",
        "security": [
          {
            "oauth2_implicit": [
              "campaign_data"
            ]
          },
          {
            "oauth2_access_code": [
              "campaign_data"
            ]
          }
        ],
        "x-authorization-privileges": [
          "ui:campaign:metrics"
        ]
      }
    },
    "/partner/accounts": {
      "get": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "GET Partner Client Accounts",
        "description": "Get all Constant Contact client accounts managed under your technology partner account. Use the `limit` query parameter to set the number of accounts to return on each results page. Use the `account_type` query parameter to filter client account results by type: `all` (default), `managed`, or `unmanaged`.\nOnly technology partners can access partner endpoints and partner endpoints cannot be tested using the API reference tester.\nFor more use case information, see [Get al[...]",
        "operationId": "getPartnerSiteOwners",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "getAccounts"
      },
      "post": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "POST (create) a Partner Client Account",
        "description": "Use this POST method to create a new Constant Contact client account under your partner account, set up the billing plan for the account, and to add the new client to the default contact list.\n\nNewly created accounts are free trials which give the user up to 60 days to try Constant Contact before buying. Trial accounts have limits depending on the services that are included.\n\nIf a field validation error occurs, a 400 response message is returned.\n\nIf provisioning do[...]",
        "operationId": "provision",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "createAccount"
      }
    },
    "/partner/accounts/{encoded_account_id}/plan": {
      "get": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "GET Billing Plan Details for a Client Account",
        "description": "Use this GET method to return billing plan details for a client's Constant Contact account.\nIf you are not on the latest billing plan, contact the Constant Contact Partner Team. However, older billing plans and `plan_type` enum values will continue to be supported. Only technology partners can access partner endpoints and partner endpoints cannot be tested using the API reference tester.\nFor more use case information, see [Get Billing Plan Details for a Client Account]([...]",
        "operationId": "getPlan",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "getAccountBillingPlan"
      },
      "put": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "PUT (update) Billing Plan Details for a Client Account",
        "description": "Use this PUT method to update the type of billing plan to assign to the Constant Contact client account. The type of billing plan determines which Constant Contact product features that the client account can access. The billing plan that you specify in the request body (`plan_type`) must already exist in the plan group. Attempting to change to a plan that is currently not available within your partner plan group results in a 400 error response code.\n\nWhen you create a [...]",
        "operationId": "setPlan",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "updateAccountBillingPlan"
      }
    },
    "/partner/accounts/{encoded_account_id}/status/cancel": {
      "put": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "PUT Cancel the Billing Plan for a Client Account",
        "description": "Use this PUT method to cancel a client's Constant Contact account. If the specified client account or technology partner account does not exist, the system returns a 404 error response. If the client account exists under a different technology partner account, the system returns a 400 error response.\n\n\n  To get a list of all canceled client accounts (`\"billing_status\": \"Canceled\"`), make a `GET` call to the `/partner/accounts` endpoint.\n\n  Only technology partner[...]",
        "operationId": "cancelAccount",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "cancelAccountBillingPlan"
      }
    },
    "/partner/accounts/{encoded_account_id}/account_operations/sync": {
      "post": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "POST Send an API request on Behalf of a Client Account",
        "description": "Use this API method to send an API request on behalf of a managed client account in your partnership.\n\nThe request body properties you use in this partner API call determine the structure of the API request that Constant Contact sends on behalf of the managed client account. This includes the HTTP url, HTTP method type, request body, request url parameters, request query parameters, and headers that for the request. You can use this `/partner/accounts/{encoded_account_i[...]",
        "operationId": "partnerAccountOperationsPostSync",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "sendRequestUsingManagedAccount"
      }
    },
    "/partner/accounts/{encoded_account_id}/users/sso": {
      "post": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "POST a User Under a Partner's SSO-Enabled Client Account",
        "description": "Use this endpoint to create a new user under a partner client account that has the Single Sign On (SSO) for all users feature enabled.",
        "operationId": "createSSOUser",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ]
      }
    },
    "/partner/accounts/{encoded_account_id}/contacts/unsubscribe": {
      "post": {
        "tags": [
          "Technology Partners"
        ],
        "summary": "POST Unsubscribe Contacts",
        "description": "Use to unsubscribe contacts from partner client accounts. Identify the contacts to unsubscribe using the `email_address` parameter. To unsubscribe a single contact from all partner client accounts, specify the contacts `email_address` and set the `global_unsubscribe` parameter to `true`.",
        "operationId": "partnerUnsubscribeContacts",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ]
      }
    },
    "/partner/webhooks/subscriptions": {
      "get": {
        "tags": [
          "Technology Partners Webhooks"
        ],
        "summary": "GET a Collection of Webhook Topic Subscriptions",
        "description": "Use this GET method to return a collection containing your application's webhook subscriptions.",
        "operationId": "getWebhooksCollection",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "getAllWebhooks"
      }
    },
    "/partner/webhooks/subscriptions/{topic_id}": {
      "get": {
        "tags": [
          "Technology Partners Webhooks"
        ],
        "summary": "GET Webhook Topic Subscription",
        "description": "Use this GET method to return subscription information for a certain `topic_id`. Possible `topic_id` values include:\n\n  * `1` - Billing tier upgrade.\n  * `2` - Billing tier downgrade.\n  * `3` - Account cancelled.\n  * `4` - Account disabled.",
        "operationId": "getWebhooksTopic",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "getWebhooksTopicById"
      },
      "put": {
        "tags": [
          "Technology Partners Webhooks"
        ],
        "summary": "PUT Webhook Topic Subscription",
        "description": "Use this PUT method to subscribe your application to a `topic_id` or to update the callback URI for an existing subscription. Possible `topic_id` values include:\n\n * `1` - Billing tier upgrade.\n * `2` - Billing tier downgrade.\n * `3` - Account cancelled.\n * `4` - Account disabled.\n\nAfter you subscribe your application, Constant Contact will automatically start sending POST notifications for your chosen topic to your application's callback URI. This is an example of[...]",
        "operationId": "putWebhooksTopic",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ],
        "x-sdk-methodName": "updateWebhooksTopic"
      },
      "delete": {
        "tags": [
          "Technology Partners Webhooks"
        ],
        "summary": "DELETE Webhook Topic Subscriptions",
        "description": "Use this DELETE method to unsubscribe your application from notifications on a certain `topic_id`. Possible `topic_id` values include:\n\n * `1` - Billing tier upgrade.\n * `2` - Billing tier downgrade.\n * `3` - Account cancelled.\n * `4` - Account disabled.",
        "operationId": "deleteWebhooksSubscriptions",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ]
      }
    },
    "/partner/webhooks/subscriptions/{topic_id}/tests": {
      "post": {
        "tags": [
          "Technology Partners Webhooks"
        ],
        "summary": "POST Test Send Webhook Notification",
        "description": "Use this POST method to validate a webhook subscription by triggering a test notification for your chosen webhook `topic_id`. Possible `topic_id` values include:\n\n * `1` - Billing tier upgrade.\n * `2` - Billing tier downgrade.\n * `3` - Account cancelled.\n * `4` - Account disabled.\n\nAfter you successfully send this request, Constant Contact will automatically send a POST notification to your chosen topic's callback URI with example data.",
        "operationId": "testSendWebhooksTopic",
        "security": [
          {
            "ctctPartnerAuthorizer": [],
            "api_key": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2_implicit": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://authz.constantcontact.com/oauth2/default/v1/authorize",
            "scopes": {
              "contact_data": "Read or modify contact data.",
              "campaign_data": "Read or modify email campaign data.",
              "account_read": "Read account data.",
              "account_update": "Modify account data."
            }
          }
        }
      },
      "oauth2_access_code": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://authz.constantcontact.com/oauth2/default/v1/authorize",
            "tokenUrl": "https://authz.constantcontact.com/oauth2/default/v1/token",
            "scopes": {
              "contact_data": "Read or modify contact data.",
              "campaign_data": "Read or modify email campaign data.",
              "account_read": "Read account data.",
              "account_update": "Modify account data."
            }
          }
        }
      },
      "ctctPartnerAuthorizer": {
        "type": "oauth2",
        "description": "Partner Authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://v3api-partner.auth.us-east-1.amazoncognito.com/oauth2/token",
            "scopes": {
              "v3api/general.partner": "Access to general partner API methods"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header"
      }
    }
  },
  "x-original-swagger-version": "2.0"
}