{
  "openapi": "3.0.0",
  "info": {
    "title": "SafetyLine",
    "version": "2.1",
    "x-jentic-source-url": "https://api.slmonitor.com/swagger/v2.1/swagger.json"
  },
  "servers": [
    {
      "url": "https://api.slmonitor.com/"
    }
  ],
  "paths": {
    "/api/v2.1/companies/{companyId}/checkin-text-suggestion": {
      "post": {
        "security": [
          {
            "EmailLogin": []
          },
          {
            "MicrosoftLogin": []
          }
        ],
        "tags": [
          "Api"
        ],
        "operationId": "Api_GetCheckInTextSuggestion",
        "summary": "Gets a suggested check-in message based on the surroundings"
      }
    },
    "/api/v2.1/companies/{companyId}/me": {
      "get": {
        "security": [
          {
            "EmailLogin": []
          },
          {
            "MicrosoftLogin": []
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation gets the authenticated user's profile.",
        "operationId": "Api_GetUser",
        "summary": "Get the authenticated user"
      }
    },
    "/api/v2.1/companies/{companyId}/monitors/{uniqueUserId}/notifications": {
      "get": {
        "security": [
          {
            "EmailLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation gets the specified user's monitor notifications.",
        "operationId": "Api_GetMonitorNotificationsForUser",
        "summary": "Get the user's monitor notifications"
      }
    },
    "/api/v2.1/companies/{companyId}/users": {
      "get": {
        "security": [
          {
            "EmailLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation gets all the users' profiles.",
        "operationId": "Api_GetUsers",
        "summary": "Get all the users"
      }
    },
    "/api/v2.1/companies/{companyId}/users/events": {
      "get": {
        "security": [
          {
            "EmailLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation retrieves the events within the specified time range.",
        "operationId": "Api_GetUserEvents",
        "summary": "Get the user events within a specified time range."
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}": {
      "get": {
        "security": [
          {
            "EmailLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyAdministrator",
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation gets the specified user's profile.",
        "operationId": "Api_GetUser2",
        "summary": "Get the user's profile"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation checks the worker in for a default time or a custom time if the optional interval is provided.",
        "operationId": "Api_CheckIn",
        "summary": "Check in"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin-audio": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation checks the worker in for a default time or a custom time if the optional interval is provided, and includes an audio attachment.",
        "operationId": "Api_CheckInWithAudio",
        "summary": "Check in with an audio recording"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin-text": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation checks the worker in for a default time or a custom time if the optional interval is provided.",
        "operationId": "Api_CheckInWithText",
        "summary": "Check in with a text report"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation declares an emergency.",
        "operationId": "Api_Emergency",
        "summary": "Declare an emergency"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency-audio": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation declares an emergency, and includes an audio attachment.",
        "operationId": "Api_EmergencyWithAudio",
        "summary": "Declare an emergency with an audio recording"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency-text": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation declares an emergency.",
        "operationId": "Api_EmergencyWithText",
        "summary": "Declare an emergency with a text report"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation ends monitoring.",
        "operationId": "Api_End",
        "summary": "End monitoring"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end-audio": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation ends monitoring, and includes an audio attachment.",
        "operationId": "Api_EndWithAudio",
        "summary": "End monitoring with an audio recording"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end-text": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation ends monitoring.",
        "operationId": "Api_EndWithText",
        "summary": "End monitoring with a text report"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/itinerary": {
      "put": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation updates the worker's itinerary.",
        "operationId": "Api_UpdateItinerary",
        "summary": "Update the itinerary"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/itinerary-file": {
      "put": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation updates the worker's itinerary.",
        "operationId": "Api_UpdateItineraryFile",
        "summary": "Update the itinerary file"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/location": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "This operation adds a location to the worker's event history.",
        "operationId": "Api_ReportLocation",
        "summary": "Report a location"
      }
    },
    "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/text": {
      "post": {
        "security": [
          {
            "EmailLogin": [
              "CompanyMonitor"
            ]
          },
          {
            "MicrosoftLogin": [
              "CompanyMonitor"
            ]
          }
        ],
        "tags": [
          "Api"
        ],
        "description": "The operation adds a text message to the worker's event history.",
        "operationId": "Api_ReportText",
        "summary": "Send a text message"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "EmailLogin": {
        "description": "",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://prodsafetyline.b2clogin.com/prodsafetyline.onmicrosoft.com/B2C_1_si/oauth2/v2.0/authorize",
            "scopes": {
              "https://prodsafetyline.onmicrosoft.com/e22f72d0-b056-4155-a2db-da02bc226023/access_as_user": "Access the API as the signed-in user",
              "offline_access": "This scopes gives your app access to resources on behalf of the user for an extended time (refresh tokens)."
            }
          }
        },
        "type": "oauth2"
      },
      "MicrosoftLogin": {
        "description": "",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize",
            "scopes": {
              "https://prodsafetyline.onmicrosoft.com/e22f72d0-b056-4155-a2db-da02bc226023/.default": "Use the default scopes",
              "offline_access": "This scopes gives your app access to resources on behalf of the user for an extended time (refresh tokens)."
            }
          }
        },
        "type": "oauth2"
      }
    }
  },
  "security": [
    {
      "EmailLogin": []
    },
    {
      "MicrosoftLogin": []
    }
  ],
  "x-generator": "NSwag v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))"
}