{
  "openapi": "3.0.0",
  "info": {
    "description": "The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to develo[...]",
    "title": "Strava API v3",
    "version": "3.0.0",
    "x-jentic-source-url": "https://developers.strava.com/swagger/swagger.json"
  },
  "servers": [
    {
      "url": "https://www.strava.com/api/v3"
    }
  ],
  "paths": {
    "/activities": {
      "post": {
        "summary": "Create an Activity",
        "operationId": "createActivity",
        "tags": [
          "Activities"
        ],
        "description": "Creates a manual activity for an athlete, requires activity:write scope."
      }
    },
    "/activities/{id}": {
      "get": {
        "summary": "Get Activity",
        "operationId": "getActivityById",
        "tags": [
          "Activities"
        ],
        "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities."
      },
      "put": {
        "summary": "Update Activity",
        "operationId": "updateActivityById",
        "tags": [
          "Activities"
        ],
        "description": "Updates the given activity that is owned by the authenticated athlete. Requires activity:write. Also requires activity:read_all in order to update Only Me activities"
      }
    },
    "/activities/{id}/comments": {
      "get": {
        "summary": "List Activity Comments",
        "operationId": "getCommentsByActivityId",
        "tags": [
          "Activities"
        ],
        "description": "Returns the comments on the given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities."
      }
    },
    "/activities/{id}/kudos": {
      "get": {
        "summary": "List Activity Kudoers",
        "operationId": "getKudoersByActivityId",
        "tags": [
          "Activities"
        ],
        "description": "Returns the athletes who kudoed an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities."
      }
    },
    "/activities/{id}/laps": {
      "get": {
        "summary": "List Activity Laps",
        "operationId": "getLapsByActivityId",
        "tags": [
          "Activities"
        ],
        "description": "Returns the laps of an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities."
      }
    },
    "/activities/{id}/streams": {
      "get": {
        "summary": "Get Activity Streams",
        "operationId": "getActivityStreams",
        "tags": [
          "Streams"
        ],
        "description": "Returns the given activity's streams. Requires activity:read scope. Requires activity:read_all scope for Only Me activities."
      }
    },
    "/activities/{id}/zones": {
      "get": {
        "summary": "Get Activity Zones",
        "operationId": "getZonesByActivityId",
        "tags": [
          "Activities"
        ],
        "description": "Summit Feature. Returns the zones of a given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities."
      }
    },
    "/athlete": {
      "get": {
        "summary": "Get Authenticated Athlete",
        "operationId": "getLoggedInAthlete",
        "tags": [
          "Athletes"
        ],
        "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation."
      },
      "put": {
        "summary": "Update Athlete",
        "operationId": "updateLoggedInAthlete",
        "tags": [
          "Athletes"
        ],
        "description": "Update the currently authenticated athlete. Requires profile:write scope."
      }
    },
    "/athlete/activities": {
      "get": {
        "summary": "List Athlete Activities",
        "operationId": "getLoggedInAthleteActivities",
        "tags": [
          "Activities"
        ],
        "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all."
      }
    },
    "/athlete/clubs": {
      "get": {
        "summary": "List Athlete Clubs",
        "operationId": "getLoggedInAthleteClubs",
        "tags": [
          "Clubs"
        ],
        "description": "Returns a list of the clubs whose membership includes the authenticated athlete."
      }
    },
    "/athlete/zones": {
      "get": {
        "summary": "Get Zones",
        "operationId": "getLoggedInAthleteZones",
        "tags": [
          "Athletes"
        ],
        "description": "Returns the the authenticated athlete's heart rate and power zones. Requires profile:read_all."
      }
    },
    "/athletes/{id}/routes": {
      "get": {
        "summary": "List Athlete Routes",
        "operationId": "getRoutesByAthleteId",
        "tags": [
          "Routes"
        ],
        "description": "Returns a list of the routes created by the authenticated athlete. Private routes are filtered out unless requested by a token with read_all scope."
      }
    },
    "/athletes/{id}/stats": {
      "get": {
        "summary": "Get Athlete Stats",
        "operationId": "getStats",
        "tags": [
          "Athletes"
        ],
        "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty."
      }
    },
    "/clubs/{id}": {
      "get": {
        "summary": "Get Club",
        "operationId": "getClubById",
        "tags": [
          "Clubs"
        ],
        "description": "Returns a given a club using its identifier."
      }
    },
    "/clubs/{id}/activities": {
      "get": {
        "summary": "List Club Activities",
        "operationId": "getClubActivitiesById",
        "tags": [
          "Clubs"
        ],
        "description": "Retrieve recent activities from members of a specific club. The authenticated athlete must belong to the requested club in order to hit this endpoint. Pagination is supported. Athlete profile visibility is respected for all activities."
      }
    },
    "/clubs/{id}/admins": {
      "get": {
        "summary": "List Club Administrators",
        "operationId": "getClubAdminsById",
        "tags": [
          "Clubs"
        ],
        "description": "Returns a list of the administrators of a given club."
      }
    },
    "/clubs/{id}/members": {
      "get": {
        "summary": "List Club Members",
        "operationId": "getClubMembersById",
        "tags": [
          "Clubs"
        ],
        "description": "Returns a list of the athletes who are members of a given club."
      }
    },
    "/gear/{id}": {
      "get": {
        "summary": "Get Equipment",
        "operationId": "getGearById",
        "tags": [
          "Gears"
        ],
        "description": "Returns an equipment using its identifier."
      }
    },
    "/routes/{id}": {
      "get": {
        "summary": "Get Route",
        "operationId": "getRouteById",
        "tags": [
          "Routes"
        ],
        "description": "Returns a route using its identifier. Requires read_all scope for private routes."
      }
    },
    "/routes/{id}/export_gpx": {
      "get": {
        "summary": "Export Route GPX",
        "operationId": "getRouteAsGPX",
        "tags": [
          "Routes"
        ],
        "description": "Returns a GPX file of the route. Requires read_all scope for private routes."
      }
    },
    "/routes/{id}/export_tcx": {
      "get": {
        "summary": "Export Route TCX",
        "operationId": "getRouteAsTCX",
        "tags": [
          "Routes"
        ],
        "description": "Returns a TCX file of the route. Requires read_all scope for private routes."
      }
    },
    "/routes/{id}/streams": {
      "get": {
        "summary": "Get Route Streams",
        "operationId": "getRouteStreams",
        "tags": [
          "Streams"
        ],
        "description": "Returns the given route's streams. Requires read_all scope for private routes."
      }
    },
    "/segment_efforts": {
      "get": {
        "summary": "List Segment Efforts",
        "operationId": "getEffortsBySegmentId",
        "tags": [
          "SegmentEfforts"
        ],
        "description": "Returns a set of the authenticated athlete's segment efforts for a given segment.  Requires subscription."
      }
    },
    "/segment_efforts/{id}": {
      "get": {
        "summary": "Get Segment Effort",
        "operationId": "getSegmentEffortById",
        "tags": [
          "SegmentEfforts"
        ],
        "description": "Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription."
      }
    },
    "/segment_efforts/{id}/streams": {
      "get": {
        "summary": "Get Segment Effort Streams",
        "operationId": "getSegmentEffortStreams",
        "tags": [
          "Streams"
        ],
        "description": "Returns a set of streams for a segment effort completed by the authenticated athlete. Requires read_all scope."
      }
    },
    "/segments/explore": {
      "get": {
        "summary": "Explore segments",
        "operationId": "exploreSegments",
        "tags": [
          "Segments"
        ],
        "description": "Returns the top 10 segments matching a specified query."
      }
    },
    "/segments/starred": {
      "get": {
        "summary": "List Starred Segments",
        "operationId": "getLoggedInAthleteStarredSegments",
        "tags": [
          "Segments"
        ],
        "description": "List of the authenticated athlete's starred segments. Private segments are filtered out unless requested by a token with read_all scope."
      }
    },
    "/segments/{id}": {
      "get": {
        "summary": "Get Segment",
        "operationId": "getSegmentById",
        "tags": [
          "Segments"
        ],
        "description": "Returns the specified segment. read_all scope required in order to retrieve athlete-specific segment information, or to retrieve private segments."
      }
    },
    "/segments/{id}/starred": {
      "put": {
        "summary": "Star Segment",
        "operationId": "starSegment",
        "tags": [
          "Segments"
        ],
        "description": "Stars/Unstars the given segment for the authenticated athlete. Requires profile:write scope."
      }
    },
    "/segments/{id}/streams": {
      "get": {
        "summary": "Get Segment Streams",
        "operationId": "getSegmentStreams",
        "tags": [
          "Streams"
        ],
        "description": "Returns the given segment's streams. Requires read_all scope for private segments."
      }
    },
    "/uploads": {
      "post": {
        "summary": "Upload Activity",
        "operationId": "createUpload",
        "tags": [
          "Uploads"
        ],
        "description": "Uploads a new data file to create an activity from. Requires activity:write scope."
      }
    },
    "/uploads/{uploadId}": {
      "get": {
        "summary": "Get Upload",
        "operationId": "getUploadById",
        "tags": [
          "Uploads"
        ],
        "description": "Returns an upload for a given identifier. Requires activity:write scope."
      }
    }
  },
  "components": {
    "securitySchemes": {
      "strava_oauth": {
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
            "scopes": {
              "activity:read": "Read the user's activity data for activities that are visible to Everyone and Followers, excluding privacy zone data",
              "activity:read_all": "The same access as activity:read, plus privacy zone data and access to read the user's activities with visibility set to Only You",
              "activity:write": "Access to create manual activities and uploads, and access to edit any activities that are visible to the app, based on activity read access level",
              "profile:read_all": "Read all profile information even if the user has set their profile visibility to Followers or Only You",
              "profile:write": "Update the user's weight and Functional Threshold Power (FTP), and access to star or unstar segments on their behalf",
              "read": "Read public segments, public routes, public profile data, public posts, public events, club feeds, and leaderboards",
              "read_all": "Read private routes, private segments, and private events for the user"
            },
            "tokenUrl": "https://www.strava.com/api/v3/oauth/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "security": [
    {
      "strava_oauth": [
        "public"
      ]
    }
  ]
}