{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "The Data Portability API lets you build applications that request authorization from a user to move a copy of data from Google services into your application. This enables data portability and facilitates switching services.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Data Portability API",
    "version": "v1beta",
    "x-jentic-source-url": "https://dataportability.googleapis.com/$discovery/rest?version=v1beta"
  },
  "servers": [
    {
      "url": "https://dataportability.googleapis.com/"
    }
  ],
  "paths": {
    "/v1beta/accessType:check": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "accessType"
        ],
        "description": "Gets the access type of the token.",
        "operationId": "dataportability.accessType.check"
      }
    },
    "/v1beta/authorization:reset": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "authorization"
        ],
        "description": "Revokes OAuth tokens and resets exhausted scopes for a user/project pair. This method allows you to initiate a request after a new consent is granted. This method also indicates that previous archives can be garbage collected. You should call this method when all jobs are complete and all archives are downloaded. Do not call it only when you start a new job.",
        "operationId": "dataportability.authorization.reset"
      }
    },
    "/v1beta/portabilityArchive:initiate": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "portabilityArchive"
        ],
        "description": "Initiates a new Archive job for the Portability API.",
        "operationId": "dataportability.portabilityArchive.initiate"
      }
    },
    "/v1beta/{+name}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "archiveJobs"
        ],
        "description": "Retrieves the state of an Archive job for the Portability API.",
        "operationId": "dataportability.archiveJobs.getPortabilityArchiveState"
      }
    },
    "/v1beta/{+name}:cancel": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "archiveJobs"
        ],
        "description": "Cancels a Portability Archive job.",
        "operationId": "dataportability.archiveJobs.cancel"
      }
    },
    "/v1beta/{+name}:retry": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.autofill"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.extensions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.history"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.chrome.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.follows"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.likes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.discover.not_interested"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.maps.starred_places"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.play"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.search"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.mymaps.maps"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.devices"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.grouping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.installs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.library"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.playpoints"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.promotions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.purchases"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.redemptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.play.usersettings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.saved.collections"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.addresses"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.shopping.reviews"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.streetview.imagery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.channel"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.clips"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.comments"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.music"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.playable"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.posts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.shopping"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
            ]
          }
        ],
        "tags": [
          "archiveJobs"
        ],
        "description": "Retries a failed Portability Archive job.",
        "operationId": "dataportability.archiveJobs.retry"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions": "Move a copy of the Google Alerts subscriptions you created",
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations": "Move a copy of messages between you and the businesses you have conversations with across Google services",
              "https://www.googleapis.com/auth/dataportability.chrome.autofill": "Move a copy of the information you entered into online forms in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks": "Move a copy of pages you bookmarked in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary": "Move a copy of words you added to Chrome's dictionary",
              "https://www.googleapis.com/auth/dataportability.chrome.extensions": "Move a copy of extensions you installed from the Chrome Web Store",
              "https://www.googleapis.com/auth/dataportability.chrome.history": "Move a copy of sites you visited in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list": "Move a copy of pages you added to your reading list in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.settings": "Move a copy of your settings in Chrome",
              "https://www.googleapis.com/auth/dataportability.discover.follows": "Move a copy of searches and sites you follow, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.discover.likes": "Move a copy of links to your liked documents, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.discover.not_interested": "Move a copy of content you marked as not interested, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places": "Move a copy of the places you labeled on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes": "Move a copy of your pinned trips on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings": "Move a copy of your commute settings on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile": "Move a copy of your electric vehicle profile on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions": "Move a copy of the corrections you made to places or map information on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions": "Move a copy of your updates to places on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos": "Move a copy of the photos and videos you posted on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers": "Move a copy of the questions and answers you posted on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.reviews": "Move a copy of your reviews and posts on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.starred_places": "Move a copy of your Starred places list on Maps",
              "https://www.googleapis.com/auth/dataportability.myactivity.maps": "Move a copy of your Maps activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter": "Move a copy of your My Ad Center activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.play": "Move a copy of your Google Play activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.search": "Move a copy of your Google Search activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping": "Move a copy of your Shopping activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube": "Move a copy of your YouTube activity",
              "https://www.googleapis.com/auth/dataportability.mymaps.maps": "Move a copy of the maps you created in My Maps",
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations": "Move a copy of your food purchase and reservation activity",
              "https://www.googleapis.com/auth/dataportability.play.devices": "Move a copy of information about your devices with Google Play Store installed",
              "https://www.googleapis.com/auth/dataportability.play.grouping": "Move a copy of your Google Play Store Grouping tags created by app developers",
              "https://www.googleapis.com/auth/dataportability.play.installs": "Move a copy of your Google Play Store app installations",
              "https://www.googleapis.com/auth/dataportability.play.library": "Move a copy of your Google Play Store downloads, including books, games, and apps",
              "https://www.googleapis.com/auth/dataportability.play.playpoints": "Move a copy of information about your Google Play Store Points",
              "https://www.googleapis.com/auth/dataportability.play.promotions": "Move a copy of information about your Google Play Store promotions",
              "https://www.googleapis.com/auth/dataportability.play.purchases": "Move a copy of your Google Play Store purchases",
              "https://www.googleapis.com/auth/dataportability.play.redemptions": "Move a copy of your Google Play Store redemption activities",
              "https://www.googleapis.com/auth/dataportability.play.subscriptions": "Move a copy of your Google Play Store subscriptions",
              "https://www.googleapis.com/auth/dataportability.play.usersettings": "Move a copy of your Google Play Store user settings and preferences",
              "https://www.googleapis.com/auth/dataportability.saved.collections": "Move a copy of your saved links, images, places, and collections from your use of Google services",
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments": "Move a copy of your comments on Google Search",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars": "Move a copy of your media reviews on Google Search",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers": "Move a copy of your self-reported video streaming provider preferences from Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs": "Move a copy of your indicated thumbs up and thumbs down on media in Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched": "Move a copy of information about the movies and TV shows you marked as watched on Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings": "Move a copy of your notification settings on the Google Search app",
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions": "Move a copy of your notification subscriptions on Google Search app",
              "https://www.googleapis.com/auth/dataportability.shopping.addresses": "Move a copy of your shipping information on Shopping",
              "https://www.googleapis.com/auth/dataportability.shopping.reviews": "Move a copy of reviews you wrote about products or online stores on Google Search",
              "https://www.googleapis.com/auth/dataportability.streetview.imagery": "Move a copy of the images and videos you uploaded to Street View",
              "https://www.googleapis.com/auth/dataportability.youtube.channel": "Move a copy of information about your YouTube channel",
              "https://www.googleapis.com/auth/dataportability.youtube.clips": "Move a copy of your YouTube clips metadata",
              "https://www.googleapis.com/auth/dataportability.youtube.comments": "Move a copy of your YouTube comments",
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat": "Move a copy of your YouTube messages in live chat",
              "https://www.googleapis.com/auth/dataportability.youtube.music": "Move a copy of your uploaded YouTube music tracks and your YouTube music library",
              "https://www.googleapis.com/auth/dataportability.youtube.playable": "Move a copy of your YouTube playables saved game progress files",
              "https://www.googleapis.com/auth/dataportability.youtube.posts": "Move a copy of your YouTube posts",
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists": "Move a copy of your YouTube private playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos": "Move a copy of your private YouTube videos and information about them",
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists": "Move a copy of your public YouTube playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos": "Move a copy of your public YouTube videos and information about them",
              "https://www.googleapis.com/auth/dataportability.youtube.shopping": "Move a copy of your YouTube shopping wishlists, and wishlist items",
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions": "Move a copy of your YouTube channel subscriptions, even if they're private",
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists": "Move a copy of your unlisted YouTube playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos": "Move a copy of your unlisted YouTube videos and information about them"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 accessCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/dataportability.alerts.subscriptions": "Move a copy of the Google Alerts subscriptions you created",
              "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations": "Move a copy of messages between you and the businesses you have conversations with across Google services",
              "https://www.googleapis.com/auth/dataportability.chrome.autofill": "Move a copy of the information you entered into online forms in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.bookmarks": "Move a copy of pages you bookmarked in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.dictionary": "Move a copy of words you added to Chrome's dictionary",
              "https://www.googleapis.com/auth/dataportability.chrome.extensions": "Move a copy of extensions you installed from the Chrome Web Store",
              "https://www.googleapis.com/auth/dataportability.chrome.history": "Move a copy of sites you visited in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.reading_list": "Move a copy of pages you added to your reading list in Chrome",
              "https://www.googleapis.com/auth/dataportability.chrome.settings": "Move a copy of your settings in Chrome",
              "https://www.googleapis.com/auth/dataportability.discover.follows": "Move a copy of searches and sites you follow, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.discover.likes": "Move a copy of links to your liked documents, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.discover.not_interested": "Move a copy of content you marked as not interested, saved by Discover",
              "https://www.googleapis.com/auth/dataportability.maps.aliased_places": "Move a copy of the places you labeled on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.commute_routes": "Move a copy of your pinned trips on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.commute_settings": "Move a copy of your commute settings on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.ev_profile": "Move a copy of your electric vehicle profile on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.factual_contributions": "Move a copy of the corrections you made to places or map information on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.offering_contributions": "Move a copy of your updates to places on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.photos_videos": "Move a copy of the photos and videos you posted on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.questions_answers": "Move a copy of the questions and answers you posted on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.reviews": "Move a copy of your reviews and posts on Maps",
              "https://www.googleapis.com/auth/dataportability.maps.starred_places": "Move a copy of your Starred places list on Maps",
              "https://www.googleapis.com/auth/dataportability.myactivity.maps": "Move a copy of your Maps activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.myadcenter": "Move a copy of your My Ad Center activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.play": "Move a copy of your Google Play activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.search": "Move a copy of your Google Search activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.shopping": "Move a copy of your Shopping activity",
              "https://www.googleapis.com/auth/dataportability.myactivity.youtube": "Move a copy of your YouTube activity",
              "https://www.googleapis.com/auth/dataportability.mymaps.maps": "Move a copy of the maps you created in My Maps",
              "https://www.googleapis.com/auth/dataportability.order_reserve.purchases_reservations": "Move a copy of your food purchase and reservation activity",
              "https://www.googleapis.com/auth/dataportability.play.devices": "Move a copy of information about your devices with Google Play Store installed",
              "https://www.googleapis.com/auth/dataportability.play.grouping": "Move a copy of your Google Play Store Grouping tags created by app developers",
              "https://www.googleapis.com/auth/dataportability.play.installs": "Move a copy of your Google Play Store app installations",
              "https://www.googleapis.com/auth/dataportability.play.library": "Move a copy of your Google Play Store downloads, including books, games, and apps",
              "https://www.googleapis.com/auth/dataportability.play.playpoints": "Move a copy of information about your Google Play Store Points",
              "https://www.googleapis.com/auth/dataportability.play.promotions": "Move a copy of information about your Google Play Store promotions",
              "https://www.googleapis.com/auth/dataportability.play.purchases": "Move a copy of your Google Play Store purchases",
              "https://www.googleapis.com/auth/dataportability.play.redemptions": "Move a copy of your Google Play Store redemption activities",
              "https://www.googleapis.com/auth/dataportability.play.subscriptions": "Move a copy of your Google Play Store subscriptions",
              "https://www.googleapis.com/auth/dataportability.play.usersettings": "Move a copy of your Google Play Store user settings and preferences",
              "https://www.googleapis.com/auth/dataportability.saved.collections": "Move a copy of your saved links, images, places, and collections from your use of Google services",
              "https://www.googleapis.com/auth/dataportability.search_ugc.comments": "Move a copy of your comments on Google Search",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.reviews_and_stars": "Move a copy of your media reviews on Google Search",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.streaming_video_providers": "Move a copy of your self-reported video streaming provider preferences from Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.thumbs": "Move a copy of your indicated thumbs up and thumbs down on media in Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.search_ugc.media.watched": "Move a copy of information about the movies and TV shows you marked as watched on Google Search and Google TV",
              "https://www.googleapis.com/auth/dataportability.searchnotifications.settings": "Move a copy of your notification settings on the Google Search app",
              "https://www.googleapis.com/auth/dataportability.searchnotifications.subscriptions": "Move a copy of your notification subscriptions on Google Search app",
              "https://www.googleapis.com/auth/dataportability.shopping.addresses": "Move a copy of your shipping information on Shopping",
              "https://www.googleapis.com/auth/dataportability.shopping.reviews": "Move a copy of reviews you wrote about products or online stores on Google Search",
              "https://www.googleapis.com/auth/dataportability.streetview.imagery": "Move a copy of the images and videos you uploaded to Street View",
              "https://www.googleapis.com/auth/dataportability.youtube.channel": "Move a copy of information about your YouTube channel",
              "https://www.googleapis.com/auth/dataportability.youtube.clips": "Move a copy of your YouTube clips metadata",
              "https://www.googleapis.com/auth/dataportability.youtube.comments": "Move a copy of your YouTube comments",
              "https://www.googleapis.com/auth/dataportability.youtube.live_chat": "Move a copy of your YouTube messages in live chat",
              "https://www.googleapis.com/auth/dataportability.youtube.music": "Move a copy of your uploaded YouTube music tracks and your YouTube music library",
              "https://www.googleapis.com/auth/dataportability.youtube.playable": "Move a copy of your YouTube playables saved game progress files",
              "https://www.googleapis.com/auth/dataportability.youtube.posts": "Move a copy of your YouTube posts",
              "https://www.googleapis.com/auth/dataportability.youtube.private_playlists": "Move a copy of your YouTube private playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.private_videos": "Move a copy of your private YouTube videos and information about them",
              "https://www.googleapis.com/auth/dataportability.youtube.public_playlists": "Move a copy of your public YouTube playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.public_videos": "Move a copy of your public YouTube videos and information about them",
              "https://www.googleapis.com/auth/dataportability.youtube.shopping": "Move a copy of your YouTube shopping wishlists, and wishlist items",
              "https://www.googleapis.com/auth/dataportability.youtube.subscriptions": "Move a copy of your YouTube channel subscriptions, even if they're private",
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists": "Move a copy of your unlisted YouTube playlists",
              "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos": "Move a copy of your unlisted YouTube videos and information about them"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "portabilityArchive"
    },
    {
      "name": "archiveJobs"
    },
    {
      "name": "accessType"
    },
    {
      "name": "authorization"
    }
  ]
}