{
  "openapi": "3.0.3",
  "info": {
    "title": "MURAL Public API",
    "description": "MURAL's Public API\n",
    "termsOfService": "https://start.mural.co/developer-beta/terms",
    "contact": {
      "name": "MURAL",
      "email": "m4d@mural.co"
    },
    "version": "1.0.0",
    "x-logo": {
      "url": "https://app.mural.co/static/images/new-logo.svg",
      "href": "https://mural.co"
    }
  },
  "servers": [
    {
      "url": "https://app.mural.co/api/public/{version}",
      "description": "MURAL Public API",
      "variables": {
        "version": {
          "default": "v1",
          "enum": [
            "v1"
          ]
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Murals"
    },
    {
      "name": "Mural Contents"
    },
    {
      "name": "Users"
    },
    {
      "name": "Rooms"
    },
    {
      "name": "Templates"
    },
    {
      "name": "Workspaces"
    },
    {
      "name": "Search"
    },
    {
      "name": "Preview",
      "description": "Preview resources that are subject to change."
    }
  ],
  "paths": {
    "/murals": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Create a mural",
        "description": "Create a mural in a room owned by the authenticated user.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createMural"
      }
    },
    "/murals/{muralId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Get single mural",
        "description": "Returns info for a mural that the authenticated user has read access to.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralById"
      },
      "delete": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Delete single mural",
        "description": "Deletes a mural that the authenticated user owns.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "deleteMuralById"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Update a mural",
        "description": "Update a mural the authenticated user owns or is a member of.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateMuralById"
      }
    },
    "/murals/{muralId}/access-info": {
      "post": {
        "tags": [
          "Murals"
        ],
        "summary": "Get mural's access information",
        "description": "Get the permission information for a particular mural.\n\n**Authorization scope**: `none`\n",
        "operationId": "muralAccessInfo"
      }
    },
    "/murals/{muralId}/assets": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create an asset URL",
        "description": "Create an asset URL to upload a file or image to a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createAsset"
      }
    },
    "/murals/{muralId}/duplicate": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Duplicate a mural",
        "description": "Duplicate an existing mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "duplicateMural"
      }
    },
    "/murals/{muralId}/export": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Export mural to file",
        "description": "Allows an authenticated user of a mural to export mural to a pdf file.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "exportMural"
      }
    },
    "/murals/{muralId}/exports/{exportId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Get export URL",
        "description": "Returns the download URL of an export operation.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "exportURLMural"
      }
    },
    "/murals/{muralId}/chat": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get chat for a mural",
        "description": "Returns all chat content for a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralChat"
      }
    },
    "/murals/{muralId}/private-mode": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get a private mode session for a mural.",
        "description": "Retrieves the current private mode session for the specified mural.\n\n **Required authorization scope**: `murals:read`\n",
        "operationId": "getPrivateMode"
      }
    },
    "/murals/{muralId}/private-mode/start": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Start a private mode session for a mural.",
        "description": "Initiates a private mode session for the specified mural.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "startPrivateMode"
      }
    },
    "/murals/{muralId}/private-mode/end": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Stops a private mode session for a mural.",
        "description": "End a private mode session for the specified mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "stopPrivateMode"
      }
    },
    "/murals/{muralId}/send-request-access": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Request access to a mural",
        "description": "Sends a request-access notification to the mural owner.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "sendRequestAccessToMural"
      }
    },
    "/murals/{muralId}/tags": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get tags in a mural",
        "description": "Returns the tags in a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralTags"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create a tag in a mural",
        "description": "Create a tag in a mural. Tag text is limited to 25 characters.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createMuralTag"
      }
    },
    "/murals/{muralId}/tags/{tagId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get a single tag",
        "description": "Get a tag on a mural\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getTagById"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a tag on a mural",
        "description": "Update a tag on a mural. Tag text is limited to 25 characters.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateTagById"
      },
      "delete": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Delete a tag from a mural",
        "description": "Delete a tag from a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "deleteTagById"
      }
    },
    "/murals/{muralId}/timer": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get the timer for a mural.",
        "description": "Retrieves the timer details for a specified mural.\n\n**Required authorization scope**: `murals:read`\n",
        "operationId": "getMuralTimer"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Pauses/resumes the mural timer.",
        "description": "Pauses/resumes the mural timer and/or adds extra time to the running timer.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "updateMuralTimer"
      }
    },
    "/murals/{muralId}/timer/start": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Start the timer for a mural.",
        "description": "Initiates the timer for the specified mural.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "startMuralTimer"
      }
    },
    "/murals/{muralId}/timer/end": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Stop the timer for a mural.",
        "description": "Stops the timer for the specified mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "stopMuralTimer"
      }
    },
    "/murals/{muralId}/users": {
      "get": {
        "security": [
          {
            "oauth2": [
              "users:read"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Get users of a mural",
        "description": "Returns all users of a mural. Users include members and guests.\n\n**Authorization scope**: `users:read`\n",
        "operationId": "getMuralUsers"
      }
    },
    "/murals/{muralId}/users/{userId}/permissions": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Update mural member permissions",
        "description": "Update mural member permissions, by an authenticated owner of the mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateMuralMemberPermissions"
      }
    },
    "/murals/{muralId}/users/invite": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Invite users to a mural",
        "description": "Allows an authenticated user of a mural to invite members and/or guests.\n\nYou can invite users by specifying either their email address or their username.\nIn both cases the user is notified by email. However, when inviting by username,\nthe user is immediately added to the mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "inviteUsersToMural"
      }
    },
    "/murals/{muralId}/users/remove": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Remove users from a mural",
        "description": "Removes members and/or guests from a specified mural that the authenticated user has write access to.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "removeMuralUsers"
      }
    },
    "/murals/{muralId}/voting-sessions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get voting sessions in a mural",
        "description": "Returns the voting sessions in a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralVotingSessions"
      }
    },
    "/murals/{muralId}/voting-sessions/{votingSessionId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get a voting session in a mural",
        "description": "Returns a single voting session in a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralVotingSessionById"
      },
      "delete": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Delete a voting session in a mural",
        "description": "Deletes a single voting session in a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "deleteMuralVotingSessionById"
      }
    },
    "/murals/{muralId}/voting-sessions/vote/{widgetId}": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Vote for a widget in the active voting session of a mural.",
        "description": "Submit a vote for a widget in the active voting session of a mural.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "voteWidgetMuralVotingSession"
      }
    },
    "/murals/{muralId}/voting-sessions/{votingSessionId}/results": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get voting session results in a mural",
        "description": "Returns the results of a voting session in a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralVotingSessionResults"
      }
    },
    "/murals/{muralId}/voting-sessions/start": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Start a voting session for a mural.",
        "description": "Initiates a voting session for the specified mural.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "startMuralVotingSession"
      }
    },
    "/murals/{muralId}/voting-sessions/end": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "End a voting session for a mural.",
        "description": "Ends a voting session for the specified mural.\n\n **Required authorization scope**: `murals:write`\n",
        "operationId": "endMuralVotingSession"
      }
    },
    "/murals/{muralId}/widgets": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get widgets for a mural",
        "description": "Returns all of the widgets for a mural. Does not currently include drawings.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralWidgets"
      }
    },
    "/murals/{muralId}/widgets/files": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get files for a mural",
        "description": "Returns all files for a mural.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralFileWidgets"
      }
    },
    "/murals/{muralId}/widgets/{widgetId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Get single widget",
        "description": "Returns information about a widget specified by its id.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getMuralWidget"
      },
      "delete": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Delete a widget",
        "description": "Delete a widget and its content from a Mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "deleteWidgetById"
      }
    },
    "/murals/{muralId}/widgets/area": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create an area on a mural",
        "description": "Create an area widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createArea"
      }
    },
    "/murals/{muralId}/widgets/area/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update an area on a mural",
        "description": "Update an area widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateArea"
      }
    },
    "/murals/{muralId}/widgets/arrow": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create an arrow on a mural",
        "description": "Create an arrow widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createArrow"
      }
    },
    "/murals/{muralId}/widgets/arrow/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update an arrow on a mural",
        "description": "Update an arrow widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateArrow"
      }
    },
    "/murals/{muralId}/widgets/file": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create a file on a mural",
        "description": "Create a file widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createFile"
      }
    },
    "/murals/{muralId}/widgets/file/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a file on a mural",
        "description": "Update a file widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateFile"
      }
    },
    "/murals/{muralId}/widgets/image": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create an image in a mural",
        "description": "Create an image widget in a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createImage"
      }
    },
    "/murals/{muralId}/widgets/image/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update an image in a mural",
        "description": "Update an image widget in a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateImage"
      }
    },
    "/murals/{muralId}/widgets/shape": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create shapes on a mural",
        "description": "Create one or more shape widgets on a mural. Limit 1000.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createShapeWidget"
      }
    },
    "/murals/{muralId}/widgets/shape/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a shape widget on a mural",
        "description": "Update a shape widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateShapeWidget"
      }
    },
    "/murals/{muralId}/widgets/sticky-note": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create sticky notes on a mural",
        "description": "Create one or more sticky note widgets on a mural. Limit 1000.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createStickyNote"
      }
    },
    "/murals/{muralId}/widgets/sticky-note/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a sticky note on a mural",
        "description": "Update a sticky note widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateStickyNote"
      }
    },
    "/murals/{muralId}/widgets/table": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create a table on a mural",
        "description": "Create a table widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createTable"
      }
    },
    "/murals/{muralId}/widgets/title": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create titles on a mural",
        "description": "Create one or more title widgets on a mural. Limit 1000.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createTitle"
      }
    },
    "/murals/{muralId}/widgets/title/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a title on a mural",
        "description": "Update a title widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateTitle"
      }
    },
    "/murals/{muralId}/widgets/textbox": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create text boxes on a mural",
        "description": "Create one or more text box widgets on a mural. Limit 1000.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createTextbox"
      }
    },
    "/murals/{muralId}/widgets/textbox/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a textbox on a mural",
        "description": "Update a textbox widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateTextbox"
      }
    },
    "/rooms": {
      "post": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Create a room",
        "description": "Create a room in a workspace that the authenticated user has write access to.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "createRoom"
      }
    },
    "/rooms/{roomId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "rooms:read"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Get single room",
        "description": "Returns information about a room that the authenticated user has read access to.\n\n**Authorization scope**: `rooms:read`\n",
        "operationId": "getRoomInfoById"
      },
      "delete": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Delete single room",
        "description": "Deletes a room that the authenticated user owns.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "deleteRoomById"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Update single room",
        "description": "Updates a room owned by the authenticated user.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "updateRoomById"
      }
    },
    "/rooms/{roomId}/folders": {
      "post": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Create a folder in a room",
        "description": "Creates a new folder in a room that the authenticated user has write access to.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "createRoomFolder"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "rooms:read"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Get folders for a room",
        "description": "Returns all folders for a room that the authenticated user has access to.\n\n**Authorization scope**: `rooms:read`\n",
        "operationId": "getRoomFolders"
      }
    },
    "/rooms/{roomId}/folders/{folderId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Delete a folder from a room",
        "description": "Delete a folder (and all its sub-folders and murals) from a room.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "deleteFolderById"
      }
    },
    "/rooms/{roomId}/users": {
      "get": {
        "security": [
          {
            "oauth2": [
              "users:read"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Get users for a room",
        "description": "Returns all members (including partial) and guests for a room the authenticated user has read access to.\n\n**Authorization scope**: `users:read`\n",
        "operationId": "getRoomMembers"
      }
    },
    "/rooms/{roomId}/users/permissions": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Update room's members' permissions.",
        "description": "Updates the permissions of one or more members of the specified room.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "updateRoomMemberPermissions"
      }
    },
    "/rooms/{roomId}/users/invite": {
      "post": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Invite users to a room",
        "description": "Allows an authenticated user of a room to invite members and/or guests.\n\nYou can invite users by specifying either their email address or their username.\nIn both cases the user is notified by email. However, when inviting by username,\nthe user is immediately added to the room.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "inviteUsersToRoom"
      }
    },
    "/rooms/{roomId}/users/remove": {
      "post": {
        "security": [
          {
            "oauth2": [
              "rooms:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Remove users from a room",
        "description": "Removes members and/or guests from a specified room that the authenticated user has write access to.\n\n**Authorization scope**: `rooms:write`\n",
        "operationId": "removeRoomUsers"
      }
    },
    "/templates": {
      "get": {
        "security": [
          {
            "oauth2": [
              "templates:read"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Get default templates",
        "description": "Returns all default templates.\n\n**Authorization scope**: `templates:read`\n",
        "operationId": "getDefaultTemplates"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "templates:write"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Create a custom template from a mural",
        "description": "Creates a custom template based on a mural to use in a workspace.\n\n**Authorization scope**: `templates:write`\n",
        "operationId": "createCustomTemplate"
      }
    },
    "/templates/{templateId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "templates:write"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Delete single template",
        "description": "Deletes a template that the authenticated user owns.\n\n**Authorization scope**: `templates:write`\n",
        "operationId": "deleteTemplateById"
      }
    },
    "/templates/{templateId}/murals": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Create a mural from a template",
        "description": "Create a mural in a room based on a template.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createMuralFromTemplate"
      }
    },
    "/users/me": {
      "get": {
        "security": [
          {
            "oauth2": [
              "identity:read"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Get current user",
        "description": "Returns information for the currently authenticated user.\n\n**Authorization scope**: `identity:read`\n",
        "operationId": "getCurrentMember"
      }
    },
    "/workspaces": {
      "get": {
        "security": [
          {
            "oauth2": [
              "workspaces:read"
            ]
          }
        ],
        "tags": [
          "Workspaces"
        ],
        "summary": "Get workspaces",
        "description": "Returns all workspaces the authenticated user is a member of, whether the workspace or user is active or inactive.\n\n**Authorization scope**: `workspaces:read`\n",
        "operationId": "getWorkspaces"
      }
    },
    "/workspaces/{workspaceId}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "workspaces:read"
            ]
          }
        ],
        "tags": [
          "Workspaces"
        ],
        "summary": "Get single workspace",
        "description": "Returns information for a workspace that the authenticated user has read access to.\n\n**Authorization scope**: `workspaces:read`\n",
        "operationId": "getWorkspace"
      }
    },
    "/workspaces/{workspaceId}/murals": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Get murals for a workspace",
        "description": "Returns all murals that the authenticated user owns or is a member of for a workspace.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getWorkspaceMurals"
      }
    },
    "/workspaces/{workspaceId}/murals/recent": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Get recently opened murals for a workspace",
        "description": "Returns the authenticated user's recently opened active murals in a workspace.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getWorkspaceRecentMurals"
      }
    },
    "/workspaces/{workspaceId}/rooms": {
      "get": {
        "security": [
          {
            "oauth2": [
              "rooms:read"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Get rooms for a workspace",
        "description": "Returns all rooms in a workspace that the authenticated user has read access to. The user must have access to both the workspace and the rooms.\n\n**Authorization scope**: `rooms:read`\n",
        "operationId": "getWorkspaceRooms"
      }
    },
    "/workspaces/{workspaceId}/rooms/open": {
      "get": {
        "security": [
          {
            "oauth2": [
              "rooms:read"
            ]
          }
        ],
        "tags": [
          "Rooms"
        ],
        "summary": "Get open rooms for a workspace",
        "description": "Returns all the discoverable open rooms in a workspace.\n\n**Authorization scope**: `rooms:read`\n",
        "operationId": "getWorkspaceOpenRooms"
      }
    },
    "/workspaces/{workspaceId}/users/invite": {
      "post": {
        "security": [
          {
            "oauth2": [
              "workspaces:write"
            ]
          }
        ],
        "tags": [
          "Users"
        ],
        "summary": "Invite users to a workspace",
        "description": "Allows an authenticated admin of a workspace to invite members and/or guests.\n\nSpecify a user's email address to send them an invitation by email.\n\n**Authorization scope**: `workspaces:write`\n",
        "operationId": "inviteUsersToWorkspace"
      }
    },
    "/rooms/{roomId}/murals": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Get murals for a room",
        "description": "Returns all murals for a room that the authenticated user has read access to.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "getRoomMurals"
      }
    },
    "/workspaces/{workspaceId}/templates": {
      "get": {
        "security": [
          {
            "oauth2": [
              "templates:read"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Get default and custom templates for a workspace",
        "description": "Returns default templates and custom templates for a workspace the authenticated user has access to.\n\n**Authorization scope**: `templates:read`\n",
        "operationId": "getTemplatesByWorkspace"
      }
    },
    "/workspaces/{workspaceId}/templates/recent": {
      "get": {
        "security": [
          {
            "oauth2": [
              "templates:read"
            ]
          }
        ],
        "tags": [
          "Templates"
        ],
        "summary": "Get the recent templates for a workspace",
        "description": "Returns the recent templates used by a user for a workspace the authenticated user has access to. By default, default and custom templates are returned. By specifying parameter `withoutDefault=true`, the list of returned templates will not include default templates.\n**Authorization scope**: `templates:read`\n",
        "operationId": "getRecentTemplates"
      }
    },
    "/search/{workspaceId}/murals": {
      "get": {
        "security": [
          {
            "oauth2": [
              "murals:read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "summary": "Search murals",
        "description": "Returns all murals that the authenticated user owns or is a member of for a specific workspace.\n\n**Authorization scope**: `murals:read`\n",
        "operationId": "searchMurals"
      }
    },
    "/search/{workspaceId}/rooms": {
      "get": {
        "security": [
          {
            "oauth2": [
              "rooms:read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "summary": "Search rooms",
        "description": "Returns all rooms that the authenticated user owns or is a member of from a specific workspace.\n\n**Authorization scope**: `rooms:read`\n",
        "operationId": "searchRooms"
      }
    },
    "/search/{workspaceId}/templates": {
      "get": {
        "security": [
          {
            "oauth2": [
              "templates:read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "summary": "Search templates",
        "description": "Returns all custom templates the authenticated user owns or has access to.\n\n**Authorization scope**: `templates:read`\n",
        "operationId": "searchTemplates"
      }
    },
    "/murals/{muralId}/widgets/comment": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Create a comment on a mural",
        "description": "Create a comment widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "createComment"
      }
    },
    "/murals/{muralId}/widgets/comment/{widgetId}": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Mural Contents"
        ],
        "summary": "Update a comment on a mural",
        "description": "Update a comment widget on a mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateComment"
      }
    },
    "/murals/{muralId}/visitor-settings": {
      "patch": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Update mural visitor settings",
        "description": "Update visitor settings of a mural, by an authenticated owner of the mural.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "updateMuralVisitorSettings"
      }
    },
    "/murals/{muralId}/visitor-settings/reset-link": {
      "post": {
        "security": [
          {
            "oauth2": [
              "murals:write"
            ]
          }
        ],
        "tags": [
          "Murals"
        ],
        "summary": "Reset the mural visitor link",
        "description": "Resets the mural visitor URL so the previous visitor URL will no longer work.\n\n**Authorization scope**: `murals:write`\n",
        "operationId": "resetVisitorLink"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.mural.co/api/public/v1/authorization/oauth2",
            "tokenUrl": "https://app.mural.co/api/public/v1/authorization/oauth2/token",
            "refreshUrl": "https://app.mural.co/api/public/v1/authorization/oauth2/token",
            "scopes": {
              "rooms:read": "Read information about rooms (for room members and owners).",
              "rooms:write": "Write information about rooms (for room owners).",
              "users:read": "Read information about users (guests, members, and visitors).",
              "workspaces:write": "Write information about workspaces (for workspace owners)",
              "workspaces:read": "Read information about workspaces (for workspace members and owners).",
              "murals:read": "Read information about murals (for mural members and owners).",
              "murals:write": "Write information about murals (for mural members and owners).",
              "identity:read": "Read information about currently authenticated user.",
              "templates:read": "Read information about templates.",
              "templates:write": "Write information about templates (for templates owners)"
            }
          }
        }
      }
    }
  }
}