{
  "openapi": "3.0.3",
  "info": {
    "version": "5.23.0",
    "title": "Pinterest REST API",
    "description": "Pinterest's REST API",
    "contact": {
      "name": "Pinterest, Inc.",
      "url": "https://developers.pinterest.com/"
    },
    "license": {
      "name": "MIT",
      "url": "https://spdx.org/licenses/MIT"
    },
    "termsOfService": "https://developers.pinterest.com/terms/"
  },
  "servers": [
    {
      "url": "https://api.pinterest.com/v5"
    }
  ],
  "paths": {
    "/ad_accounts": {
      "get": {
        "operationId": "ad_accounts/list",
        "summary": "List ad accounts",
        "description": "Get a list of the ad_accounts that the \"operation user_account\" has access to.\n        - This includes ad_accounts they own and ad_accounts that are owned by others who have granted them [Business Access](https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts).",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "ad_accounts/create",
        "summary": "Create ad account",
        "description": "Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.\nAn ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account.\n\nYou can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.)\nFor more, see [Create an advertiser account](https://help.pinterest.c[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}": {
      "get": {
        "operationId": "ad_accounts/get",
        "summary": "Get ad account",
        "description": "Get an ad account",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups": {
      "get": {
        "operationId": "ad_groups/list",
        "summary": "List ad groups",
        "description": "List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id. Do not provide both.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "ad_groups/create",
        "summary": "Create ad groups",
        "description": "Create multiple new ad groups. All ads in a given ad group will have the same budget, bid, run dates, targeting, and placement (search, browse, other). For more information, <a href=\"https://help.pinterest.com/en/business/article/campaign-structure\" target=\"_blank\"> click here</a>.\n<strong>Notes:</strong>\n- `bid_in_micro_currency` and `budget_in_micro_currency` should be expressed in microcurrency amounts based on the currency field set in the advertiser's profile.<[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "ad_groups/update",
        "summary": "Update ad groups",
        "description": "Update multiple existing ad groups.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/analytics": {
      "get": {
        "operationId": "ad_groups/analytics",
        "summary": "Get ad group analytics",
        "description": "Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, you can pull data from up to[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/targeting_analytics": {
      "get": {
        "operationId": "ad_groups_targeting_analytics/get",
        "summary": "Get targeting analytics for ad groups",
        "description": "Get targeting analytics for one or more ad groups.\nFor the requested ad group(s) and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/audience_sizing": {
      "post": {
        "operationId": "ad_groups/audience_sizing",
        "summary": "Get audience sizing",
        "description": "Get potential audience size for an ad group with given targeting criteria. \nPotential audience size estimates the number of people you may be able to reach per month with your campaign. \nIt is based on historical advertising data and the targeting criteria you select.\nIt does not guarantee results or take into account factors such as bid, budget, schedule, seasonality or product experiments.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}": {
      "get": {
        "operationId": "ad_groups/get",
        "summary": "Get ad group",
        "description": "Get a specific ad group given the ad group ID.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ad_previews": {
      "post": {
        "operationId": "ad_previews/create",
        "summary": "Create ad preview with pin or image",
        "description": "Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>\nIf you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href=\"https://help.pinterest.com/en/business/article/promoted-pins-overview\" target=\"_blank\">Ads Overview</a>.) <p/>\nYou can view the returned preview URL on [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads": {
      "get": {
        "operationId": "ads/list",
        "summary": "List ads",
        "description": "List ads that meet the filters provided:\n  - Listed campaign ids or ad group ids or ad ids\n  - Listed entity statuses <p/>\nIf no filter is provided, all ads in the ad account are returned. <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>\nReview status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.\nFor more, see <a href=\"h[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "ads/create",
        "summary": "Create ads",
        "description": "Create multiple new ads. Request must contain `ad_group_id`, `creative_type`, and the source Pin `pin_id`.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "ads/update",
        "summary": "Update ads",
        "description": "Update multiple existing ads",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/analytics": {
      "get": {
        "operationId": "ads/analytics",
        "summary": "Get ad analytics",
        "description": "Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- The request must contain either ad_ids or both campaign_ids an[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads_credit/discounts": {
      "get": {
        "operationId": "ads_credits_discounts/get",
        "summary": "Get ads credit discounts",
        "description": "Returns the list of discounts applied to the account.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "billing:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads_credit/redeem": {
      "post": {
        "operationId": "ads_credit/redeem",
        "summary": "Redeem ad credits",
        "description": "Redeem ads credit on behalf of the ad account id and apply it towards billing.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write",
              "billing:write"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/targeting_analytics": {
      "get": {
        "operationId": "ad_targeting_analytics/get",
        "summary": "Get targeting analytics for ads",
        "description": "Get targeting analytics for one or more ads. For the requested ad(s) and metrics,\nthe response will include the requested metric information (e.g. SPEND_IN_DOLLAR) for the requested target type\n(e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage-[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ads/{ad_id}": {
      "get": {
        "operationId": "ads/get",
        "summary": "Get ad",
        "description": "Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will\ncontain additional information from the Ad Review process.\nFor more information about our policies and rejection reasons see the <a href=\"https://www.pinterest.com/_/_/policy/advertising-guidelines/\" target=\"_blank\">Pinterest advertising standards</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ads"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/advertiser_defined_events": {
      "get": {
        "operationId": "advertiser_defined_events/get",
        "summary": "Get advertiser defined events",
        "description": "<p>Get advertiser defined events for the given ad account.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversions"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/analytics": {
      "get": {
        "operationId": "ad_account/analytics",
        "summary": "Get ad account analytics",
        "description": "Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, you can pull data from up to 90 days before the current[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audience_insights": {
      "get": {
        "operationId": "audience_insights/get",
        "summary": "Get audience insights",
        "description": "Get Audience Insights for an ad account. The response will return insights for 3 types of audiences: the\nad account's engaged audience on Pinterest, the ad account's total audience on Pinterest and Pinterest's\ntotal audience.<p/>\n<a href=\"https://help.pinterest.com/en/business/article/audience-insights\" target=\"_blank\">Learn more about Audience Insights</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "audience_insights"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences": {
      "get": {
        "operationId": "audiences/list",
        "summary": "List audiences",
        "description": "Get list of audiences for the ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "audiences"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "audiences/create",
        "summary": "Create audience",
        "description": "Create an audience you can use in targeting for specific ad groups. Targeting combines customer information with\nthe ways users interact with Pinterest to help you reach specific groups of users; you can include or exclude\nspecific `audience_ids` when you create an ad group. <p/>\nLearn about <a href=\"/docs/work-with-targets-and-audiences/create-audiences/\" target=\"_blank\">creating different kinds of audiences</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "audiences"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/{audience_id}": {
      "get": {
        "operationId": "audiences/get",
        "summary": "Get audience",
        "description": "Get a specific audience given the audience ID.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "audiences"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "audiences/update",
        "summary": "Update audience",
        "description": "Update (edit or remove) an existing targeting audience.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "audiences"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/shared/accounts": {
      "get": {
        "operationId": "ad_accounts_audiences_shared_accounts/list",
        "summary": "List accounts with access to an audience owned by an ad account",
        "description": "List all ad accounts and/or businesses that have access to a specific audience. The audience must be owned by the requesting ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/ad_accounts/shared": {
      "patch": {
        "operationId": "update_ad_account_to_ad_account_shared_audience",
        "summary": "Update audience sharing between ad accounts",
        "description": "From an ad account, share a specific audience with another ad account, or revoke access to a previously shared audience. Only the audience owner account can share the audience. The recipient ad account(s) must be in the same <a href='https://help.pinterest.com/en/business/article/create-and-manage-accounts'>Pinterest Business Hierarchy</a> as the business owner of the ad account.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/using-beta-and-[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/audiences/businesses/shared": {
      "patch": {
        "operationId": "update_ad_account_to_business_shared_audience",
        "summary": "Update audience sharing from an ad account to businesses",
        "description": "From an ad account, share a specific audience with a business account, or revoke access to a previously shared audience. Only the audience owner account can share the audience. The recipient business account must be in the same business hierarchy as the business owner of the ad account.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bid_floor": {
      "post": {
        "operationId": "ad_groups_bid_floor/get",
        "summary": "Get bid floors",
        "description": "List bid floors for your campaign configuration. Bid floors are given in microcurrency values based on the currency in the bid floor specification. <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser\u2019s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser\u2019s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars as an example currency:</[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_groups"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/billing_profiles": {
      "get": {
        "operationId": "billing_profiles/get",
        "summary": "Get billing profiles",
        "description": "Get billing profiles in the advertiser account.\n\n<strong>This endpoint might not be available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "billing:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/billing_invoices": {
      "get": {
        "operationId": "billing_invoices/get",
        "summary": "Get billing invoices",
        "description": "Get billing invoices in the advertiser account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "billing:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/billing_invoice/{billing_invoice_id}/download": {
      "get": {
        "operationId": "billing_invoice_download/get",
        "summary": "Get download url for a billing invoice",
        "description": "Get download url for a billing invoice.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "billing:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/download": {
      "post": {
        "operationId": "bulk_download/create",
        "summary": "Get advertiser entities in bulk",
        "description": "Create an asynchronous report that may include information on campaigns, ad groups, product groups, ads,\nkeywords, and/or labels; can filter by campaigns. Though the entities may be active, archived, or paused,\nonly active entities will return data.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "bulk"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/upsert": {
      "post": {
        "operationId": "bulk_upsert/create",
        "summary": "Create/update ad entities in bulk",
        "description": "Either create or update any combination of campaigns, ad groups, product groups, ads, keywords, or labels.\nNote that this request will be processed asynchronously; the response will include a <code>request_id</code>\nthat can be used to obtain the status of the request.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "bulk"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/bulk/{bulk_request_id}": {
      "get": {
        "operationId": "bulk_request/get",
        "summary": "Download advertiser entities in bulk",
        "description": "Get the status of a bulk request by <code>request_id</code>, along with a download URL that will allow you to download the\nnew or updated entity data (campaigns, ad groups, product groups, ads, or keywords).",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "bulk"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns": {
      "get": {
        "operationId": "campaigns/list",
        "summary": "List campaigns",
        "description": "Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "campaigns/create",
        "summary": "Create campaigns",
        "description": "Create multiple new campaigns. Every campaign has its own campaign_id and houses one or more ad groups, which contain one or more ads.\nFor more, see <a href=\"https://help.pinterest.com/en/business/article/set-up-your-campaign/\">Set up your campaign</a>. <p/>\n<strong>Note:</strong>\n- The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "campaigns/update",
        "summary": "Update campaigns",
        "description": "<p>Update multiple ad campaigns based on campaign_ids. </p>\n<p><strong>Note:</strong></p>\n- <p>The values for `lifetime_spend_cap` and `daily_spend_cap` are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertiser's profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser's p[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/analytics": {
      "get": {
        "operationId": "campaigns/analytics",
        "summary": "Get campaign analytics",
        "description": "Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, you can pull data from up to[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/targeting_analytics": {
      "get": {
        "operationId": "campaign_targeting_analytics/get",
        "summary": "Get targeting analytics for campaigns",
        "description": "Get targeting analytics for one or more campaigns.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/{campaign_id}": {
      "get": {
        "operationId": "campaigns/get",
        "summary": "Get campaign",
        "description": "Get a specific campaign given the campaign ID.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags": {
      "post": {
        "operationId": "conversion_tags/create",
        "summary": "Create conversion tag",
        "description": "Create a conversion tag, also known as [Pinterest tag](https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag), with the option to enable enhanced match.\n\nThe Pinterest Tag tracks actions people take on the ad account's website after they view the ad account's ad on Pinterest. The advertiser needs to customize this tag to track conversions.\n\nFor more information, see:\n\n[Set up the Pinterest tag](https://help.pinterest.com/en/business/article/set-up-[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "conversion_tags"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "get": {
        "operationId": "conversion_tags/list",
        "summary": "List conversion tags",
        "description": "List conversion tags associated with an ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversion_tags"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/ocpm_eligible": {
      "get": {
        "operationId": "ocpm_eligible_conversion_tags/get",
        "summary": "Get Ocpm eligible conversion tags",
        "description": "Get Ocpm eligible conversion tag events for an ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversion_tags"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/page_visit": {
      "get": {
        "operationId": "page_visit_conversion_tags/get",
        "summary": "Get page visit conversion tags",
        "description": "Get all page visit conversion tag events for an ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversion_tags"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_tags/{conversion_tag_id}": {
      "get": {
        "operationId": "conversion_tags/get",
        "summary": "Get conversion tag",
        "description": "Get information about an existing conversion tag.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversion_tags"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists": {
      "post": {
        "operationId": "customer_lists/create",
        "summary": "Create customer lists",
        "description": "<p>Create a customer list from your records(hashed or plain-text email addresses, or hashed MAIDs or IDFAs).</p>\n<p>A customer list is one of the four types of Pinterest audiences: for more information, see <a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\nor the <a href=\"/docs/api-features/targeting-overview/\" target=\"_blank\">Audiences</a> section of the ads management guide.<p/>\n<p><b>Please rev[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "customer_lists"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "get": {
        "operationId": "customer_lists/list",
        "summary": "Get customer lists",
        "description": "<p>Get a set of customer lists including id and name based on the filters provided.</p>\n<p>(Customer lists are a type of audience.) For more information, see\n<a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\n or the <a href=\"/docs/api-features/targeting-overview/\" target=\"_blank\">Audiences</a>\nsection of the ads management guide.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "customer_lists"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}": {
      "get": {
        "operationId": "customer_lists/get",
        "summary": "Get customer list",
        "description": "Gets a specific customer list given the customer list ID.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "customer_lists"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "customer_lists/update",
        "summary": "Update customer list",
        "description": "<p>Append or remove records to/from an existing customer list. (A customer list is one of the four types of Pinterest audiences.)</p>\n<p>When you add records to an existing customer list, the system scans the additions for existing Pinterest\naccounts; those are the records that will be added to your \u201cCUSTOMER_LIST\u201d audience. Your original list of records\nto add will be deleted when the matching process is complete.</p>\n<p>For more information, see <a href=\"[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "customer_lists"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}/uploads": {
      "post": {
        "operationId": "customer_list_uploads/create",
        "summary": "Create customer list upload",
        "description": "<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"_blank\">Closed beta</a>\n\n<p>Create a customer list upload request for multipart S3 upload.</p>\n<p>Note: Each part must be at least 5mb; however the last part can be any size greater than 0.\nClients with smaller files can request a single part count. This minimal part size restriction is defined by the AWS S3 API.</p>\n<p><b>Please review the <u><a href=\"/docs/api/v5/customer_lists-update/[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "customer_list_uploads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}/uploads/{customer_list_upload_id}": {
      "get": {
        "operationId": "customer_list_uploads/get",
        "summary": "Get customer list upload",
        "description": "<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"_blank\">Closed beta</a>\n<p>Get the metadata for a given upload by its ID.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "customer_list_uploads"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}/uploads/{customer_list_upload_id}/run": {
      "post": {
        "operationId": "customer_list_uploads/run",
        "summary": "Run customer list upload",
        "description": "<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"_blank\">Closed beta</a>\n<p>Begin processing a customer list upload.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "customer_list_uploads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/events": {
      "post": {
        "operationId": "events/create",
        "summary": "Send conversions",
        "description": "The Pinterest API offers advertisers a way to send Pinterest their conversion information (including web conversions, in-app conversions, or even offline conversions) based on their <code>ad_account_id</code>. The request body should be a JSON object.\n- This endpoint requires an <code>access_token</code> be generated through Ads Manager. Review the <a href=\"/docs/api-features/conversion-overview/\">Conversions Guide</a> for more details. (Note that the authorization hea[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          },
          {
            "conversion_token": []
          }
        ],
        "tags": [
          "conversion_events"
        ],
        "x-ratelimit-category": "ads_conversions",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/msot/events": {
      "post": {
        "operationId": "msot_events/create",
        "summary": "Send Measurement Source Of Truth (MSOT) attributed conversion events",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n<br>\n<p>Advertisers or their measurement partners can send attributed MSOT conversion events to Pinterest based on their <code>ad_account_id</code>. The request body should be a JSON object.</p>\n- These events will NOT be used in Reporting.",
        "security": [
          {
            "pinterest_oauth2": [
              "msot:write"
            ]
          }
        ],
        "tags": [
          "msot_events"
        ],
        "x-ratelimit-category": "msot_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/insights/audiences": {
      "get": {
        "operationId": "audience_insights_scope_and_type/get",
        "summary": "Get audience insights scope and type",
        "description": "Get the scope and type of available audiences, which along with a date, is an audience that has recently had an interaction (referred to here as a type) on pins. Interacted pins can belong to at least the most common **partner** or **Pinterest** scopes. This means that user interactions made on advertiser or partner pins will have the **partner** scope. You can also have user interactions performed in general on Pinterest with the **Pinterest** scope. In that case, you ca[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "audience_insights"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords": {
      "get": {
        "operationId": "keywords/get",
        "summary": "Get keywords",
        "description": "<p>Get a list of keywords based on the filters provided. If no filter is provided, it will default to the ad_account_id filter, which means it will only return keywords that specifically have parent_id set to the ad_account_id. Note: Keywords can have ad_account_ids, campaign_ids, and ad_group_ids set as their parent_ids. Keywords created through Ads Manager will have their parent_id set to an ad_group_id, not ad_account_id.</p>\n<p>For more information, see <a target=\"_[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "keywords"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "keywords/create",
        "summary": "Create keywords",
        "description": "<p>Create keywords for following entity types(advertiser, campaign, ad group or ad).</p> <p>For more information, see <a target=\"_blank\" href=\"https://help.pinterest.com/en/business/article/keyword-targeting\">Keyword targeting</a>.</p>\n<p><b>Notes:</b></p> <ul style=\"list-style-type: square;\"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "keywords"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "keywords/update",
        "summary": "Update keywords",
        "description": "<p>Update one or more keywords' bid and archived fields.</p> <p>Archiving a keyword effectively deletes it - keywords no longer receive metrics and no longer visible within the parent entity's keywords list.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "keywords"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/keywords/metrics": {
      "get": {
        "operationId": "country_keywords_metrics/get",
        "summary": "Get country's keyword metrics",
        "description": "See keyword metrics for a specified country, aggregated across all of Pinterest.\n(Definitions are available from the \"Get delivery metrics definitions\"\n<a href=\"/docs/api/v5/#operation/delivery_metrics/get\">API endpoint</a>).",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "keywords"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/labels": {
      "post": {
        "operationId": "labels/create",
        "summary": "Create labels",
        "description": "<p>\n<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"blank\" target=\"blank\">Closed beta</a>\nThis endpoint is not available to all users.\n</p>\n<p>\n  Apply one or more labels to a campaign.\n  Currently, you can apply brand and custom labels. Future releases will provide more options.\n\n  <b>Note:</b> You can only apply one brand label to a campaign. You can apply 30 custom labels to a campaign.\n </p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "labels"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "get": {
        "operationId": "labels/list",
        "summary": "List labels",
        "description": "<p>\n  <a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"blank\" target=\"blank\">Closed beta</a>\n  This endpoint is not available to all users.\n</p>\n<p>\n  See a list of labels for assets that your account owns, and filter the list by different criteria.\n</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "labels"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "labels/update",
        "summary": "Update labels",
        "description": "<p>\n  <a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"blank\" target=\"blank\">Closed beta</a>\n  This endpoint is not available to all users.\n</p>\n<p>\n  Change the properties of one or more labels.\n</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "labels"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms": {
      "get": {
        "operationId": "lead_forms/list",
        "summary": "List lead forms",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nList lead forms associated with an ad account ID.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "lead_forms"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "lead_forms/create",
        "summary": "Create lead forms",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nCreate lead forms. Lead forms are used in lead ads and allow you to control what text appears on the lead form\u2019s description, questions and confirmation sections.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "lead_forms"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "lead_forms/update",
        "summary": "Update lead forms",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nUpdate lead forms. Lead ads help you reach people who are actively looking for, and interested in, your goods and services. The lead form can be associated with an ad to allow people to fill out the form.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/busine[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "lead_forms"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}": {
      "get": {
        "operationId": "lead_form/get",
        "summary": "Get lead form by id",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nGets a lead form given it's ID. It must also be associated with the provided ad account ID.\n\nFor more, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/lead-ads\">Lead ads</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "lead_forms"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}/test": {
      "post": {
        "operationId": "lead_form_test/create",
        "summary": "Create lead form test data",
        "description": "Create lead form test data based on the list of answers provided as part of the body.\n- List of answers should follow the questions creation order.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "lead_forms"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads/subscriptions": {
      "get": {
        "operationId": "ad_accounts_subscriptions/get_list",
        "summary": "Get lead ads subscriptions",
        "description": "Get the advertiser's list of lead ads subscriptions. Only requests for the OWNER or ADMIN of the ad_account will be allowed.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "lead_ads"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "ad_accounts_subscriptions/post",
        "summary": "Create lead ads subscription",
        "description": "Create a lead ads webhook subscription.\nSubscriptions allow Pinterest to deliver lead data from Ads Manager directly to the subscriber. Subscriptions can exist for a specific lead form or at ad account level.\n  - Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n  - Advertisers can set up multiple integrations using ad_account_id + lead_form_id but only one integration per unique records.\n  - For data security, egress lead data is encrypted with [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "lead_ads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads/subscriptions/{subscription_id}": {
      "get": {
        "operationId": "ad_accounts_subscriptions/get_by_id",
        "summary": "Get lead ads subscription by ID",
        "description": "Get an existing lead ads webhook subscription by ID.\n  - Only requests for the OWNER or ADMIN of the ad_account will be allowed.'",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "lead_ads"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "ad_accounts_subscriptions/del_by_id",
        "summary": "Delete lead ads subscription",
        "description": "Delete an existing lead ads webhook subscription by ID.\n  - Only requests for the OWNER or ADMIN of the ad_account will be allowed.'",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "lead_ads"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads_export": {
      "post": {
        "operationId": "leads_export/create",
        "summary": "Create a request to export leads collected from a lead ad",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nCreate an export of leads collected from a lead ad. This returns a lead_export_id  token that you can use to download the export when it is ready.\n\nNote: Lead ad data will be available up to 30 days after the lead has been submitted.\n\nFor more, see <a class=\"reference external\" href=\"https[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "leads_export"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/leads_export/{leads_export_id}": {
      "get": {
        "operationId": "leads_export/get",
        "summary": "Get the lead export from the lead export create call",
        "description": "<strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>\n\nGet the export of leads collected from a lead ad. This returns a URL to a list of lead export given a lead_export_id token returned from the create a lead export call. You can use the URL to download the report.\n\nNote: Lead ad data will be available up to 30 days after the lead has been submitt[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "leads_export"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/mmm_reports": {
      "get": {
        "operationId": "analytics/get_mmm_report",
        "summary": "Get advertiser Marketing Mix Modeling (MMM) report.",
        "description": "Get an mmm report for an ad account. This returns a URL to an mmm metrics report given a token returned from the\ncreate mmm report endpoint.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "analytics/create_mmm_report",
        "summary": "Create a request for a Marketing Mix Modeling (MMM) report",
        "description": "This creates an asynchronous mmm report based on the given request. It returns a token that you can use to download\nthe report when it is ready. NOTE: An additional limit of 5 queries per minute per advertiser applies to this endpoint while it's in beta release.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/order_lines": {
      "get": {
        "operationId": "order_lines/list",
        "summary": "Get order lines",
        "description": "List existing order lines associated with an ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "order_lines"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/order_lines/{order_line_id}": {
      "get": {
        "operationId": "order_lines/get",
        "summary": "Get order line",
        "description": "Get a specific existing order line associated with an ad account.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "order_lines"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/pins/analytics": {
      "get": {
        "operationId": "ad_pins/analytics",
        "summary": "Get pins analytics",
        "description": "Get analytics for the pins given a campaign and pins in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n- If granularity is not HOUR, the furthest back[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "campaigns"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions": {
      "post": {
        "operationId": "product_group_promotions/create",
        "summary": "Create product group promotions",
        "description": "Add one or more product groups from your catalog to an existing ad group. (Product groups added to an ad group are a 'product group promotion.')",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "product_group_promotions"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "product_group_promotions/update",
        "summary": "Update product group promotions",
        "description": "Update multiple existing Product Group Promotions (by product_group_id)",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "product_group_promotions"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "get": {
        "operationId": "product_group_promotions/list",
        "summary": "Get product group promotions",
        "description": "List existing product group promotions associated with an ad account.\n\nInclude either ad_group_id or product_group_promotion_ids in your request.\n\n<b>Note:</b> ad_group_ids and product_group_promotion_ids are mutually exclusive parameters.\nOnly provide one. If multiple options are provided, product_group_promotion_ids takes precedence over ad_group_ids. If none are provided, the endpoint returns an error.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "product_group_promotions"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}": {
      "get": {
        "operationId": "product_group_promotions/get",
        "summary": "Get a product group promotion by id",
        "description": "Get a product group promotion by id",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "product_group_promotions"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/product_groups/analytics": {
      "get": {
        "operationId": "product_groups/analytics",
        "summary": "Get product group analytics",
        "description": "Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.\n  - If granularity is not HOUR, you can pull data fro[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "product_group_promotions"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/promotions": {
      "get": {
        "operationId": "promotions/list",
        "summary": "Get promotions",
        "description": "Gets all promotions associated with an ad account ID that can be applied to an ad group. Can be either internally-saved promotions or external promotions imported from a commerce integration.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "promotions"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "promotions/create",
        "summary": "Create promotions",
        "description": "Create multiple new promotions.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "promotions"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "promotions/update",
        "summary": "Update promotions",
        "description": "Update multiple promotions.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "promotions"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/promotions/{promotion_id}": {
      "get": {
        "operationId": "promotions/get",
        "summary": "Get promotion by id",
        "description": "Get a promotion by its Pinterest-specific id. It must be associated with the provided ad account id.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "promotions"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "promotions/delete",
        "summary": "Delete promotion by id",
        "description": "Delete a promotion within Pinterest.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "promotions"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/reports": {
      "get": {
        "operationId": "analytics/get_report",
        "summary": "Get the account analytics report created by the async call",
        "description": "This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report. The link is valid for five minutes and the report is valid for one hour.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business A[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "analytics/create_report",
        "summary": "Create async request for an account analytics report",
        "description": "This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Busi[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/reports/brand_category_sku": {
      "get": {
        "operationId": "analytics/get_conversion_product_report",
        "summary": "Get advertiser brand, category, SKU report",
        "description": "<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"blank\" target=\"blank\">Restricted</a>\nGet a brand, category, SKU report for an ad account. This call returns the URL for the report that matches the token returned in the request to the Create brand, category, SKU report endpoint.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "analytics/create_conversion_product_report",
        "summary": "Create a request for a brand, category, SKU report",
        "description": "<a href=\"/docs/getting-started/using-beta-and-restricted-features/\" target=\"blank\" target=\"blank\">Restricted</a>\nThis creates an asynchronous brand, category, SKU report based on the given request. This request returns a token that you can use to download the report when it is ready.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/sandbox": {
      "delete": {
        "operationId": "sandbox/delete",
        "summary": "Delete ads data for ad account in API Sandbox",
        "description": "Delete an ad account and all the ads data associated with that account.\nA string message is returned indicating the status of the delete operation.\n\nNote: This endpoint is only allowed in the Pinterest API Sandbox (https://api-sandbox.pinterest.com/v5).\nGo to /docs/developer-tools/sandbox/ for more information.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/accounts": {
      "get": {
        "operationId": "ssio_accounts/get",
        "summary": "Get Salesforce account details including bill-to information.",
        "description": "Get Salesforce account details including bill-to information to be used in insertion orders process for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders": {
      "post": {
        "operationId": "ssio_insertion_order/create",
        "summary": "Create insertion order through SSIO.",
        "description": "Create insertion order through SSIO for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "ssio_insertion_order/edit",
        "summary": "Edit insertion order through SSIO.",
        "description": "Edit insertion order through SSIO for <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders/status": {
      "get": {
        "operationId": "ssio_insertion_orders_status/get_by_ad_account",
        "summary": "Get insertion order status by ad account id.",
        "description": "Get insertion order status for account id <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/insertion_orders/{pin_order_id}/status": {
      "get": {
        "operationId": "ssio_insertion_orders_status/get_by_pin_order_id",
        "summary": "Get insertion order status by pin order id.",
        "description": "Get insertion order status for pin order id <code>pin_order_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/ssio/order_lines": {
      "get": {
        "operationId": "ssio_order_lines/get_by_ad_account",
        "summary": "Get Salesforce order lines by ad account id.",
        "description": "Get Salesforce order lines for account id <code>ad_account_id</code>.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Finance, Campaign.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "billing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/targeting_analytics": {
      "get": {
        "operationId": "ad_account_targeting_analytics/get",
        "summary": "Get targeting analytics for an ad account",
        "description": "Get targeting analytics for an ad account.\nFor the requested account and metrics, the response will include the requested metric information\n(e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. \"age_bucket\") for applicable values (e.g. \"45-49\"). <p/>\n- The token's user_account must either be the Owner of the specified ad account, or have one\nof the necessary roles granted to them via\n<a href=\"https://help.pinterest.com/en/business/article/share-and-manage-[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/targeting_templates": {
      "get": {
        "operationId": "targeting_template/list",
        "summary": "List targeting templates",
        "description": "Get a list of the targeting templates in the specified <code>ad_account_id</code>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "targeting_template"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "targeting_template/create",
        "summary": "Create targeting templates",
        "description": "<p>Targeting templates allow advertisers to save a set of targeting details including audience lists,\n keywords & interest, demographics, and placements to use more than once during the campaign creation process.</p>\n <p>Templates can be used to build out basic targeting criteria that you plan to use across campaigns and to reuse\n  performance targeting from prior campaigns for new campaigns.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "targeting_template"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "targeting_template/update",
        "summary": "Update targeting templates",
        "description": "<p>Update the targeting template given advertiser ID and targeting template ID</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "targeting_template"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/templates": {
      "get": {
        "operationId": "templates/list",
        "summary": "List templates",
        "description": "Gets all Templates associated with an ad account ID.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/ad_accounts/{ad_account_id}/templates/{template_id}/reports": {
      "post": {
        "operationId": "analytics/create_template_report",
        "summary": "Create async request for an analytics report using a template",
        "description": "\n  This takes a template ID and an optional custom timeframe and\n  constructs an asynchronous report based on the template. It returns\n  a token that you can use to download the report when it is ready.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "ad_accounts"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/terms_of_service": {
      "get": {
        "operationId": "terms_of_service/get",
        "summary": "Get terms of service",
        "description": "Get the text of the terms of service and see whether the advertiser has accepted the terms of service.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "terms_of_service"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/advanced_auction/items/get": {
      "post": {
        "operationId": "advanced_auction_items_get/post",
        "summary": "Get item bid options (POST)",
        "description": "Get the bid options for a batch of retail catalog items.\n\nThe catalog must be owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a> By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "advanced_auction"
        ],
        "x-ratelimit-category": "advanced_auction_read",
        "x-sandbox": "enabled"
      }
    },
    "/advanced_auction/items/submit": {
      "post": {
        "operationId": "advanced_auction_items_submit/post",
        "summary": "Operate on item level bid options",
        "description": "This endpoint supports multiple operations on a set of one or more bid options (bid price and bid adjustments for targeting categories) for retail catalog items. These advanced auction settings are applied in campaigns using objective_type `CATALOG_SALES` and ad groups using bid_strategy_type `MAX_BID`.\n\nThe catalog must be owned by the \"operation user_account\". <a href=\"/docs/api-features/modify-items-in-batch/\" target=\"_blank\">See detailed documentation here.</a[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write",
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "advanced_auction"
        ],
        "x-ratelimit-category": "advanced_auction_write",
        "x-sandbox": "enabled"
      }
    },
    "/boards": {
      "post": {
        "operationId": "boards/create",
        "summary": "Create board",
        "description": "Create a board owned by the \"operation user_account\".\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n* By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      },
      "get": {
        "operationId": "boards/list",
        "summary": "List boards",
        "description": "Get a list of the boards owned by the \"operation user_account\" + group boards where this account is a collaborator\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\nOptional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.\n* If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) wi[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/boards/{board_id}": {
      "get": {
        "operationId": "boards/get",
        "summary": "Get board",
        "description": "Get a board owned by the operation user_account - or a group board that has been shared with this account.\n* Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n* By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      },
      "delete": {
        "operationId": "boards/delete",
        "summary": "Delete board",
        "description": "Delete a board owned by the \"operation user_account\".\n* Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n* By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "boards/update",
        "summary": "Update board",
        "description": "Update a board owned by the \"operating user_account\".\n* Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n* By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/boards/{board_id}/pins": {
      "get": {
        "operationId": "boards/list_pins",
        "summary": "List Pins on board",
        "description": "Get a list of the Pins on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/boards/{board_id}/sections": {
      "get": {
        "operationId": "board_sections/list",
        "summary": "List board sections",
        "description": "Get a list of all board sections from a board owned by the \"operation user_account\" - or a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "board_sections/create",
        "summary": "Create board section",
        "description": "Create a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}": {
      "patch": {
        "operationId": "board_sections/update",
        "summary": "Update board section",
        "description": "Update a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      },
      "delete": {
        "operationId": "board_sections/delete",
        "summary": "Delete board section",
        "description": "Delete a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/boards/{board_id}/sections/{section_id}/pins": {
      "get": {
        "operationId": "board_sections/list_pins",
        "summary": "List Pins on board section",
        "description": "Get a list of the Pins on a board section of a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "boards"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/businesses/employers": {
      "get": {
        "operationId": "get/business_employers",
        "summary": "List business employers for user",
        "description": "Get all of the viewing user's business employers.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/businesses/invites": {
      "patch": {
        "operationId": "respond_business_access_invites",
        "summary": "Accept or decline an invite/request",
        "description": "Accept or decline invites or requests.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/businesses/{business_id}/system_users/{system_user_id}": {
      "patch": {
        "operationId": "system_user/update",
        "summary": "Update a system user information.",
        "description": "Update a system user information such as name.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/assets/{asset_id}/members": {
      "get": {
        "operationId": "business_asset_members/get",
        "summary": "Get members with access to asset",
        "description": "Get all the members the requesting business has granted access to on the given asset.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/assets/{asset_id}/partners": {
      "get": {
        "operationId": "business_asset_partners/get",
        "summary": "Get partners with access to asset",
        "description": "Get all the partners the requesting business has granted access to on the given asset.\nNote: If the asset has been shared with you, an empty array will be returned. This is because an asset shared with\nyou cannot be shared with a different partner.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/invites/assets/access": {
      "post": {
        "operationId": "create_asset_invites",
        "summary": "Update invite/request with an asset permission",
        "description": "Assign asset permissions information to an existing invite/request. Can be used to:\n- Request access to a partner's asset. Note: This is only for when no existing partnership exists. If an existing\n  partnership exists, use \"Create a request to access an existing partner's assets\" to request access to your\n  partner's assets.\n    - invite_type=\"PARTNER_REQUEST\"\n- Invite a partner to access your business assets. Note: This is only for when there is no existing par[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/requests/assets/access": {
      "post": {
        "operationId": "asset_access_requests/create",
        "summary": "Create a request to access an existing partner's assets.",
        "description": "Create a request to access an existing partner's assets with the specified permissions. The request will be sent to the partner for approval. The assets that can be requested are ad accounts and profiles.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/members": {
      "get": {
        "operationId": "get/business_members",
        "summary": "Get business members",
        "description": "Get all members of the specified business.\nThe return response will include the member's business_role and assets they have access to if assets_summary=TRUE",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "update/business_memberships",
        "summary": "Update member's business role",
        "description": "Update a member's business role within the business.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "delete_business_membership",
        "summary": "Terminate business memberships",
        "description": "Terminate memberships between the specified members and your business.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/businesses/{business_id}/assets": {
      "get": {
        "operationId": "business_assets/get",
        "summary": "List business assets",
        "description": "Get all the assets the requesting business has access to. This includes assets the business owns and assets the business has access to through partnerships.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/members/{member_id}/assets": {
      "get": {
        "operationId": "business_member_assets/get",
        "summary": "Get assets assigned to a member",
        "description": "Get assets on which you assigned asset permissions to the given member. Can be used to:\n- get all assets, regardless of asset type or\n- get assets of one asset type by using the asset_type query.\nThe return response will include the permissions the member has to that asset and the asset type.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/members/assets/access": {
      "patch": {
        "operationId": "business_members_asset_access/update",
        "summary": "Assign/Update member asset permissions",
        "description": "Grant multiple members access to assets and/or update multiple member's exisiting permissions to an asset.\nNote: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of the type PROFILE.\n",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "business_members_asset_access/delete",
        "summary": "Delete member access to asset",
        "description": "Terminate multiple members' access to an asset.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/invites": {
      "get": {
        "operationId": "get/invites",
        "summary": "Get invites/requests",
        "description": "Get the membership/partnership invites and/or requests for the authorized user.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "post": {
        "operationId": "create_membership_or_partnership_invites",
        "summary": "Create invites or requests",
        "description": "Create batch invites or requests. Can create batch invites or requests as described below.\n- Invite members to join the business. This would required specifying the following:\n    - invite_type=\"MEMBER_INVITE\"\n    - business_role=\"EMPLOYEE\" OR business_role=\"BIZ_ADMIN\" (To learn more about business roles, visit\n    https://help.pinterest.com/en/business/article/profile-permissions-in-business-access.)\n    - members\n- Invite partners to access your business ass[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "cancel_invites_or_requests",
        "summary": "Cancel invites/requests",
        "description": "Cancel membership/partnership invites and/or requests.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_invite"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/partners/assets": {
      "patch": {
        "operationId": "update_partner_asset_access_handler_impl",
        "summary": "Assign/Update partner asset permissions",
        "description": "Grant multiple partners access to assets and/or update multiple partner's exisiting permissions to an asset.\nIf your partner already had permissions on the asset, they will be overriden with the new permissions you assign to them.\nTo learn more about permission levels, visit https://help.pinterest.com/en/business/article/business-manager-overview\n\nNote: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be\napplicabl[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "delete_partner_asset_access_handler_impl",
        "summary": "Delete partner access to asset",
        "description": "Terminate multiple partners' access to an asset. If\n- partner_type=INTERNAL: You will terminate a partner's asset access to your business assets.\n- partner_type=EXTERNAL: You will terminate your own access to your partner's business assets.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/partners/{partner_id}/assets": {
      "get": {
        "operationId": "business_partner_asset_access/get",
        "summary": "Get assets assigned to a partner or assets assigned by a partner",
        "description": "Can be used to get the business assets your partner has granted you access to or the business assets you have\ngranted your partner access to. If you specify:\n- partner_type=INTERNAL, you will retrieve your business assets that the partner has access to.\n- partner_type=EXTERNAL, you will retrieve the partner's business assets that the partner has granted you access to.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/partners": {
      "get": {
        "operationId": "get/business_partners",
        "summary": "Get business partners",
        "description": "Get all partners of the specified business.\n\nIf the assets_summary=TRUE and:\n- partner_type=INTERNAL, the business assets returned are your business assets the partner has access to.\n- partner_type=EXTERNAL, the business assets returned are your partner's business assets the partner has granted you\n  access to.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "delete_business_partners",
        "summary": "Terminate business partnerships",
        "description": "Terminate partnerships between the specified partners and your business.\nNote: You may only batch terminate partners of the same partner type.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/audiences": {
      "get": {
        "operationId": "shared_audiences_for_business/list",
        "summary": "List received audiences for a business",
        "description": "Get a list of received audiences for the given business.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/audiences/shared/accounts": {
      "get": {
        "operationId": "business_account_audiences_shared_accounts/list",
        "summary": "List accounts with access to an audience owned by a business",
        "description": "List all ad accounts and/or businesses that have access to a specific audience.\nThe audience must either be owned by an ad account in the requesting business, or it must have been shared with the requesting business.\nIf the requesting business is not the owner of the audience, only ad accounts owned by the requesting business will be returned.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/audiences/ad_accounts/shared": {
      "patch": {
        "operationId": "update_business_to_ad_account_shared_audience",
        "summary": "Update audience sharing from a business to ad accounts",
        "description": "From a business, share a specific audience with other ad account(s), or revoke access to a previously shared audience. <ul> <li>If the business is the owner of the audience, it can share with any ad account within the same business hierarchy.</li> <li>If the business is the recipient of the audience, it can share with any of its owned ad accounts.</li> </ul> This endpoint is not available to all apps.<a href='/docs/getting-started/using-beta-and-restricted-features/'>Lear[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/audiences/businesses/shared": {
      "patch": {
        "operationId": "update_business_to_business_shared_audience",
        "summary": "Update audience sharing between businesses",
        "description": "From a business, share a specific audience with another business account, or revoke access to a previously shared audience. Only the audience owner can share the audience with other businesses, and the recipient business must be within the same business hierarchy.<br> This endpoint is not available to all apps.<a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "audience_sharing"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/businesses/{business_id}/asset_groups": {
      "post": {
        "operationId": "asset_group/create",
        "summary": "Create a new asset group.",
        "description": "Create a new asset group with the specified parameters.\n- An <a href=\"https://help.pinterest.com/en/business/article/asset-groups\">asset group</a> is a custom group of assets based on how you\u2019d like to manage your accounts.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "asset_group/update",
        "summary": "Update asset groups.",
        "description": "Update a batch of asset groups with the specified parameters.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "asset_group/delete",
        "summary": "Delete asset groups.",
        "description": "Delete a batch of asset groups.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_assets"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/business_access/business_hierarchy/{business_hierarchy_id}/brand_accounts": {
      "post": {
        "operationId": "brand_accounts/create",
        "summary": "Create a Brand Account",
        "description": "Create a Brand Account that will be a child business of a business hierarchy. Request must contain name, username, and country.",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/business_access/business_hierarchy/{business_hierarchy_id}/brand_accounts/{brand_account_id}": {
      "patch": {
        "operationId": "brand_accounts/update",
        "summary": "Update a Brand Account",
        "description": "Update an existing Brand Account",
        "security": [
          {
            "pinterest_oauth2": [
              "biz_access:read",
              "biz_access:write"
            ]
          }
        ],
        "tags": [
          "business_access_relationships"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/catalogs": {
      "get": {
        "operationId": "catalogs/list",
        "summary": "List catalogs",
        "description": "Fetch catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busine[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "catalogs/create",
        "summary": "Create catalog",
        "description": "Create a new catalog owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/available_filter_values": {
      "get": {
        "operationId": "catalogs/available_filter_values",
        "summary": "List available filter values",
        "description": "Get the available filter attributes and values associated with a given feed or catalog owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n- <code>country</code>, <code>language</code>, and <code>feed_id</code> are only used in retail catalogs.\n- Note: It is not guaranteed that all available filter values will be returned. Instead this endpoint will return values from a sample of up to 1000 items.\n\nOptional[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/feeds": {
      "get": {
        "operationId": "feeds/list",
        "summary": "List feeds",
        "description": "Fetch feeds owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/business/[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "feeds/create",
        "summary": "Create feed",
        "description": "Create a new feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nPlease, be aware that \"default_country\"\nand \"default_locale\" are not required in the spec for forward compatibility\nbut for now the API will not accept requests without those fields.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}": {
      "get": {
        "operationId": "feeds/get",
        "summary": "Get feed",
        "description": "Get a single feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/bus[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "feeds/update",
        "summary": "Update feed",
        "description": "Update a feed owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busines[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      },
      "delete": {
        "operationId": "feeds/delete",
        "summary": "Delete feed",
        "description": "Delete a feed owned by the \"operating user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/busines[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}/ingest": {
      "post": {
        "operationId": "feeds/ingest",
        "summary": "Ingest feed items",
        "description": "Ingest items for a given feed owned by the \"operation user_account\".\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">B[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/feeds/{feed_id}/processing_results": {
      "get": {
        "operationId": "feed_processing_results/list",
        "summary": "List feed processing results",
        "description": "Fetch a feed processing results owned by the \"operation user_account\". Please note that for now the bookmark parameter is not functional and only the first page will be available until it is implemented in some release in the near future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/processing_results/{processing_result_id}/item_issues": {
      "get": {
        "operationId": "items_issues/list",
        "summary": "List item issues",
        "description": "List item validation issues for a given feed processing result owned by the \"operation user_account\". Up to 20 random samples of affected items are returned for each error and warning code. Please note that for now query parameters 'item_numbers' and 'item_validation_issue' cannot be used simultaneously until it is implemented in some release in the future.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_feeds"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/items": {
      "post": {
        "operationId": "items/post",
        "summary": "Get catalogs items (POST)",
        "description": "Get the items of the catalog owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_items"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/items/batch": {
      "post": {
        "operationId": "items_batch/post",
        "summary": "Operate on item batch",
        "description": "This endpoint supports multiple operations on a set of one or more catalog items owned by the \"operation user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad account[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_items"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/items/batch/{batch_id}": {
      "get": {
        "operationId": "items_batch/get",
        "summary": "Get item batch status",
        "description": "Get a single catalogs items batch owned by the \"operating user_account\". <a href=\"/docs/api-features/shopping-overview/#Update%20items%20in%20batch\" target=\"_blank\">See detailed documentation here.</a>\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as t[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          },
          {
            "client_credentials": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_items"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/product_groups/multiple": {
      "delete": {
        "operationId": "catalogs_product_groups/delete_many",
        "summary": "Delete product groups",
        "description": "Delete product groups owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.pinterest.com/en[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "catalogs_product_groups/create_many",
        "summary": "Create product groups",
        "description": "Create product group to use in Catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://hel[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/product_groups": {
      "get": {
        "operationId": "catalogs_product_groups/list",
        "summary": "List product groups",
        "description": "Get a list of product groups for a given Catalogs Feed Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "catalogs_product_groups/create",
        "summary": "Create product group",
        "description": "Create product group to use in Catalogs owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://hel[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}": {
      "get": {
        "operationId": "catalogs_product_groups/get",
        "summary": "Get product group",
        "description": "Get a singe product group for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the followi[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      },
      "delete": {
        "operationId": "catalogs_product_groups/delete",
        "summary": "Delete product group",
        "description": "Delete a product group owned by the \"operation user_account\" from being in use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "catalogs_product_groups/update",
        "summary": "Update single product group",
        "description": "Update product group owned by the \"operation user_account\" to use in Catalogs.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://hel[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_write",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/product_counts": {
      "get": {
        "operationId": "catalogs_product_groups/product_counts_get",
        "summary": "Get product counts",
        "description": "Get a product counts for a given Catalogs Product Group owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a hr[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/product_groups/{product_group_id}/products": {
      "get": {
        "operationId": "catalogs_product_group_pins/list",
        "summary": "List products by product group",
        "description": "Get a list of product pins for a given Catalogs Product Group Id owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the follow[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "catalogs:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/products/get_by_product_group_filters": {
      "post": {
        "operationId": "products_by_product_group_filter/list",
        "summary": "List products by filter",
        "description": "List products Pins owned by the \"operation user_account\" that meet the criteria specified in the Catalogs Product Group Filter given in the request.\n- This endpoint has been implemented in POST to allow for complex filters. This specific POST endpoint is designed to be idempotent.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "catalogs:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "catalog_product_groups"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "enabled"
      }
    },
    "/catalogs/reports": {
      "post": {
        "operationId": "reports/create",
        "summary": "Build catalogs report",
        "description": "Async request to create a report of the catalog owned by the \"operation user_account\". This endpoint generates a report upon receiving the first approved request of the day. Any following requests with identical parameters will yield the same report even if data has changed.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_account[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_reports"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "disabled"
      },
      "get": {
        "operationId": "reports/get",
        "summary": "Get catalogs report",
        "description": "This returns a URL to a report given a token returned from <a href='/docs/api/v5/#operation/reports/create'>Build catalogs report</a>. You can use the URL to download the report.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\"[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_reports"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "disabled"
      }
    },
    "/catalogs/reports/stats": {
      "get": {
        "operationId": "reports/stats",
        "summary": "List report stats",
        "description": "List aggregated numbers of issues for a catalog owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"htt[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalog_reports"
        ],
        "x-ratelimit-category": "catalogs_read",
        "x-sandbox": "disabled"
      }
    },
    "/integrations/commerce": {
      "post": {
        "operationId": "integrations_commerce/post",
        "summary": "Create commerce integration",
        "description": "Create commerce integration metadata to link an external business ID with a Pinterest merchant & ad account.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/integrations/commerce/{external_business_id}": {
      "get": {
        "operationId": "integrations_commerce/get",
        "summary": "Get commerce integration",
        "description": "Get commerce integration metadata associated with the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      },
      "patch": {
        "operationId": "integrations_commerce/patch",
        "summary": "Update commerce integration",
        "description": "Update commerce integration metadata for the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "integrations_commerce/del",
        "summary": "Delete commerce integration",
        "description": "Delete commerce integration metadata for the given external business ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "disabled"
      }
    },
    "/integrations/logs": {
      "post": {
        "operationId": "integrations_logs/post",
        "summary": "Receives batched logs from integration applications.",
        "description": "This endpoint receives batched logs from integration applications on partner platforms.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_write",
        "x-sandbox": "enabled"
      }
    },
    "/integrations": {
      "get": {
        "operationId": "integrations/get_list",
        "summary": "Get integration metadata list",
        "description": "Get integration metadata list.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/integrations/{id}": {
      "get": {
        "operationId": "integrations/get_by_id",
        "summary": "Get integration metadata",
        "description": "Get integration metadata by ID.\nNote: If you're interested in joining the beta, please reach out to your Pinterest account manager.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "integrations"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    },
    "/media": {
      "get": {
        "operationId": "media/list",
        "summary": "List media uploads",
        "description": "List media uploads filtered by given parameters.\n\n**[Learn more](/docs/api-features/creating-boards-and-pins/#creating-video-pins)** about video Pin creation.",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read"
            ]
          }
        ],
        "tags": [
          "media"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      },
      "post": {
        "operationId": "media/create",
        "summary": "Register media upload",
        "description": "Register your intent to upload media.\n\nThe response includes all of the information needed to upload the media to Pinterest.\n\nTo upload the media, make an HTTP POST request (using `curl`, for example) to `upload_url` using the `Content-Type` header value. Send the media file's contents as the request's `file` parameter and also include all of the parameters from `upload_parameters`.\n\n**[Learn more](/docs/api-features/creating-boards-and-pins/#creating-video-pins)** [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "tags": [
          "media"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/media/{media_id}": {
      "get": {
        "operationId": "media/get",
        "summary": "Get media upload details",
        "description": "Get details for a registered media upload, including its current status.\n\n**[Learn more](/docs/api-features/creating-boards-and-pins/#creating-video-pins)** about video Pin creation.",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read"
            ]
          }
        ],
        "tags": [
          "media"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/notifications": {
      "post": {
        "operationId": "notification/post",
        "summary": "Receive notifications from external partners.",
        "description": "Used by third-party partners to send notifications to Pinterest. These notifications could be specific for your use-case or generic notification that are accepted by Pinterests' systems. This API is gated and you need to request access to this feature.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "notification"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/oauth/conversion_token": {
      "post": {
        "operationId": "oauth/conversion_token",
        "summary": "Generate OAuth access token for conversion API",
        "description": "Generate a new and long-lived OAuth access token dedicated for sending conversions using a valid access token.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:write"
            ]
          }
        ],
        "tags": [
          "oauth"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/oauth/token": {
      "post": {
        "operationId": "oauth/token",
        "summary": "Generate OAuth access token",
        "description": "Generate a new OAuth access token using an authorization code; or refresh an existing one using a continuous refresh token.\n\nFollow the complete steps for <a href='/docs/getting-started/set-up-authentication-and-authorization/' target='blank'>requesting and refreshing tokens</a>.\n\n<strong>Note:</strong> If your app was created <strong>before September 25, 2025</strong>, make sure to set the <code>continuous_refresh</code> parameter to <code>true</code> to use the cont[...]",
        "security": [
          {
            "basic": []
          }
        ],
        "tags": [
          "oauth"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/oauth/token/revoke": {
      "post": {
        "operationId": "token/revoke",
        "summary": "Revoke a token",
        "description": "Revokes an access or refresh token. Only tokens issued for system users are currently supported. Revoked tokens become immediately invalid and unusable.",
        "security": [
          {
            "basic": []
          }
        ],
        "tags": [
          "oauth"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/pins": {
      "post": {
        "operationId": "pins/create",
        "summary": "Create Pin",
        "description": "\n Create a Pin on a board or board section owned by the \"operation user_account\".\n\n Note: If the current \"operation user_account\" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).\n\n- This functio[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      },
      "get": {
        "operationId": "pins/list",
        "summary": "List Pins",
        "description": "\n    Get a list of the Pins owned by the \"operation user_account\".\n    - By default, the \"operation user_account\" is the token user_account.\n    - All Pins owned by the \"operation user_account\" are included, regardless of who owns the board they are on.\n\n    Optional: Business Access: Specify an `ad_account_id` to use the owner of that ad_account as the \"operation user_account\".\n\n    Disclaimer: There are known performance issues when filtering by field `cr[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/pins/{pin_id}": {
      "get": {
        "operationId": "pins/get",
        "summary": "Get Pin",
        "description": "\n  Get a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n  - By default, the \"operation user_account\" is the token user_account.\n\n  Optional: Business Access: Specify an `ad_account_id` (obtained via [List ad accounts](/docs/api/v5/#operation/ad_accounts/list)) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following [Bus[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      },
      "patch": {
        "operationId": "pins/update",
        "summary": "Update Pin",
        "description": "Update a pin owned by the \"operating user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an `ad_account_id` (obtained via [List ad accounts](/docs/api/v5/#operation/ad_accounts/list)) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following [Business Access](https://help.pinterest.com/en/business/article/share[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      },
      "delete": {
        "operationId": "pins/delete",
        "summary": "Delete Pin",
        "description": "\n  Delete a Pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n  - By default, the \"operation user_account\" is the token user_account.\n\n  Optional: Business Access: Specify an `ad_account_id` (obtained via [List ad accounts](/docs/api/v5/#operation/ad_accounts/list)) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/pins/{pin_id}/analytics": {
      "get": {
        "operationId": "pins/analytics",
        "summary": "Get Pin analytics",
        "description": "Get analytics for a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=\"/docs/api/v5/#operation/ad_accounts/list\">List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must [...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/pins/analytics": {
      "get": {
        "operationId": "multi_pins/analytics",
        "summary": "Get multiple Pin analytics",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>\n\nGet analytics for multiple pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- The maximum number of pins supported in a single request is 100.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: S[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/pins/{pin_id}/save": {
      "post": {
        "operationId": "pins/save",
        "summary": "Save Pin",
        "description": "Save a Pin on a board or board section owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the following <a href=\"https://help.p[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "tags": [
          "pins"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/resources/ad_account_countries": {
      "get": {
        "operationId": "ad_account_countries/get",
        "summary": "Get ad accounts countries",
        "description": "Get Ad Accounts countries",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/resources/delivery_metrics": {
      "get": {
        "operationId": "delivery_metrics/get",
        "summary": "Get available metrics' definitions",
        "description": "Get the definitions for ads and organic metrics available across both synchronous and asynchronous report endpoints.\nThe `display_name` attribute will match how the metric is named in our native tools like Ads Manager.\nSee <a href='/docs/api-features/analytics-overview/'>Organic Analytics</a> and <a href='/docs/api-features/ads-reporting/'>Ads Analytics</a> for more information.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read",
              "pins:read",
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read",
              "pins:read",
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/resources/lead_form_questions": {
      "get": {
        "operationId": "lead_form_questions/get",
        "summary": "Get lead form questions",
        "description": "Get a list of all lead form question type names. Some questions might not be used.\n\n<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/resources/metrics_ready_state": {
      "get": {
        "operationId": "metrics_ready_state/get",
        "summary": "Get metrics ready state",
        "description": "Learn whether conversion or non-conversion metrics are finalized and ready to query.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_analytics",
        "x-sandbox": "enabled"
      }
    },
    "/resources/targeting/interests/{interest_id}": {
      "get": {
        "operationId": "interest_targeting_options/get",
        "summary": "Get interest details",
        "description": "<p>Get details of a specific interest given interest ID.</p> <p>Click <a href=\"https://docs.google.com/spreadsheets/d/1HxL-0Z3p2fgxis9YBP2HWC3tvPrs1hAuHDRtH-NJTIM/edit#gid=118370875\" target=\"_blank\">here</a> for a spreadsheet listing interests and their IDs.</p>",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/resources/targeting/{targeting_type}": {
      "get": {
        "operationId": "targeting_options/get",
        "summary": "Get targeting options",
        "description": "<p>You can use targeting values in ads placement to define your intended audience. </p> <p>Targeting metrics are organized around targeting specifications.</p> <p>For more information on ads targeting, see <a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>.</p>\n<p><b>Sample return:</b></p> <pre class=\"literal-block\"> [{&quot;36313&quot;: &quot;Australia: Moreton Bay - North[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "resources"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/search/boards": {
      "get": {
        "operationId": "search_user_boards/get",
        "summary": "Search user's boards",
        "description": "Search for boards for the \"operation user_account\". This includes boards of all board types.\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:read_secret"
            ]
          },
          {
            "client_credentials": [
              "boards:read",
              "boards:read_secret"
            ]
          }
        ],
        "tags": [
          "search"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      }
    },
    "/search/pins": {
      "get": {
        "operationId": "search_user_pins/list",
        "summary": "Search user's Pins",
        "description": "Search for pins for the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:read_secret",
              "pins:read",
              "pins:read_secret"
            ]
          }
        ],
        "tags": [
          "search"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      }
    },
    "/search/partner/pins": {
      "get": {
        "operationId": "search_partner_pins",
        "summary": "Search pins by a given search term",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>\n\nGet the top 10 Pins by a given search term.",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "tags": [
          "search"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      }
    },
    "/terms/related": {
      "get": {
        "operationId": "terms_related/list",
        "summary": "List related terms",
        "description": "Get a list of terms logically related to each input term. <p/>\nExample: the term 'workout' would list related terms like 'one song workout', 'yoga workout', 'workout motivation', etc.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "terms"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/terms/suggested": {
      "get": {
        "operationId": "terms_suggested/list",
        "summary": "List suggested terms",
        "description": "Get popular search terms that begin with your input term. <p/>\nExample: 'sport' would return popular terms like 'sports bar' and 'sportswear', but not 'motor sports' since the phrase does not begin with the given term.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "terms"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/trends/keywords/{region}/top/{trend_type}": {
      "get": {
        "operationId": "trending_keywords/list",
        "summary": "List trending keywords",
        "description": "<p>Get the top trending search keywords among the Pinterest user audience.</p> <p>Trending keywords can be used to inform ad targeting, budget strategy, and creative decisions about which products and Pins will resonate with your audience.</p> <p>Geographic, demographic and interest-based filters are available to narrow down to the top trends among a specific audience. Multiple trend types are supported that can be used to identify newly-popular, evergreen or seasonal key[...]",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "keywords"
        ],
        "x-ratelimit-category": "trends_read",
        "x-sandbox": "enabled"
      }
    },
    "/user_account": {
      "get": {
        "operationId": "user_account/get",
        "summary": "Get user account",
        "description": "Get account information for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/getting-started/using-business-access/'>Understanding Business Access</a> for more information.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/user_account/analytics": {
      "get": {
        "operationId": "user_account/analytics",
        "summary": "Get user account analytics",
        "description": "Get analytics for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/user_account/analytics/top_pins": {
      "get": {
        "operationId": "user_account/analytics/top_pins",
        "summary": "Get user account top pins analytics",
        "description": "Gets analytics data about a user's top pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read",
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "pins:read",
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/user_account/analytics/top_video_pins": {
      "get": {
        "operationId": "user_account/analytics/top_video_pins",
        "summary": "Get user account top video pins analytics",
        "description": "Gets analytics data about a user's top video pins (limited to the top 50).\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read",
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "pins:read",
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_analytics",
        "x-sandbox": "disabled"
      }
    },
    "/user_account/businesses": {
      "get": {
        "operationId": "linked_business_accounts/get",
        "summary": "List linked businesses",
        "description": "Get a list of your linked business accounts.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/user_account/followers": {
      "get": {
        "operationId": "followers/list",
        "summary": "List followers",
        "description": "Get a list of your followers.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "enabled"
      }
    },
    "/user_account/following": {
      "get": {
        "operationId": "user_following/get",
        "summary": "List following",
        "description": "Get a list of who a certain user follows.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      }
    },
    "/user_account/following/boards": {
      "get": {
        "operationId": "boards_user_follows/list",
        "summary": "List following boards",
        "description": "Get a list of the boards a user follows. The request returns a board summary object array.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/user_account/following/{username}": {
      "post": {
        "operationId": "follow_user/update",
        "summary": "Follow user",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>.</strong>\n\nUse this request, as a signed-in user, to follow another user.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:write"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "enabled"
      }
    },
    "/user_account/websites": {
      "post": {
        "operationId": "verify_website/update",
        "summary": "Verify website",
        "description": "Verify a website as a signed-in user.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:write"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "disabled"
      },
      "get": {
        "operationId": "user_websites/get",
        "summary": "Get user websites",
        "description": "Get user websites, claimed or not",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      },
      "delete": {
        "operationId": "unverify_website/delete",
        "summary": "Unverify website",
        "description": "Unverifu a website verified by the signed-in user.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:write"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_write",
        "x-sandbox": "disabled"
      }
    },
    "/user_account/websites/verification": {
      "get": {
        "operationId": "website_verification/get",
        "summary": "Get user verification code for website claiming",
        "description": "Get verification code for user to install on the website to claim it.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "disabled"
      }
    },
    "/users/{username}/interests/follow": {
      "get": {
        "operationId": "user_account/followed_interests",
        "summary": "List following interests",
        "description": "Get a list of a user's following interests in one place.",
        "deprecated": true,
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "user_account"
        ],
        "x-ratelimit-category": "org_read",
        "x-sandbox": "enabled"
      }
    },
    "/trends/topics/featured": {
      "get": {
        "operationId": "trends_featured_topics/list",
        "summary": "Get featured topics",
        "description": "  Enables advertisers to pull top five trending topics by interest and market, at full parity with the Pinterest Trends UI.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "product_categories"
        ],
        "x-ratelimit-category": "trends_read",
        "x-sandbox": "disabled"
      }
    },
    "/trends/product_categories/details": {
      "get": {
        "operationId": "trends_product_categories_details/list",
        "summary": "Get product category details",
        "description": "  Enables advertisers to retrieve demographic information, related pins, and trend lines for specified product categories",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "product_categories"
        ],
        "x-ratelimit-category": "trends_read",
        "x-sandbox": "disabled"
      }
    },
    "/trends/product_categories/trending": {
      "get": {
        "operationId": "trends_product_categories_trending/list",
        "summary": "Get a list of growing Shopping Product Categories",
        "description": "  Get a list of growing Shopping Product Categories in ranked order allowing filtering by engagement type, vertical, age, and gender.",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          },
          {
            "client_credentials": [
              "user_accounts:read"
            ]
          }
        ],
        "tags": [
          "product_categories"
        ],
        "x-ratelimit-category": "trends_read",
        "x-sandbox": "disabled"
      }
    },
    "/ad_accounts/{ad_account_id}/conversion_eqs": {
      "get": {
        "operationId": "conversion_eqs/list",
        "summary": "Get event quality score (EQS)",
        "description": "Get the Event Quality Score (EQS) of your conversion signals.\n\n[Event Quality Score](https://help.pinterest.com/en/business/article/eqs) indicates how effective the customer information and event insights (metadata) passed with your web, app and offline conversion events may be at matching to a Pinterest user.",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          },
          {
            "client_credentials": [
              "ads:read"
            ]
          }
        ],
        "tags": [
          "conversion_eqs"
        ],
        "x-ratelimit-category": "ads_read",
        "x-sandbox": "disabled"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "pinterest_oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://www.pinterest.com/oauth/",
            "tokenUrl": "https://api.pinterest.com/v5/oauth/token",
            "scopes": {
              "ads:read": "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write": "Create, update, or delete ads, ad groups, campaigns etc.",
              "billing:read": "See all of your billing data, billing profile, etc.",
              "billing:write": "Create, update, or delete billing data, billing profiles, etc.",
              "biz_access:read": "See business access data",
              "biz_access:write": "Create, update, or delete business access data",
              "boards:read": "See your public boards, including group boards you join",
              "boards:read_secret": "See your secret boards",
              "boards:write": "Create, update, or delete your public boards",
              "boards:write_secret": "Create, update, or delete your secret boards",
              "catalogs:read": "See all of your catalogs data",
              "catalogs:write": "Create, update, or delete your catalogs data",
              "msot:write": "Create measurement source of truth events",
              "pins:read": "See your public Pins",
              "pins:read_secret": "See your secret Pins",
              "pins:write": "Create, update, or delete your public Pins",
              "pins:write_secret": "Create, update, or delete your secret Pins",
              "user_accounts:read": "See your user accounts and followers",
              "user_accounts:write": "Update your user accounts and followers"
            }
          }
        }
      },
      "conversion_token": {
        "type": "http",
        "scheme": "bearer",
        "description": "This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com)."
      },
      "basic": {
        "type": "http",
        "scheme": "basic"
      },
      "client_credentials": {
        "flows": {
          "clientCredentials": {
            "scopes": {
              "ads:read": "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write": "Create, update, or delete ads, ad groups, campaigns etc.",
              "billing:read": "See all of your billing data, billing profile, etc.",
              "billing:write": "Create, update, or delete billing data, billing profiles, etc.",
              "biz_access:read": "See business access data",
              "biz_access:write": "Create, update, or delete business access data",
              "boards:read": "See your public boards, including group boards you join",
              "boards:read_secret": "See your secret boards",
              "boards:write": "Create, update, or delete your public boards",
              "boards:write_secret": "Create, update, or delete your secret boards",
              "catalogs:read": "See all of your catalogs data",
              "catalogs:write": "Create, update, or delete your catalogs data",
              "msot:write": "Create measurement source of truth events",
              "pins:read": "See your public Pins",
              "pins:read_secret": "See your secret Pins",
              "pins:write": "Create, update, or delete your public Pins",
              "pins:write_secret": "Create, update, or delete your secret Pins",
              "user_accounts:read": "See your user accounts and followers",
              "user_accounts:write": "Update your user accounts and followers"
            },
            "tokenUrl": "https://api.pinterest.com/v3/oauth/access_token/"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "account_claiming",
      "description": "Connect Pinterest users to external platform accounts."
    },
    {
      "name": "ad_accounts",
      "description": "View analytical information about advertising.\n\n\nNote: If the current operation_user_account (defined by the access token)\nhas access to another user's Ad Accounts via\n<a href='/docs/getting-started/using-business-access/'>Pinterest Business Access</a>,\nyou can modify your request to use the current operation_user_account's\npermissions to those Ad Accounts by including the ad_account_id in the path\nparameters for the request (e.g. .../?ad_account_id=12345&...)."
    },
    {
      "name": "ad_groups",
      "description": "View, create or update ad groups."
    },
    {
      "name": "ads",
      "description": "View, create or update ads."
    },
    {
      "name": "advanced_auction",
      "description": "View, create, or update advanced auction item bid options."
    },
    {
      "name": "audience_insights",
      "description": "View audience insights."
    },
    {
      "name": "audience_sharing",
      "description": "View, share, or revoke shared audiences.<br>\nAudience Sharing endpoints are not available to all apps,\nif you are interested in using them, reach out to us on our help center page.\n<a href='/docs/getting-started/using-beta-and-restricted-features/'>Learn more</a>."
    },
    {
      "name": "audiences",
      "description": "View, create, or update audiences."
    },
    {
      "name": "billing",
      "description": "View, create, or update information related to billing."
    },
    {
      "name": "boards",
      "description": "View, create, update, or delete information about boards."
    },
    {
      "name": "bulk",
      "description": "Create, update, or download ads-related entities in bulk."
    },
    {
      "name": "campaigns",
      "description": "View, create or update campaigns."
    },
    {
      "name": "catalog_feeds",
      "description": "View and manage catalog feeds.",
      "x-display-name": "feeds"
    },
    {
      "name": "catalog_items",
      "description": "View and manage catalog items directly without a feed.",
      "x-display-name": "items"
    },
    {
      "name": "catalog_product_groups",
      "description": "View and manage catalog product groups using filters.",
      "x-display-name": "product_groups"
    },
    {
      "name": "catalog_regions",
      "description": "View and manage catalog regions defined by sets of postal codes.",
      "x-display-name": "regions"
    },
    {
      "name": "catalog_reports",
      "description": "View and manage reports about catalogs.",
      "x-display-name": "reports"
    },
    {
      "name": "catalog_supplemental",
      "description": "View and manage catalog supplemental items.",
      "x-display-name": "supplemental"
    },
    {
      "name": "catalogs",
      "description": "Manage information about shopping product catalogs and items."
    },
    {
      "name": "conversion_eqs",
      "description": "Get the Event Quality Score (EQS) of your conversion signals."
    },
    {
      "name": "conversion_events",
      "description": "Submit conversion events via the Pinterest API."
    },
    {
      "name": "conversion_tags",
      "description": "View, create, or update conversion tags."
    },
    {
      "name": "customer_lists",
      "description": "View, create, or update customer lists."
    },
    {
      "name": "integrations",
      "description": "View, create, or update commerce integrations."
    },
    {
      "name": "keywords",
      "description": "View, create or update keywords."
    },
    {
      "name": "lead_ads",
      "description": "View, create, or update lead ads."
    },
    {
      "name": "lead_forms",
      "description": "View lead forms."
    },
    {
      "name": "leads_export",
      "description": "Create and export leads information from lead ads."
    },
    {
      "name": "media",
      "description": "Register and manage media uploads."
    },
    {
      "name": "msot_events",
      "description": "Submit Measurement Source of Truth attributed conversion events via the Pinterest API."
    },
    {
      "name": "oauth",
      "description": "Generate and refresh OAuth access tokens."
    },
    {
      "name": "order_lines",
      "description": "View order lines."
    },
    {
      "name": "pins",
      "description": "View, create, update, or delete information about Pins."
    },
    {
      "name": "product_group_promotions",
      "description": "View, create, update, or delete information about promoted product groups."
    },
    {
      "name": "promotions",
      "description": "View, create, update, or delete promotions."
    },
    {
      "name": "resources",
      "description": "View metadata about available metrics and targeting options in the Pinterest API."
    },
    {
      "name": "search",
      "description": "Search for Pins and boards owned by the current user."
    },
    {
      "name": "targeting_template",
      "description": "View, create or update targeting templates."
    },
    {
      "name": "terms",
      "description": "View related and suggested terms for ads targeting."
    },
    {
      "name": "terms_of_service",
      "description": "View Advertising Terms Of Service."
    },
    {
      "name": "user_account",
      "description": "View user accounts associated with a given access token."
    }
  ],
  "x-tagGroups": [
    {
      "name": "Pin and Boards",
      "tags": [
        "pins",
        "boards",
        "media",
        "aggregated_comments",
        "aggregated_pin_data",
        "user_account",
        "entity_history"
      ]
    },
    {
      "name": "Campaign Management",
      "tags": [
        "ad_accounts",
        "campaigns",
        "ad_groups",
        "ads",
        "product_group_promotions",
        "bulk",
        "labels"
      ]
    },
    {
      "name": "Targeting",
      "tags": [
        "audiences",
        "customer_lists",
        "customer_list_uploads",
        "keywords",
        "targeting_template",
        "audience_insights",
        "audience_sharing"
      ]
    },
    {
      "name": "Ad Formats",
      "tags": [
        "lead_forms",
        "lead_ads",
        "leads_export",
        "promotions"
      ]
    },
    {
      "name": "Billing",
      "tags": [
        "billing",
        "order_lines",
        "terms_of_service"
      ]
    },
    {
      "name": "Business Access",
      "tags": [
        "business_access_assets",
        "business_access_invite",
        "business_access_relationships"
      ]
    },
    {
      "name": "Conversions",
      "tags": [
        "conversion_events",
        "conversion_eqs",
        "conversion_tags",
        "msot_events"
      ]
    },
    {
      "name": "Others",
      "tags": [
        "advanced_auction",
        "integrations",
        "oauth",
        "resources",
        "search",
        "terms",
        "pca_uploads"
      ]
    },
    {
      "name": "Shopping",
      "tags": [
        "catalogs",
        "catalog_feeds",
        "catalog_product_groups",
        "catalog_reports",
        "catalog_items",
        "catalog_regions",
        "catalog_supplemental"
      ]
    },
    {
      "name": "Account Claiming",
      "tags": [
        "account_claiming"
      ]
    }
  ]
}